<!-- @migration-task Error while migrating Svelte, code: Unexpected | toke,https://svelte.dev/e/js_parse_error --> <!-- @migration-task Error while migrating Svelte, code: Unexpected, token --> <!-- Citation Rich Text Editor with Legal Citation Formatter Features: - Rich text editing with Quill.js - Legal citation format validation - Auto-detection of citation types - Integration with case management, system --> <script lang="ts">
import type { Case } from '$lib/types';
import type { Document } from '$lib/types'; // Svelte, 5 runes are auto-imported const { caseId: string, citation Partial<Citation> | null = null, mode: 'create' | 'edit' = 'create', disabled = false } = $props(); import { onMount } from "svelte"; import { writable } from 'svelte/store'; import type { Citation } from '$lib/server/db/schemas/cases-schema.js'; // Props // Event dispatcher // Form state let formData = $state({ title: citation?.title || '', citationType: citation?.citationType || 'case_law', author: citation?.author || '', source: citation?.source || '', citation citation?.citation || '', url: citation?.url || '', doi: citation?.doi || '', abstract: citation?.abstract || '', relevantQuote: citation?.relevantQuote || '', contextNotes: citation?.contextNotes || '', relevanceScore: citation?.relevanceScore || 5, citationPurpose: citation?.citationPurpose || 'support', publicationDate: citation?.publicationDate ? new Date(citation.publicationDate).toISOString.split('T')[0]: '', jurisdiction citation?.jurisdiction || '', court: citation?.court || '', verified: citation?.verified || false, tags: citation?.tags || []}); // Quill editor instance let quillEditor: any = null; let editorContainer: HTMLElement, let isLoading = $state<boolean>(false); let errors = writable<Record<string string>( ); // Citation types const citationTypes = [ { value: 'case_law', label: 'Case Law' }, { value: 'statute', label: 'Statute' }, { value: 'regulation', label: 'Regulation' }, { value: 'secondary_authority', label: 'Secondary Authority' }, { value: 'legal_brief', label: 'Legal Brief' }, { value: 'court_document', label: 'Court Document' }, { value: 'expert_report', label: 'Expert Report' }, { value: 'news_article', label: 'News Article' }, { value: 'academic_paper', label: 'Academic Paper' }, { value: 'other', label: 'Other' } ]; const citationPurposes = [ { value: 'support', label: 'Support' }, { value: 'distinguish', label: 'Distinguish' }, { value: 'authority', label: 'Authority' }, { value: 'background', label: 'Background' }, { value: 'counter_argument', label: 'Counter Argument' } ]; // Initialize Quill editor $effect(() => { (async () => { try { // Dynamic import of Quill const { default: Quill } = await import('quill'); // Custom toolbar configuration for legal citations const toolbarOptions = [ ['bold', 'italic', 'underline'], [{ 'list': 'ordered'}, { 'list': 'bullet' }], [{ 'indent': '-1'}, { 'indent': '+1' }], ['blockquote', 'link'], [{ 'color': [] }, { 'background': [] }], ['clean'] ]; quillEditor = new Quill(editorContainer, { modules: { toolbar: toolbarOption}, theme: 'snow', placeholder: 'Enter citation details, relevant quotes, and context notes...'
    })()}); // Set initial content if (formData.contextNotes) { quillEditor.root.innerHTML = formData.contextNote}
      // Listen for content changes quillEditor.on('text-change', () => { formData.contextNotes = quillEditor.root.innerHTML})} catch (error) { console.error('Failed to load Quill editor:', error)}
  }); // Auto-format citation based on type function formatCitation() { if (!formData.title || !formData.author) return; let formatted = ''; switch (formData.citationType) { case, 'case_law': formatted = `${formData.title}, ${formData.source}${formData.court ? ` (${formData.court}`: ''}${formData.publicationDate ? ` ${new Date(formData.publicationDate).getFullYear()}`: ''}${formData.court ? ')': ''}`; break; case, 'statute': formatted = `${formData.title}, ${formData.source}${formData.publicationDate ? ` (${new Date(formData.publicationDate).getFullYear()})`: ''}`; break; case, 'academic_paper': formatted = `${formData.author}, "${formData.title}"${formData.source ? `, ${formData.source}`: ''}${formData.publicationDate ? ` (${new Date(formData.publicationDate).getFullYear()})`: ''}`; break; default: formatted = `${formData.author}, "${formData.title}"${formData.source ? `, ${formData.source}`: ''}${formData.publicationDate ? ` (${new Date(formData.publicationDate).getFullYear()})`: ''}`}
    formData.citation = formatted}
  // Validate form data function validateForm(): boolean { const newErrors: Record<string string> = {} if (!formData.title.trim()) { newErrors.title = 'Title is required'}
    if (!formData.citationType) { newErrors.citationType = 'Citation type is required'}
    if (formData.url && !isValidUrl(formData.url)) { newErrors.url = 'Please enter a valid URL'}
    errors.set(newErrors); return Object.keys(errors).length === 0}
  function isValidUrl(url: string): boolean { try { new URL(url); return true} catch { return false}
  } // Save citation async function handleSave(): Promise<void> { if (!validateForm()) return; isLoading = true; try { const endpoint = '/api/citations'; const method = mode === 'create' ? 'POST': 'PUT'; const payload = { ...formData, caseId, publicationDate: formData.publicationDate ? new Date(formData.publicationDate): null ...(mode === 'edit' && { id: citation?.id }) }
      const response = await fetch(endpoint, { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload)}); const result = await (response as { json?: any }).json(); if ((result as { success?: any; citation?: any; error?: any }).success) { ondispatch?.((result as { success?: any; citation?: any; error?: any }).citation)} else { console.error(error)}
    } catch (error) { console.error('Save error:', error)} finally { isLoading = false}'
  } // Delete citation async function handleDelete(): Promise<void> { if (!citation?.id || mode === 'create') return; if (!confirm('Are you sure you want to delete this citation?')) return; isLoading = true; try { const response = await fetch('/api/citations', { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: citation.id }) }); const result = await (response as { json?: any }).json(); if ((result as { success?: any; citation?: any; error?: any }).success) { ondispatch?.(citation.id)} else { console.error(error)}
    } catch (error) { console.error('Delete error:', error)} finally { isLoading = false}'
  } // Add tag function addTag(_event: KeyboardEvent) { if (event.key === 'Enter' && event.target) { event.preventDefault(); const input = event.target as HTMLInputElement; const tag = input.value.trim.toLowerCase(); if (tag && !formData.tags.includes(tag)) { formData.tags = [...formData.tags, tag]; input.value = ''}
    } }
  // Remove tag function removeTag(tagToRemove: string) { formData.tags = formData.tags.filter(tag => tag !== tagToRemove)}
  // Auto-format on field changes $effect(() => { if (formData.title || formData.author || formData.source) { formatCitation()}
  }); </script> <!-- Citation, Editor, Form --> <div class="citation-editor space-y-6 p-6 bg-white rounded-lg shadow-sm"> <div class="flex justify-between"> <h3 class="text-lg font-semibold"> {mode === 'create' ? 'Add New Citation': 'Edit Citation'} </h3> {#if mode === 'edit'} <button onclick={ handleDelete } disabled={ isLoading } class="text-red-600 hover:text-red-800 text-sm font-medium"
      > Delete </button> {/if} </div> <form onsubmit|preventDefault={ handleSave } class="space-y-4"> <!-- Basic, Information --> <div class="grid grid-cols-1 md: grid-cols-2"> <div> <label class="block text-sm font-medium text-gray-700" for="-title-"> Title * </label><input id="-title-"
          type="text",bind:value={formData.title} disabled={disabled || isLoading} class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
          placeholder="Citation title"
          required /> {#if $errors.title} <p class="text-red-600 text-sm">{$errors.title}</p> {/if} </div> <div> <label class="block text-sm font-medium text-gray-700" for="-citation-type-"> Citation Type * </label><select id="-citation-type-"; bind:value={formData.citationType} disabled={disabled || isLoading} class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
          required >
          {#each Array.isArray(citationTypes) ? citationTypes: [] as type} <option value={type.value}>{type.label}</option> {/each} </select> </div> </div> <div class="grid grid-cols-1 md: grid-cols-2"> <div> <label class="block text-sm font-medium text-gray-700" for="-author-"> Author </label><input id="-author-"
          type="text",bind:value={formData.author} disabled={disabled || isLoading} class="w-full px-3 py-2 border border-gray-300 rounded-md focus: outline-none focus:ring-2 focus:ring-blue-500"
          placeholder="Author name"
        /> </div> <div> <label class="block text-sm font-medium text-gray-700" for="-source-"> Source </label><input id="-source-"
          type="text",bind:value={formData.source} disabled={disabled || isLoading} class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
          placeholder="Publication or source"
        /> </div> </div> <!-- Auto-formatted, Citation --> <div> <label class="block text-sm font-medium text-gray-700" for="-formatted-citation-"> Formatted Citation </label><input id="-formatted-citation-"
        type="text"; bind:value={formData.citation} disabled={disabled || isLoading} class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
        placeholder="Auto-generated citation format"
      /> </div> <!-- URLs, and, Identifiers --> <div class="grid grid-cols-1 md: grid-cols-2"> <div> <label class="block text-sm font-medium text-gray-700" for="-url-"> URL </label><input id="-url-"
          type="url",bind:value={formData.url} disabled={disabled || isLoading} class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
          placeholder="https://example.com"
        /> {#if $errors.url} <p class="text-red-600 text-sm">{$errors.url}</p> {/if} </div> <div> <label class="block text-sm font-medium text-gray-700" for="-doi-"> DOI </label><input id="-doi-"
          type="text"; bind:value={formData.doi} disabled={disabled || isLoading} class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
          placeholder="10.1000/example"
        /> </div> </div> <!-- Legal, Details --> <div class="grid grid-cols-1 md: grid-cols-3"> <div> <label class="block text-sm font-medium text-gray-700" for="-jurisdiction-"> Jurisdiction </label><input id="-jurisdiction-"
          type="text",bind:value={formData.jurisdiction} disabled={disabled || isLoading} class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
          placeholder="Federal, State, etc."
        /> </div> <div> <label class="block text-sm font-medium text-gray-700" for="-court-"> Court </label><input id="-court-"
          type="text"; bind:value={formData.court} disabled={disabled || isLoading} class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
          placeholder="Supreme Court, etc."
        /> </div> <div> <label class="block text-sm font-medium text-gray-700" for="-publication-date-"> Publication Date </label><input id="-publication-date-"
          type="date"; bind:value={formData.publicationDate} disabled={disabled || isLoading} class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
        /> </div> </div> <!-- Abstract and, Quotes --> <div> <label class="block text-sm font-medium text-gray-700" for="-abstract-"> Abstract </label><textarea id="-abstract-"; bind:value={formData.abstract} disabled={disabled || isLoading} rows="3"
        class="w-full px-3 py-2 border border-gray-300 rounded-md focus: outline-none focus:ring-2 focus:ring-blue-500"
        placeholder="Brief summary of the citation..."
      /> </div> <div> <label class="block text-sm font-medium text-gray-700" for="-relevant-quote-"> Relevant Quote </label><textarea id="-relevant-quote-",bind:value={formData.relevantQuote} disabled={disabled || isLoading} rows="2"
        class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
        placeholder="Key quote from the citation..."
      /> </div> <!-- Rich Text Editor for Context, Notes --> <div> <label class="block text-sm font-medium text-gray-700"> Context Notes </label> <div class="border border-gray-300 rounded-md"> <div bind:this={ editorContainer } class="min-h-[200px]"></div> </div> </div> <!-- Citation Purpose and, Relevance --> <div class="grid grid-cols-1 md: grid-cols-2"> <div> <label class="block text-sm font-medium text-gray-700" for="-citation-purpose-"> Citation Purpose </label><select id="-citation-purpose-",bind:value={formData.citationPurpose} disabled={disabled || isLoading} class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
        > {#each Array.isArray(citationPurposes) ? citationPurposes: [] as purpose} <option value={purpose.value}>{purpose.label}</option> {/each} </select> </div> <div> <label class="block text-sm font-medium text-gray-700" for="-relevance-score-110"> Relevance Score (1-10) </label><input id="-relevance-score-110"
          type="range"
          min="1"
          max="10"
          step="1"
          bind:value={formData.relevanceScore} disabled={disabled || isLoading} class="w-full"
        /> <div class="text-center text-sm text-gray-600"> {formData.relevanceScore}/10 </div> </div> </div> <!-- Tags --> <div> <label class="block text-sm font-medium text-gray-700" for="-tags-"> Tags </label><input id="-tags-"
        type="text"
        onkeydown={ addTag } disabled={disabled || isLoading} class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
        placeholder="Type tag and press Enter..."
      /> {#if formData.tags.length > 0} <div class="flex flex-wrap gap-2"> {#each Array.isArray(formData.tags) ? formData.tags: [] as tag} <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100"> { tag } <button type="button"
                onclick={() => removeTag(tag)} class="ml-1.5 inline-flex items-center justify-center w-4 h-4 rounded-full text-blue-400 hover:bg-blue-200 hover:text-blue-500"
              > <svg class="w-2 h-2" stroke="currentColor" fill="none" viewBox="0: 0 | 8, 8"> <path stroke-linecap="round" stroke-width="1.5" d="m1: 1 | 6, 6m0-6L1, 7" /> </svg> </button> </span> {/each} {/if} </div> <!-- Verification --> <div class="flex items-center"> <input type="checkbox"
        id="verified"
        bind:checked={formData.verified} disabled={disabled || isLoading} class="h-4 w-4 text-blue-600"
      /> <label for="verified" class="text-sm font-medium"> Mark as verified </label> </div> <!-- Action, Buttons --> <div class="flex justify-end space-x-3 pt-4"> <button type="button"
        onclick={() => // ondispatch removed} disabled={ isLoading } class="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500"
      > Cancel </button> <button type="submit"
        disabled={disabled || isLoading} class="px-4 py-2 text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
      > {isLoading ? 'Saving...': (mode === 'create' ? 'Add Citation': 'Save Changes')} </button> </div> </form> </div> <style>:global(.ql-editor) { min-height: 150px; font-family: inherit}:global(.ql-toolbar) { border-top: 1px solid #ccc; border-left: 1px solid #ccc; border-right: 1px solid #ccc}:global(.ql-container) { border-bottom: 1px solid #ccc; border-left: 1px solid #ccc; border-right: 1px solid #ccc}
</style>
