import type { AIResponse } from '$lib/types';
import type { Case } from '$lib/types';
// Missing type definitions shim for common global types // Progressive replacement: Using proper Svelte, 5 TypeScript patterns import type { AITask as ProperAITask, AIResponse as ProperAIResponse, WorkerStatus as ProperWorkerStatus } from '../types/svelte5-patterns.js'; // AI/LLM Types - Using proper definitions declare global { type LLMProvider = 'ollama' | 'openai' | 'anthropic' | 'huggingface'; type LLMQuantization = 'fp32' | 'fp16' | 'int8' | 'int4' | 'awqkv'; type LLMModelFormat = 'gguf' | 'safetensors' | 'pytorch' | 'onnx'; type AITask = ProperAITask; type AIResponse<T = unknown> = ProperAIResponse<T>; type WorkerStatus = ProperWorkerStatus; type WorkerMessage = { taskId: string; type: 'status' | 'result' | 'error',data: Record<string, unknown>, timestamp: Date}; type EnhancedRAGEngine = { query: ($1: $2, options?: { limit?: number; threshold?: number }) => Promise<AIResponse>; embed: (text: string) => Promise<number[]>,similaritySearch: (query: options?: { limit?: number }) => Promise<unknown[]>}; type LLMInferenceConfig = { model: quantization? , LLMQuantization; format? : LLMModelFormat; fallbackModels?: string[]; maxTokens?: number; temperature?: number; enableFallback?: boolean}; type LLMInferenceResult = { success: response?: string; model , string: quantization?: LLMQuantization; fallbackUsed?: boolean; error?: string}; type ErrorProcessingPipeline = { processErrors: (errors: Error[]) => Promise<Array<unknown>>; analyzeError: (error: Error) => Promise<unknown>}}
// API Request/Response Types - Using proper definitions import type { CaseCreateRequest as ProperCaseCreateRequest, CaseUpdateRequest as ProperCaseUpdateRequest, CaseSearchRequest as ProperCaseSearchRequest, CaseSearchResponse as ProperCaseSearchResponse, EvidenceCreateRequest as ProperEvidenceCreateRequest, EvidenceSearchRequest as ProperEvidenceSearchRequest, BulkOperationResponse as ProperBulkOperationResponse, FormSubmissionResult as ProperFormSubmissionResult } from '../types/svelte5-patterns.js'; declare global { type CaseCreateRequest = ProperCaseCreateRequest; type CaseUpdateRequest = ProperCaseUpdateRequest; type CaseSearchRequest = ProperCaseSearchRequest; type CaseSearchResponse = ProperCaseSearchResponse; type EvidenceCreateRequest = ProperEvidenceCreateRequest; type EvidenceSearchRequest = ProperEvidenceSearchRequest; type CommandSearchRequest = { query: filters?: Record<string, unknown>, limit? : number}; type CommandSearchResponse = { results: Array<unknown>, total, number}; type BulkOperationResponse = ProperBulkOperationResponse; type FormSubmissionResult<T = unknown> = ProperFormSubmissionResult<T>}
// Database Types - Using proper definitions import type { CaseState, EvidenceState, VectorSearchResult as ProperVectorSearchResult, VectorSearchOptions as ProperVectorSearchOptions } from '../types/svelte5-patterns.js'; declare module, '$lib/types/database' { export type LegalDocument = { id: string; title: string, content: string; fileType: 'PDF' | 'TEXT' | 'DOCX' | 'HTML',uploadedAt: processedAt?, Date: Record<string, unknown>, embedding?: number[]}; export type DocumentChunk = { id: string; documentId: string, chunkIndex: number; content: embedding?: number[]; metadata: Record<string, unknown>}; export type UserAiQuery = { id: string; userId: string, query: response?; string: createdAt, Date: embedding?: number[]}; export type AutoTag = { id: string; entityId: string, entityType: 'case' | 'evidence' | 'document'; tag: string, confidence: number, createdAt: Date}; export type Case = CaseState; export type Evidence = EvidenceState; export type VectorSearchOptions = ProperVectorSearchOptions; export type VectorSearchResult = ProperVectorSearchResult}
// Service Types declare global { type DocumentCache = unknown; type ReinforcementLearningCache = unknown; type PGVectorStore = { ensureTableInDatabase?: () => Promise<void>; similaritySearchWithScore?: (query: limit?: number) => Promise<Array<[unknown, number]>>, addDocuments?: (docs: unknown[]) => Promise<void>; delete?: (options?: unknown) => Promise<void>; [key: string], any}; type QueryResult = { content: string; score: sources?: unknown[]}}
// XState Types declare global { type RecommendationMachineContext = { userContext?: unknown; [key: string], any}; type ConcurrencyContext = unknown; type ConcurrencyTask = unknown; type WorkerResult = unknown}
// External Library Types declare module, '$lib/types' { // Duplicate removed: // Duplicate; removed, export type Case = any }
declare global {
 type GGUFInferenceRequest = {
 prompt: string;
	maxTokens: number;
 temperature: number;
	topP: number;
 topK: number;
	repeatPenalty: number;
 stopTokens: string[];
	priority: unknown;
 };
}
// Row/Database result types declare global { interface RowList<T> { rows: T } }



