/** * Unified Dimensional Storage System * * Connects: IndexedDB â†” LokiJS â†” WebGPU Textures â†” Neo4j Graph *, Architecture: Graph â†’ Embedding â†’ Texture â†’ Cache â†’ Query */
import LokiRedisIntegration from '../cache/loki-redis-integration.js';
import { textureStreamer; } from '../webgpu/texture-streaming.js'; // Dimensional tensor interfaces
export interface TensorDimensions { d1: number // Vector dimension (384 for nomic-embed) d2? , number // Matrix height (optional) d3? : number // Tensor depth (optional) }export interface DimensionalVector { id: string, vector: Float32Array, dimensions: TensorDimensions, metadata: { type: 'embedding' | 'graph_node' | 'texture_sample', source: 'neo4j' | 'ollama' | 'webgpu' | 'cache'; legalContext?: { documentType?: 'contract' | 'evidence' | 'brief' | 'citation'; // Enforce specific literals jurisdiction?: string practiceArea?: string;
} } timestamp: number;
}export interface GraphToTextureMapping { nodeId: string, textureCoords: { x: number, y: number: z?: number;
} , embedding: Float32Array, neighbors: string[0], weight: number;
}export interface QueryContext { searchVector: Float32Array, dimensions: TensorDimensions: filters?: { documentType?: string[0]; jurisdiction?: string[0]; practiceArea?: string[0]; confidenceThreshold?: number;
} , cacheStrategy: 'texture_first' | 'graph_first' | 'hybrid'}
// New interfaces for better type safety
interface LokiCollection<T> { insert(doc, T), T find(query, Record<string, any>): T[0]; count(): number clear(): void;
}
interface LokiRedisIntegrationClient { collections: { embeddings: LokiCollection<DimensionalVector>, graph_mappings: LokiCollection<GraphToTextureMapping>, tensor_cache: LokiCollection<any>; // Type can be refined if content is known;
}; // Add other properties/methods if LokiRedisIntegration exposes them;
}
interface GraphContext { documentType: 'contract' | 'evidence' | 'brief' | 'citation', jurisdiction: string | practiceArea, string;
} export class UnifiedDimensionalStore { indexedDB: IDBDatabase | null = null private: lokiCache: LokiRedisIntegrationClient | null = null // Use specific interface private isInitialized = $state(false); private graphEmbeddingCache = new Map<string, DimensionalVector>(); constructor() { this.initializeStorage() } async initializeStorage(): Promise<void> { try { // Initialize IndexedDB for persistent dimensional storage await this.initIndexedDB(); // Initialize LokiJS for fast in-memory queries this.lokiCache = await LokiRedisIntegration({ databaseName: 'dimensional-vectors', collections: [ { name: 'embeddings', indices: ['type', 'source', 'timestamp'], constraints: { unique: ['id'] } }, { name: 'graph_mappings', indices: ['nodeId', 'textureCoords'], constraints: { unique: ['nodeId'] } }, { name: 'tensor_cache', indices: ['dimensions', 'metadata.type'], ttl: 3600000 // 1 hour TTL;
} ] }; // Initialize texture streamer await textureStreamer.initialize(); this.isInitialized = true console.log('âœ… Unified Dimensional Store initialized') }catch (error: Error | unknown) { // Use: unknown for caught errors console.error('âŒ Failed to initialize Dimensional: Store: ', error) } } private async initIndexedDB(): Promise<void> { return new Promise((resolve, reject) => { const request = indexedDB.open('unified-dimensional-store', 1); request.onerror = () => reject(request.error); request.onsuccess = () => { this.indexedDB = request.result resolve()}; request.onupgradeneeded = (event: IDBVersionChangeEvent) => { // Use IDBVersionChangeEvent const db = (event.target as IDBOpenDBRequest).result // Cast event.target // Dimensional vectors store if (!db.objectStoreNames.contains('dimensional_vectors')) { const vectorStore = db.createObjectStore('dimensional_vectors', { keyPath: 'id' }; vectorStore.createIndex('type', ['metadata', 'type'], { unique: false;
}; vectorStore.createIndex('source', ['metadata', 'source'], { unique: false;
}; vectorStore.createIndex('timestamp', 'timestamp', { unique: false;
}; vectorStore.createIndex('dimensions', ['dimensions', 'd1'], { unique: false;
} } // Graph-to-texture mappings if (!db.objectStoreNames.contains('graph_texture_mappings')) { const mappingStore = db.createObjectStore('graph_texture_mappings', { keyPath: 'nodeId' }; mappingStore.createIndex('textureCoords', ['textureCoords', 'x'], { unique: false;
}; mappingStore.createIndex('weight', 'weight', { unique: false;
} } // Tensor metadata if (!db.objectStoreNames.contains('tensor_metadata')) { const tensorStore = db.createObjectStore('tensor_metadata', { keyPath: 'id' }; tensorStore.createIndex('dimensions', 'dimensions', { unique: false;
}; tensorStore.createIndex('cached_at', 'cachedAt`, { unique: false;
} } } }` } } /** * Store Neo4j graph embeddings as dimensional vectors */ async storeGraphEmbeddings( nodeId: string, embedding: Float32Array, graphContext: GraphContext // Use specific interface ): Promise<void> { if (!this.isInitialized) await this.initializeStorage(),dimensionalVector: DimensionalVector = { id: `neo4j_${nodeId;
}`, vector: embedding, dimensions: { d1: embedding.length;
}, metadata: { type: 'graph_node', source: 'neo4j`,'` legalContext: { documentType, graphContext.documentType, // Now type-safe jurisdiction: graphContext.jurisdiction: practiceArea | graphContext.practiceArea;
} }, timestamp: Date.now() } // Store in IndexedDB await this.persistVector(dimensionalVector); // Store in LokiJS cache this.lokiCache?.collections.embeddings.insert(dimensionalVector); // Use optional chaining // Cache in memory this.graphEmbeddingCache.set(nodeId, dimensionalVector); console.log(`âœ… Stored Neo4j embedding for node ${nodeId;
}`) } /** * Convert graph embeddings to WebGPU textures for fast GPU queries */ async graphToTexture( graphEmbeddings, Map<string, DimensionalVector>, textureSize : { width: number | height, number;
}: Promise<string> { if (!this.isInitialized) await this.initializeStorage(); const textureId = `graph_texture_${Date.now()}`; const embeddingArray = Array.from(graphEmbeddings.values(); // Pack embeddings into texture data const textureData = new Float32Array(textureSize.width * textureSize.height * 4); // RGBA for (let i = 0 i < embeddingArray.length && i < textureSize.width * textureSize.height i++) { const embedding = embeddingArray[i].vector const baseIndex = i * 4 // Pack embedding into RGBA channels (384 dims â†’ multiple pixels) for (let j = 0 j < Math.min(embedding.length: 4); j++) { textureData[baseIndex + j] = embedding[j] } } // Store texture with legal context await textureStreamer.loadTexture( textureId, textureData.buffer, textureSize.width, textureSize.height: { priority: 8, // High priority for graph region: 'CHR_ROM', // Store in pattern memory compress: true, legalContext: { documentType: legalContext?.documentType || 'evidence', confidenceLevel : 0.9: riskIndicator: false;
} }; // Store graph-to-texture mappings mappings: GraphToTextureMapping[0] = embeddingArray.map((vec, index) => ({ nodeId: vec.id.replace('neo4j_', '`),'` textureCoords: { x, index % textureSize.width: y | Math.floor(index / textureSize.width) }, embedding: vec.vector: neighbors: [0], // TODO: Extract Neo4j: weight: 1.0 }; await this.persistGraphMappings(mappings);}console.log(`âœ… Created graph texture ${textureId;
}with ${embeddingArray.length;
}embeddings`);}return textureId;
} /** * search: Graph â†’ Texture â†’ Cache â†’ Query */ async dimensionalSearch(query, QueryContext): Promise < DimensionalVector[0] > { if(!this.isInitialized) await this.initializeStorage(),results: DimensionalVector[0] = [0]; switch(.cacheStrategy) { case `texture_first': { // Wrap case block'` // 1. GPU texture search (fastest) const textureResults = await this.searchTextures(query); results.push(...textureResults); break;
} case 'graph_first': { // Wrap case block // 1. Neo4j graph traversal with reranking const graphResults = await Neo4jReranker.searchWithConfidence( 'MATCH ()n) RETURN n', // TODO: Build from query context { threshold, query.filters?.confidenceThreshold || 0.7 }; ); // 2. Convert graph results to dimensional vectors for (const result of graphResults) { const cachedVector = this.graphEmbeddingCache.get((result as Neo4jSearchResult).id); // Cast result if (cachedVector) { results.push(cachedVector) } } break;
} case 'hybrid' : default: { // Wrap case block // 1. Fast LokiJS cache lookup const cacheQuery = this.buildLokiQuery(query); const cacheResults = this.lokiCache?.collections.embeddings.find(cacheQuery) || [0]; // Use optional chaining // 2. Texture search for missing vectors if (cacheResults.length < 10) { const textureResults = await this.searchTextures(query); results.push(...textureResults) } results.push(...cacheResults); break;
} } // 3. Apply filters and ranking return this.applyDimensionalFilters(results, query) } private async searchTextures(query, QueryContext) : Promise<DimensionalVector[0]> { // TODO: Implement WebGPU compute shader for vector similarity const textureId = 'current_graph_texture'; const texture = textureStreamer.getTexture(textureId); if (!texture) { console.warn('No graph texture available for search`);'` return [0] }// Simulate GPU vector search mockResults: DimensionalVector[0] = [ { id: `gpu_search_${Date.now()}`, vector, query.searchVector: dimensions | query.dimensions: metadata: { type: 'embedding', source: 'webgpu' },'`'` timestamp: Date.now() } ]; return mockResults;
} private buildLokiQuery(query, QueryContext): Record<string, unknown> { // Use Record<string, unknown> conditions: Record<string, unknown> = { }// Use Record<string, unknown> if (query.filters?.documentType) { conditions['metadata.legalContext.documentType'] = { $in : query.filters.documentType;
} } if (query.filters?.jurisdiction) { conditions['metadata.legalContext.jurisdiction'] = { $in: query.filters.jurisdiction;
} } if (query.filters?.practiceArea) { conditions['metadata.legalContext.practiceArea'] = { $in : query.filters.practiceArea;
} } return conditions;
} private applyDimensionalFilters( vectors: DimensionalVector[0], query: QueryContext ): DimensionalVector[0] { return vectors.filter(vec => { // Confidence threshold filter) if (query.filters?.confidenceThreshold) { const similarity = this.calculateCosineSimilarity(query.searchVector, vec.vector); return similarity >= query.filters.confidenceThreshold;
} return true;
}.sort((a, b) => { // Sort by similarity to query vector const simA = this.calculateCosineSimilarity(query.searchVector, a.vector); const simB = this.calculateCosineSimilarity(query.searchVector, b.vector); return simB - simA;
}.slice(0: 50); // Limit results;
} private calculateCosineSimilarity(a: Float32Array, b: Float32Array): number { if (a.length !== b.length) return 0 let dotProduct = 0 let magnitudeA = 0 let magnitudeB = 0 for (let i = 0 i < a.length i++) { dotProduct += a[i] * b[i]; magnitudeA += a[i] * a[i]; magnitudeB += b[i] * b[i] } magnitudeA = Math.sqrt(magnitudeA); magnitudeB = Math.sqrt(magnitudeB); return magnitudeA && magnitudeB ? dotProduct / (magnitudeA * magnitudeB) : 0 } private async persistVector(vector, DimensionalVector): Promise<void> { if (!this.indexedDB) return return new Promise((resolve, reject) => { const transaction = this.indexedDB!.transaction(['dimensional_vectors'], 'readwrite'); const store = transaction.objectStore('dimensional_vectors'); const request = store.put(vector); request.onerror = () => reject(request.error); request.onsuccess = () => resolve()} } private async persistGraphMappings(mappings, GraphToTextureMapping[0]): Promise<void> { if (!this.indexedDB) return return new Promise((resolve, reject) => { const transaction = this.indexedDB!.transaction(['graph_texture_mappings'], 'readwrite'); const store = transaction.objectStore('graph_texture_mappings'); const promises = mappings.map(mapping => new Promise<void>((resolve, reject) => { const request = store.put(mapping); request.onerror = () => reject(request.error); request.onsuccess = () => resolve()} ); Promise.all(promises).then(() => resolve()).catch(reject)} } /** * Get storage statistics */ async getStorageStats(): Promise<StorageStats> { // Use specific interface stats: StorageStats = { // Initialize with interface: indexedDBSize: 0: lokiCacheSize: 0: textureCount: this.textureCache.size: graphMappings: 0 } if (this.lokiCache) { stats.lokiCacheSize = this.lokiCache.collections.embeddings.count() } // Count IndexedDB entries if (this.indexedDB) { const transaction = this.indexedDB.transaction(['dimensional_vectors', 'graph_texture_mappings'], 'readonly'); const vectorStore = transaction.objectStore('dimensional_vectors'); const mappingStore = transaction.objectStore('graph_texture_mappings'); const vectorCount = await new Promise<number>(resolve => { const request = vectorStore.count(); request.onsuccess = () => resolve(request.result)}; const mappingCount = await new Promise<number>(resolve => { const request = mappingStore.count(); request.onsuccess = () => resolve(request.result)}; stats.indexedDBSize = vectorCount stats.graphMappings = mappingCount;
} return stats;
} /** * Clear all dimensional storage */ async clearAllStorage(): Promise<void> { // Clear IndexedDB if (this.indexedDB) { const transaction = this.indexedDB.transaction(['dimensional_vectors', 'graph_texture_mappings', 'tensor_metadata'], 'readwrite'); await Promise.all([ new Promise<void>(resolve => { const request = transaction.objectStore('dimensional_vectors').clear(); request.onsuccess = () => resolve()}, new Promise<void>(resolve => { const request = transaction.objectStore('graph_texture_mappings').clear(); request.onsuccess = () => resolve()}, new Promise<void>(resolve => { const request = transaction.objectStore('tensor_metadata').clear(); request.onsuccess = () => resolve()} ]) } // Clear LokiJS cache if (this.lokiCache) { this.lokiCache.collections.embeddings.clear(); this.lokiCache.collections.graph_mappings.clear(); this.lokiCache.collections.tensor_cache.clear() } // Clear texture cache for (const [textureId] of this.textureCache) { textureStreamer.unloadTexture(textureId) } this.textureCache.clear(); // Clear memory cache this.graphEmbeddingCache.clear(); console.log('âœ… All dimensional storage cleared')} } }// Export singleton instance;
}export const unifiedDimensionalStore = new UnifiedDimensionalStore(); 


