# Qdrant Configuration for Memory-Optimized RAG System
# This configuration balances performance with resource usage

log_level: INFO

service:
  host: 0.0.0.0
  http_port: 6333
  grpc_port: 6334
  enable_cors: true
  max_request_size_mb: 32
  max_timeout_seconds: 60

storage:
  # Memory optimization settings
  performance:
    max_search_threads: 2
    max_optimization_threads: 1

  # Memory mapping threshold for large collections
  optimizers:
    # Use memory mapping for collections larger than 100k vectors
    memmap_threshold: 100000
    # Indexing threshold for automatic HNSW creation
    indexing_threshold: 10000
    # Flush interval in seconds
    flush_interval_sec: 5
    # Optimize on close
    max_segment_size: 100000

cluster:
  enabled: false

# Default collection configuration
collections:
  default_segment_number: 1
  # Vector parameters
  vector_size: 1536
  distance: Cosine

  # HNSW parameters for balanced performance/memory
  hnsw_config:
    m: 16 # Number of connections per node
    ef_construct: 200 # Size of the dynamic candidate list during construction
    ef: 128 # Size of the dynamic candidate list during search
    max_indexing_threads: 1 # Limit indexing threads for memory
    on_disk: true # Store index on disk to save memory

# Quantization for memory reduction (optional)
quantization:
  scalar:
    type: int8
    quantile: 0.99
    always_ram: true

# Telemetry (disable for privacy)
telemetry_disabled: true

# Experimental features
experimental:
  # Enable if you need advanced filtering
  search_batching:
    max_batch_size: 100
    timeout_seconds: 1
