trtllm-build \
  --checkpoint_dir /workspace/engines/gemma3-legal-production/checkpoint \
  --output_dir /workspace/engines/gemma3_12b_engine \
  --max_batch_size 1 \
  --max_input_len 2048 \
  --max_seq_len 4096 \
  --kv_cache_type paged \
  --remove_input_padding enable \
  --context_fmha enable \
  --use_paged_context_fmha enable \
  --gpt_attention_plugin float16 \
  --gemm_plugin float16 \
  --multiple_profiles enable \
  --logits_dtype float16 \
  --monitor_memory