// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.23.4
// source: gpu_service.proto

// Unified into embed package for single Go package in this directory.

package embed

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GPUProcessingService_ProcessStream_FullMethodName      = "/embed.GPUProcessingService/ProcessStream"
	GPUProcessingService_ProcessSemantic_FullMethodName    = "/embed.GPUProcessingService/ProcessSemantic"
	GPUProcessingService_QueryRAG_FullMethodName           = "/embed.GPUProcessingService/QueryRAG"
	GPUProcessingService_StreamRAG_FullMethodName          = "/embed.GPUProcessingService/StreamRAG"
	GPUProcessingService_GetRecommendations_FullMethodName = "/embed.GPUProcessingService/GetRecommendations"
	GPUProcessingService_HealthCheck_FullMethodName        = "/embed.GPUProcessingService/HealthCheck"
	GPUProcessingService_GetMetrics_FullMethodName         = "/embed.GPUProcessingService/GetMetrics"
)

// GPUProcessingServiceClient is the client API for GPUProcessingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definitions
type GPUProcessingServiceClient interface {
	// Bidirectional streaming for real-time processing
	ProcessStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DataChunk, ProcessingResult], error)
	// Semantic operations
	ProcessSemantic(ctx context.Context, in *SemanticRequest, opts ...grpc.CallOption) (*ProcessingResult, error)
	// Enhanced RAG pipeline
	QueryRAG(ctx context.Context, in *RAGRequest, opts ...grpc.CallOption) (*RAGResponse, error)
	StreamRAG(ctx context.Context, in *RAGRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RAGResponse], error)
	// Recommendation system
	GetRecommendations(ctx context.Context, in *RecommendationRequest, opts ...grpc.CallOption) (*RecommendationResponse, error)
	// System health and metrics
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error)
}

type gPUProcessingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGPUProcessingServiceClient(cc grpc.ClientConnInterface) GPUProcessingServiceClient {
	return &gPUProcessingServiceClient{cc}
}

func (c *gPUProcessingServiceClient) ProcessStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DataChunk, ProcessingResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GPUProcessingService_ServiceDesc.Streams[0], GPUProcessingService_ProcessStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DataChunk, ProcessingResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GPUProcessingService_ProcessStreamClient = grpc.BidiStreamingClient[DataChunk, ProcessingResult]

func (c *gPUProcessingServiceClient) ProcessSemantic(ctx context.Context, in *SemanticRequest, opts ...grpc.CallOption) (*ProcessingResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessingResult)
	err := c.cc.Invoke(ctx, GPUProcessingService_ProcessSemantic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUProcessingServiceClient) QueryRAG(ctx context.Context, in *RAGRequest, opts ...grpc.CallOption) (*RAGResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RAGResponse)
	err := c.cc.Invoke(ctx, GPUProcessingService_QueryRAG_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUProcessingServiceClient) StreamRAG(ctx context.Context, in *RAGRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RAGResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GPUProcessingService_ServiceDesc.Streams[1], GPUProcessingService_StreamRAG_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RAGRequest, RAGResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GPUProcessingService_StreamRAGClient = grpc.ServerStreamingClient[RAGResponse]

func (c *gPUProcessingServiceClient) GetRecommendations(ctx context.Context, in *RecommendationRequest, opts ...grpc.CallOption) (*RecommendationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendationResponse)
	err := c.cc.Invoke(ctx, GPUProcessingService_GetRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUProcessingServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, GPUProcessingService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUProcessingServiceClient) GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricsResponse)
	err := c.cc.Invoke(ctx, GPUProcessingService_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GPUProcessingServiceServer is the server API for GPUProcessingService service.
// All implementations must embed UnimplementedGPUProcessingServiceServer
// for forward compatibility.
//
// Service definitions
type GPUProcessingServiceServer interface {
	// Bidirectional streaming for real-time processing
	ProcessStream(grpc.BidiStreamingServer[DataChunk, ProcessingResult]) error
	// Semantic operations
	ProcessSemantic(context.Context, *SemanticRequest) (*ProcessingResult, error)
	// Enhanced RAG pipeline
	QueryRAG(context.Context, *RAGRequest) (*RAGResponse, error)
	StreamRAG(*RAGRequest, grpc.ServerStreamingServer[RAGResponse]) error
	// Recommendation system
	GetRecommendations(context.Context, *RecommendationRequest) (*RecommendationResponse, error)
	// System health and metrics
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	GetMetrics(context.Context, *MetricsRequest) (*MetricsResponse, error)
	mustEmbedUnimplementedGPUProcessingServiceServer()
}

// UnimplementedGPUProcessingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGPUProcessingServiceServer struct{}

func (UnimplementedGPUProcessingServiceServer) ProcessStream(grpc.BidiStreamingServer[DataChunk, ProcessingResult]) error {
	return status.Errorf(codes.Unimplemented, "method ProcessStream not implemented")
}
func (UnimplementedGPUProcessingServiceServer) ProcessSemantic(context.Context, *SemanticRequest) (*ProcessingResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessSemantic not implemented")
}
func (UnimplementedGPUProcessingServiceServer) QueryRAG(context.Context, *RAGRequest) (*RAGResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryRAG not implemented")
}
func (UnimplementedGPUProcessingServiceServer) StreamRAG(*RAGRequest, grpc.ServerStreamingServer[RAGResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamRAG not implemented")
}
func (UnimplementedGPUProcessingServiceServer) GetRecommendations(context.Context, *RecommendationRequest) (*RecommendationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecommendations not implemented")
}
func (UnimplementedGPUProcessingServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedGPUProcessingServiceServer) GetMetrics(context.Context, *MetricsRequest) (*MetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedGPUProcessingServiceServer) mustEmbedUnimplementedGPUProcessingServiceServer() {}
func (UnimplementedGPUProcessingServiceServer) testEmbeddedByValue()                              {}

// UnsafeGPUProcessingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GPUProcessingServiceServer will
// result in compilation errors.
type UnsafeGPUProcessingServiceServer interface {
	mustEmbedUnimplementedGPUProcessingServiceServer()
}

func RegisterGPUProcessingServiceServer(s grpc.ServiceRegistrar, srv GPUProcessingServiceServer) {
	// If the following call pancis, it indicates UnimplementedGPUProcessingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GPUProcessingService_ServiceDesc, srv)
}

func _GPUProcessingService_ProcessStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GPUProcessingServiceServer).ProcessStream(&grpc.GenericServerStream[DataChunk, ProcessingResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GPUProcessingService_ProcessStreamServer = grpc.BidiStreamingServer[DataChunk, ProcessingResult]

func _GPUProcessingService_ProcessSemantic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SemanticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUProcessingServiceServer).ProcessSemantic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUProcessingService_ProcessSemantic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUProcessingServiceServer).ProcessSemantic(ctx, req.(*SemanticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUProcessingService_QueryRAG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RAGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUProcessingServiceServer).QueryRAG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUProcessingService_QueryRAG_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUProcessingServiceServer).QueryRAG(ctx, req.(*RAGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUProcessingService_StreamRAG_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RAGRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GPUProcessingServiceServer).StreamRAG(m, &grpc.GenericServerStream[RAGRequest, RAGResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GPUProcessingService_StreamRAGServer = grpc.ServerStreamingServer[RAGResponse]

func _GPUProcessingService_GetRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUProcessingServiceServer).GetRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUProcessingService_GetRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUProcessingServiceServer).GetRecommendations(ctx, req.(*RecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUProcessingService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUProcessingServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUProcessingService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUProcessingServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUProcessingService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUProcessingServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUProcessingService_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUProcessingServiceServer).GetMetrics(ctx, req.(*MetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GPUProcessingService_ServiceDesc is the grpc.ServiceDesc for GPUProcessingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GPUProcessingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "embed.GPUProcessingService",
	HandlerType: (*GPUProcessingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessSemantic",
			Handler:    _GPUProcessingService_ProcessSemantic_Handler,
		},
		{
			MethodName: "QueryRAG",
			Handler:    _GPUProcessingService_QueryRAG_Handler,
		},
		{
			MethodName: "GetRecommendations",
			Handler:    _GPUProcessingService_GetRecommendations_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _GPUProcessingService_HealthCheck_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _GPUProcessingService_GetMetrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessStream",
			Handler:       _GPUProcessingService_ProcessStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamRAG",
			Handler:       _GPUProcessingService_StreamRAG_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gpu_service.proto",
}
