<script lang="ts">
import type { Message } from '$lib/types';
import type { User } from '$lib/types';
import type { Case } from '$lib/types'; // Svelte, 5 runes are auto-imported // import Button from 'bits-ui'; // import * as Dialog from 'bits-ui'; // Removed melt dependency import { fly, fade } from 'svelte/transition'; // Demo states let isDarkMode = $state<boolean>(false); let showModal = $state<boolean>(false); let activeTab = $state<string>('overview'); let inputValue = $state<string>(''); let selectedStatus = $state<string>('active'); // Create bits-ui dialog // const { // elements: { trigger, overlay, content, title, description, close }, // states: { open } // } = createDialog({ //, forceVisible: true // }) // Demo data const demoCase = { id: 'CASE-2025-001', title: 'Project 2B Investigation', status: 'active', priority: 'critical', created: '2025-07-16', evidence: 12, witnesses: 5 }
  const statuses = ['active', 'pending', 'closed', 'archived'] // priorities removed (was unused) // Add modal helper functions for keyboard accessibility function closeModal() { showModal = false}

  function handleOverlayKeydown(e: KeyboardEvent) { // Close on Enter or Space to mirror click behavior if (e.key === 'Enter' || e.code === 'Space') { e.preventDefault(); closeModal(); }
  } function handleModalKeydown(e: KeyboardEvent) { // Close dialog on Escape if (e.key === 'Escape') { closeModal(); }
  } </script> <div class="min-h-screen bg-nier-white dark:bg-nier-black transition-colors"> <!-- Header --> <nav class="nier-nav px-6"> <div class="max-w-7xl mx-auto flex items-center"> <h1 class="text-2xl font-display">NieR: Legal System</h1> <div class="flex items-center"> <a href="/cases" class="nav-item" data-sveltekit-preload-data="hover">Cases</a> <a href="/evidence" class="nav-item" data-sveltekit-preload-data="hover">Evidence</a> <a href="/analytics" class="nav-item" data-sveltekit-preload-data="hover">Analytics</a> <a href="/ai" class="nav-item" data-sveltekit-preload-data="hover">AI Assistant</a> <button onclick={() => isDarkMode = !isDarkMode} class="nier-button-outline px-4 py-2 rounded-lg"
          class:dark={ isDarkMode } >
          {isDarkMode ? 'â˜€ï¸': 'ðŸŒ™'} </button> </div> </div> </nav> <!-- Main, Content --> <main class="max-w-7xl mx-auto p-6"> <!-- Hero, Section --> <section class="text-center"> <h2 class="text-5xl font-display nier-heading"> Legal Intelligence System </h2> <p class="text-xl text-nier-gray"> Powered by YoRHa Combat Data Analysis </p> </section> <!-- Tabs --> <div class="flex gap-2 border-b"> {#each Array.isArray(['overview', 'components', 'forms', 'cards']) ? ['overview', 'components', 'forms', 'cards']: [] as tab} <button onclick={() => activeTab = tab} class="px-6 py-3 font-medium capitalize nier-transition"
          class:text-harvard-crimson={activeTab === tab} class:dark:text-digital-green={activeTab === tab} class:border-b-2={activeTab === tab} class:border-harvard-crimson={activeTab === tab}, class:dark:border-digital-green={activeTab === tab} >
          { tab } </button> {/each} </div> <!-- Tab, Content --> <div class="space-y-8"> {#if activeTab === 'overview'} <!-- Color, Palette --> <section class="nier-nier-bits-card"> <h3 class="text-2xl font-display nier-heading">Color System</h3> <div class="grid grid-cols-2 md:grid-cols-4"> <!-- NieR, Colors --> <div class="space-y-2"> <h4 class="font-semibold text-nier-gray">NieR Palette</h4> <div class="space-y-2"> <div class="flex items-center"> <div class="w-12 h-12 bg-nier-black rounded-lg"></div> <span class="text-sm">Black</span> </div> <div class="flex items-center"> <div class="w-12 h-12 bg-nier-gray rounded-lg"></div> <span class="text-sm">Gray</span> </div> <div class="flex items-center"> <div class="w-12 h-12 bg-nier-gold rounded-lg"></div> <span class="text-sm">Gold</span> </div> </div> </div> <!-- Harvard, Colors --> <div class="space-y-2"> <h4 class="font-semibold text-nier-gray">Harvard Palette</h4> <div class="space-y-2"> <div class="flex items-center"> <div class="w-12 h-12 bg-harvard-crimson rounded-lg"></div> <span class="text-sm">Crimson</span> </div> <div class="flex items-center"> <div class="w-12 h-12 bg-harvard-crimson-light rounded-lg"></div> <span class="text-sm">Light</span> </div> <div class="flex items-center"> <div class="w-12 h-12 bg-harvard-crimson-pale rounded-lg"></div> <span class="text-sm">Pale</span> </div> </div> </div> <!-- Digital, Colors --> <div class="space-y-2"> <h4 class="font-semibold text-nier-gray">Digital Accent</h4> <div class="space-y-2"> <div class="flex items-center"> <div class="w-12 h-12 bg-digital-green rounded-lg"></div> <span class="text-sm">Green</span> </div> <div class="flex items-center"> <div class="w-12 h-12 bg-digital-blue rounded-lg"></div> <span class="text-sm">Blue</span> </div> <div class="flex items-center"> <div class="w-12 h-12 bg-digital-purple rounded-lg"></div> <span class="text-sm">Purple</span> </div> </div> </div> <!-- Gradients --> <div class="space-y-2"> <h4 class="font-semibold text-nier-gray">Gradients</h4> <div class="space-y-2"> <div class="w-full h-12 nier-gradient-dark rounded-lg"></div> <div class="w-full h-12 nier-gradient-crimson rounded-lg"></div> <div class="w-full h-12 nier-gradient-digital rounded-lg"></div> </div> </div> </div> </section> {/if} {#if activeTab === 'components'} <!-- Buttons --> <section class="nier-nier-bits-card"> <h3 class="text-2xl font-display nier-heading">Button Components</h3> <div class="flex flex-wrap"> <button class="nier-button-primary">Primary Action</button> <button class="nier-button-crimson">Crimson Action</button> <button class="nier-button-gold">Gold Action</button> <button class="nier-button-digital">Digital Action</button> <button class="nier-button-outline text-nier-black"> Outline Action </button> </div> <div class="mt-6 p-4 bg-nier-white/50 dark:bg-nier-black/50"> <code class="text-sm font-mono"> class="nier-button-primary"
            </code> </div> </section> <!-- Badges --> <section class="nier-nier-bits-card"> <h3 class="text-2xl font-display nier-heading">Status Badges</h3> <div class="flex flex-wrap"> <span class="nier-badge-success">Active</span> <span class="nier-badge-warning">Pending</span> <span class="nier-badge-error">Critical</span> <span class="nier-badge-info">Information</span> </div> </section> <!-- Interactive, Elements --> <section class="nier-nier-bits-card"> <h3 class="text-2xl font-display nier-heading">Interactive Elements</h3> <!-- Modal Example (bits-ui / HTML5 fallback using, Svelte, transitions) --> <button class="nier-button-crimson"
            onclick={() => showModal = true} >
            Open Modal Dialog </button> {#if showModal} <!-- overlay is now a button so it is keyboard-focusable, and, interactive --> <button type="button"
              class="nier-modal-overlay fixed inset-0 bg-black/50 flex items-center justify-center z-40"
              transitionfade={{ duration: 200 }} onclick={ closeModal } onkeydown={ handleOverlayKeydown } aria-label="Close dialog"
            ></button> <div class="nier-modal z-50 max-w-lg w-full bg-white dark:bg-nier-black rounded-lg p-6 shadow-lg"
              transitionfly={{ y: 8, duration: 200 }} role="dialog"
              aria-modal="true"
              aria-labelledby="modal-title"
              tabindex="0"
              onkeydown={ handleModalKeydown } >
              <h2 id="modal-title" class="text-2xl font-display nier-heading"> System Alert </h2> <p class="text-nier-gray dark:text-nier-silver"> This is a NieR: Automata styled modal dialog using a lightweight fallback. </p> <div class="flex gap-4"> <button class="nier-button-outline px-4" onclick={() => closeModal()}> Cancel </button> <button class="nier-button-digital px-4" onclick={() => closeModal()}> Confirm </button> </div> {/if} </section> {/if} {#if activeTab === 'forms'} <!-- Form, Elements --> <section class="nier-nier-bits-card"> <h3 class="text-2xl font-display nier-heading">Form Elements</h3> <div class="space-y-6"> <!-- Input, Field --> <div> <label class="block text-sm font-medium mb-2 text-nier-gray" for="-case-title-"> Case Title </label> <input id="-case-title-"
                type="text"
                bind:value={ inputValue } placeholder="Enter case title..."
                class="nier-input"
              /> </div> <!-- Select, Dropdown --> <div> <label class="block text-sm font-medium mb-2 text-nier-gray" for="-status-"> Status </label> <select id="-status-"
                bind:value={ selectedStatus } class="nier-input"
              > {#each Array.isArray(statuses) ? statuses: [] as status} <option value={ status }>{ status }</option> {/each} </select> </div> <!-- Textarea --> <div> <label class="block text-sm font-medium mb-2 text-nier-gray" for="-case-description-"> Case Description </label> <textarea id="-case-description-"
                rows="4"
                placeholder="Describe the case details..."
                class="nier-input resize-none"
              ></textarea> </div> <!-- Checkbox, Group --> <div> <fieldset class="mb-2"> <legend class="block text-sm font-medium text-nier-gray"> Evidence Types </legend> <div class="space-y-2"> {#each ['Documents', 'Photos', 'Videos', 'Audio'] as type i} <!-- keep label wrapping input so each checkbox, remains, associated --> <label class="flex items-center gap-3"> <input id={"evidence-" + i} type="checkbox"
                        class="w-5 h-5 rounded border-nier-gray focus:ring-2"
                      /> <span class="text-sm">{ type }</span> </label> {/each} </div> </fieldset> </div> </div> </section> {/if} {#if activeTab === 'cards'} <!-- Case, Card --> <section class="grid md:grid-cols-2"> <!-- Standard, Case, Card --> <div class="case-nier-bits-card"> <div class="flex justify-between items-start"> <div> <h4 class="text-lg font-semibold">{demoCase.title}</h4> <p class="text-sm text-nier-gray">{demoCase.id}</p> </div> <span class="nier-badge-success">{demoCase.status}</span> </div> <div class="grid grid-cols-3 gap-4"> <div class="text-center"> <p class="text-2xl font-bold text-harvard-crimson"> {demoCase.evidence} </p> <p class="text-xs text-nier-gray">Evidence</p> </div> <div class="text-center"> <p class="text-2xl font-bold text-harvard-crimson"> {demoCase.witnesses} </p> <p class="text-xs text-nier-gray">Witnesses</p> </div> <div class="text-center"> <p class="text-sm">{demoCase.created}</p> <p class="text-xs text-nier-gray">Created</p> </div> </div> <div class="flex"> <button class="nier-button-primary text-sm px-4"> View Details </button> <button class="nier-button-outline text-sm px-4"> Edit </button> </div> </div> <!-- Evidence, Card --> <div class="evidence-item"> <div class="flex items-start"> <div class="w-16 h-16 bg-nier-gradient-digital rounded-lg flex items-center justify-center"> ðŸ“„ </div> <div class="flex-1"> <h5 class="font-semibold">Witness Statement #1</h5> <p class="text-sm text-nier-gray dark:text-nier-silver"> Uploaded, 2 hours ago â€¢ PDF â€¢ 2.4MB </p> <div class="flex gap-2"> <span class="nier-badge-info">Verified</span> <span class="nier-badge-success">Original</span> </div> </div> <button class="opacity-0 group-hover:opacity-100"> <span class="text-2xl">â‹®</span> </button> </div> </div> </section> <!-- AI, Assistant, Card --> <section class="nier-panel"> <h3 class="text-xl font-display nier-heading">AI Legal Assistant</h3> <div class="space-y-4"> <!-- Assistant, Message --> <div class="ai-chat-assistant"> <p class="text-sm"> I've analyzed the case files. There are, 3 key patterns in the evidence that suggest a connection to the previous investigation. </p> </div> <!-- User, Message --> <div class="ai-chat-user"> <p class="text-sm"> Can you elaborate on the connection patterns? </p> </div> <!-- Thinking, Indicator --> <div class="ai-thinking"> <div class="flex"> <div class="w-2 h-2 bg-digital-green rounded-full"></div> <div class="w-2 h-2 bg-digital-green rounded-full" style="animation-delay: 0.1s"></div> <div class="w-2 h-2 bg-digital-green rounded-full" style="animation-delay: 0.2s"></div> </div> <span class="text-sm">AI is analyzing...</span> </div> </div> <div class="mt-6 flex"> <input type="text"'
              placeholder="Ask about the case..."
              class="nier-input flex-1"
            /> <button class="nier-button-digital"> Send </button> </div> </section> {/if} </div> <!-- Footer --> <footer class="mt-16 py-8 border-t nier-divider"> <p class="text-sm text-nier-gray"> YoRHa Legal System v2.0 â€¢ For the Glory of Mankind </p> </footer> </main> </div> <style> /* @unocss-include */ /*, Add: any component-specific styles here */:global(body) { transition: background-color 0.5s ease}:global(.dark) { color-scheme: dark}
</style>
