-- Fixed PostgreSQL Migration Script
-- Replaces problematic SERIAL types with proper PostgreSQL syntax

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS vector;

-- Fix serial type issue by using INTEGER with GENERATED BY DEFAULT AS IDENTITY
-- This replaces the problematic "ALTER COLUMN id SET DATA TYPE serial"

-- Drop and recreate canvas_states table with proper serial column
DROP TABLE IF EXISTS canvas_states CASCADE;

CREATE TABLE canvas_states (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id UUID,
    canvas_data TEXT,
    metadata TEXT,
    created_by UUID,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Grant proper permissions
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO postgres;

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_canvas_states_report_id ON canvas_states(report_id);
CREATE INDEX IF NOT EXISTS idx_canvas_states_created_by ON canvas_states(created_by);
