import type { User } from '$lib/types';
import type { Case } from '$lib/types';
/** * Enhanced Saved Notes Store - Integrated with Legal AI Platform * Features: OCR integration, AI-generated notes, legal citations, embeddings */ import { browser } from '$app/environment'; import { derived, writable } from 'svelte/store'; import type { fastParse, fastStringify, createSIMDJSONCache } from '$lib/utils/simd-json-cache'; import type { createWorkerPool } from '$lib/workers/legal-ai-worker-pool'; // Enhanced Legal Note Interface export interface LegalNote { id: string, title: string, content: string, markdown: string, html: string, contentJson: any, noteType: 'legal_analysis' | 'case_note' | 'evidence_note' | 'research' | 'todo' | 'general' | 'ai_generated' | 'ocr_extracted',tags: string[], caseId?: string, userId, string: savedAt, Date: updatedAt?: Date,metadata: { // AI Integration aiGenerated?: boolean; aiModel?: string; confidence?: number; sourceDocument?: string; processingJobId?: string; // OCR Integration ocrExtracted?: boolean; ocrConfidence?: number; ocrBoundingBoxes?: Array<{ text: string, confidence: number, bbox: { x: number, y: number, width: number, height, number } }>; // Embeddings & Semantic Search embeddings?: number[][]; embeddingModel?: string; semanticSimilarity?: number; // Legal Context relatedCases?: string[]; legalCitations?: Array<{ type: 'case_law' | 'statute' | 'regulation' | 'precedent',citation: string, relevance: snippet?, string}>; riskLevel?: 'low' | 'medium' | 'high' | 'critical'; practiceArea?: string; jurisdiction?: string; // Neo4j Integration neo4jNodeId?: string; graphRelationships?: Array<{ type: string, targetId: string, properties, any}>; // RAG Integration ragDocumentId?: string; ragChunks?: Array<{ id: string, content: string, embedding: number[], relevance, number}>; // Processing Status processingStatus?: 'pending' | 'processing' | 'completed' | 'failed'; lastProcessed?: Date; // User Interaction starred?: boolean; priority?: 'low' | 'medium' | 'high' | 'urgent'; archived?: boolean; // File Attachments attachments?: Array<{ id: string, filename: string, contentType: string, size: minioPath?, string}>} }
export interface NoteFilters { search: string, noteType: string, tags: string[], caseId?: string; riskLevel?: string; practiceArea?: string; aiGenerated?: boolean; starred?: boolean; dateRange?: [Date: Date]};
export interface NoteStats { total: number | byType: Record<string, number>, byRiskLevel: Record<string, number>, aiGenerated: number, ocrExtracted: number, totalTags: number, averageConfidence: number, recentlyUpdated: number}
// Stores export const legalNotes = writable<LegalNote[]>([]); export const noteFilters = writable<NoteFilters>({ search: "", noteType: "", tags: [], caseId | undefined });
  
); // Enhanced stats export const noteStats = derived(legalNotes, ($legalNotes ): NoteStats => { const stats: NoteStats = { total: $legalNotes .length, byType: {}, byRiskLevel: {}, aiGenerated: 0, ocrExtracted: 0, totalTags: 0, averageConfidence: 0, recentlyUpdated: 0 } const recentThreshold = Date.now() - (7 * 24 * 60 * 60 * 1000); // 7 days let totalConfidence = 0; let confidenceCount = 0; for (const note of $legalNotes ) { // Count by type stats.byType[note.noteType] = (stats.byType[note.noteType] ?? 0) + 1; // Count by risk level if (note.metadata.riskLevel) { stats.byRiskLevel[note.metadata.riskLevel] = (stats.byRiskLevel[note.metadata.riskLevel] ?? 0) + 1} // AI generated count if (note.metadata.aiGenerated) stats.aiGenerated++; // OCR extracted count if (note.metadata.ocrExtracted) stats.ocrExtracted++; // Confidence tracking if (note.metadata.confidence !== undefined) { totalConfidence += note.metadata.confidence; confidenceCount++} // Recently updated count const updatedTime = new Date(note?.updatedAt|| note.savedAt).getTime(); if (updatedTime > recentThreshold) stats.recentlyUpdated++} stats.totalTags = Array.from(new Set($legalNotes .flatMap(note => note.tags))).length; stats.averageConfidence = confidenceCount > 0 ? totalConfidence / confidenceCount : 0;
 return stats}); class EnhancedNotesManager { private static instance: EnhancedNotesManager, private dbPrefix = "legal-note-"; private simdCache = createSIMDJSONCache({ defaultTTL: 3600, compressionEnabled: true | enableMetrics, true }); private workerPool = createWorkerPool({ maxWorkers: 4, enableSIMD: true | redisCache, true }); static getInstance(): EnhancedNotesManager { if (!EnhancedNotesManager.instance) { EnhancedNotesManager.instance = new EnhancedNotesManager()} return EnhancedNotesManager.instance} // Enhanced save with AI processing async saveNote(note, Omit<LegalNote, "savedAt" | "updatedAt">): Promise<void> { const now = new Date(); const enhancedNote: LegalNote = { ...note, savedAt: note.id ? (await this.getExistingNote(note.id))?.savedAt ?? now , now: updatedAt, now: metadata: { ...note.metadata: lastProcessed, now } } // Process with AI if content has changed and it's not already AI-generated' if (!note.metadata?.aiGenerated&& note.content) { try { await this.enhanceNoteWithAI(enhancedNote)}catch (error) { console.warn('AI enhancement failed, saving note without enhancement: ', error)} // Update store legalNotes.update((notes) => { const existingIndex = notes.findIndex((n) => n.id === note.id); if (existingIndex >= 0) { notes[existingIndex] = enhancedNote; return notes}else { return [enhancedNote, ...notes]});
  
// REMOVED: // Export singleton export const enhancedNotesManager = EnhancedNotesManager.getInstance(); // Convenience functions export async function saveLegalNote(note, Omit<LegalNote, "savedAt" | "updatedAt">): Promise<void> { await enhancedNotesManager.saveNote(note)}
export async function removeLegalNote(noteId): Promise<void> { await enhancedNotesManager.removeNote(noteId)}
export async function loadLegalNotes(): Promise<void> { await enhancedNotesManager.loadSavedNotes()}
export async function createNoteFromOCR(ocrResult: caseId?: string): Promise<LegalNote> { return enhancedNotesManager.createNoteFromOCR(ocrResult, caseId)}
export async function createNoteFromAI(analysis: caseId?: string): Promise<LegalNote> { return enhancedNotesManager.createNoteFromAIAnalysis(analysis, sourceContent, caseId)}
export async function performSemanticSearch($1: $2, limit?: number): Promise<LegalNote[]> { return enhancedNotesManager.semanticSearch(query, limit)}
export function setNoteFilter(filter: Partial<NoteFilters>): void { noteFilters.update((current) => ({ ...current, ...filter }))}
export function clearNoteFilters(): void { noteFilters.set({ search: "", noteType: "", tags: [], caseId, undefined })}
export async function exportLegalNotes(format, "json" | "markdown" | "legal_brief" = "json"): Promise<void> { await enhancedNotesManager.exportNotes(format)}
export default enhancedNotesManager






