// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.23.4
// source: ingest.proto

package embed // unified (was ingest)

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	ChunkIndex    uint32                 `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	TotalChunks   uint32                 `protobuf:"varint,3,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	MimeType      string                 `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Hash          string                 `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,8,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Final         bool                   `protobuf:"varint,9,opt,name=final,proto3" json:"final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestChunk) Reset() {
	*x = IngestChunk{}
	mi := &file_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestChunk) ProtoMessage() {}

func (x *IngestChunk) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestChunk.ProtoReflect.Descriptor instead.
func (*IngestChunk) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *IngestChunk) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *IngestChunk) GetChunkIndex() uint32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *IngestChunk) GetTotalChunks() uint32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *IngestChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *IngestChunk) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *IngestChunk) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *IngestChunk) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *IngestChunk) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *IngestChunk) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

type IngestAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DocId          string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	ReceivedChunks uint32                 `protobuf:"varint,2,opt,name=received_chunks,json=receivedChunks,proto3" json:"received_chunks,omitempty"`
	Complete       bool                   `protobuf:"varint,3,opt,name=complete,proto3" json:"complete,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Message        string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IngestAck) Reset() {
	*x = IngestAck{}
	mi := &file_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestAck) ProtoMessage() {}

func (x *IngestAck) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestAck.ProtoReflect.Descriptor instead.
func (*IngestAck) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *IngestAck) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *IngestAck) GetReceivedChunks() uint32 {
	if x != nil {
		return x.ReceivedChunks
	}
	return 0
}

func (x *IngestAck) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *IngestAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IngestAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_ingest_proto protoreflect.FileDescriptor

const file_ingest_proto_rawDesc = "" +
	"\n" +
	"\fingest.proto\x12\x06ingest\"\xc9\x02\n" +
	"\vIngestChunk\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\rR\n" +
	"chunkIndex\x12!\n" +
	"\ftotal_chunks\x18\x03 \x01(\rR\vtotalChunks\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04hash\x18\x06 \x01(\tR\x04hash\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x121\n" +
	"\x04meta\x18\b \x03(\v2\x1d.ingest.IngestChunk.MetaEntryR\x04meta\x12\x14\n" +
	"\x05final\x18\t \x01(\bR\x05final\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x99\x01\n" +
	"\tIngestAck\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12'\n" +
	"\x0freceived_chunks\x18\x02 \x01(\rR\x0ereceivedChunks\x12\x1a\n" +
	"\bcomplete\x18\x03 \x01(\bR\bcomplete\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage2E\n" +
	"\tIngestion\x128\n" +
	"\fStreamChunks\x12\x13.ingest.IngestChunk\x1a\x11.ingest.IngestAck(\x01B6Z4legal-ai-production/proto/ingest;ingestb\x06proto3"

var (
	file_ingest_proto_rawDescOnce sync.Once
	file_ingest_proto_rawDescData []byte
)

func file_ingest_proto_rawDescGZIP() []byte {
	file_ingest_proto_rawDescOnce.Do(func() {
		file_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingest_proto_rawDesc), len(file_ingest_proto_rawDesc)))
	})
	return file_ingest_proto_rawDescData
}

var file_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ingest_proto_goTypes = []any{
	(*IngestChunk)(nil), // 0: ingest.IngestChunk
	(*IngestAck)(nil),   // 1: ingest.IngestAck
	nil,                 // 2: ingest.IngestChunk.MetaEntry
}
var file_ingest_proto_depIdxs = []int32{
	2, // 0: ingest.IngestChunk.meta:type_name -> ingest.IngestChunk.MetaEntry
	0, // 1: ingest.Ingestion.StreamChunks:input_type -> ingest.IngestChunk
	1, // 2: ingest.Ingestion.StreamChunks:output_type -> ingest.IngestAck
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ingest_proto_init() }
func file_ingest_proto_init() {
	if File_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingest_proto_rawDesc), len(file_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ingest_proto_goTypes,
		DependencyIndexes: file_ingest_proto_depIdxs,
		MessageInfos:      file_ingest_proto_msgTypes,
	}.Build()
	File_ingest_proto = out.File
	file_ingest_proto_goTypes = nil
	file_ingest_proto_depIdxs = nil
}
