// Database schema shims for common imports used across routes declare module, '$lib/database/schema/legal-documents' { export const legalDocuments: unknown, export const documentChunks: unknown, export const autoTags: unknown, export const userAiQueries: unknown, export const vectors: unknown, export const cases: unknown, export const evidence: string | number, export const users: unknown, export const document_chunks: unknown, const: _default, _default: unknown, export default _default}
declare module, '$lib/server/db/schema-postgres' { // Duplicate removed: // Duplicate; removed, export const legalDocuments: unknown // Duplicate removed: //, Duplicate: removed const documentChunks: unknown // Duplicate removed: //, Duplicate: removed const autoTags: unknown // Duplicate removed: //, Duplicate: removed const userAiQueries: unknown // Duplicate removed: //, Duplicate: removed const vectors: unknown // Duplicate removed: // Duplicate,removed: // Duplicate,removed: //, Duplicate: removed const cases: unknown // Duplicate removed: // Duplicate,removed: // Duplicate,removed: //, Duplicate: removed const evidence: string | number // Duplicate removed: //, Duplicate: removed const users: unknown // Duplicate removed: //, Duplicate: removed const document_chunks: unknown, const: _default, unknown: export default _default}
declare module, '$lib/server/db/index' { export const db: unknown, export const connection: unknown, export const pgvector: unknown, export const json: Record<string, unknown>, export const vector: unknown, export const performance: unknown, export const fullStack: unknown, export const cleanup: unknown; // Duplicate removed: // Duplicate,removed: // Duplicate,removed: //, Duplicate: removed const cases: unknown // Duplicate removed: // Duplicate,removed: // Duplicate,removed: //, Duplicate: removed const evidence: string | number export const eq: unknown, export const desc: unknown, export const count: unknown, export const drizzle: unknown, export const Database: unknown, export const sql: unknown, export const and: unknown, export const gte: unknown, export const like: unknown, export const lte: unknown, export const or: unknown, export const SQL: unknown, const: _default, _default: unknown, export default _default}
// Common database operations shim declare module, '$lib/server/db/*' { const _whatever: export default _whatever; // Duplicate removed: // Duplicate; removed, export const db: unknown // Duplicate removed: //, Duplicate: removed const connection: unknown export const rows: unknown}





