// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: cuda.proto

package cuda

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CUDAService_StreamingInference_FullMethodName    = "/cuda.CUDAService/StreamingInference"
	CUDAService_StreamingEmbedding_FullMethodName    = "/cuda.CUDAService/StreamingEmbedding"
	CUDAService_StreamingVectorSearch_FullMethodName = "/cuda.CUDAService/StreamingVectorSearch"
	CUDAService_GetGPUMetrics_FullMethodName         = "/cuda.CUDAService/GetGPUMetrics"
	CUDAService_HealthCheck_FullMethodName           = "/cuda.CUDAService/HealthCheck"
)

// CUDAServiceClient is the client API for CUDAService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CUDAService provides high-performance tensor operations for AI inference
type CUDAServiceClient interface {
	// StreamingInference provides real-time AI inference with tensor streaming
	StreamingInference(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InferenceRequest, InferenceResponse], error)
	// StreamingEmbedding generates embeddings with tensor streaming
	StreamingEmbedding(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EmbeddingRequest, EmbeddingResponse], error)
	// StreamingVectorSearch performs similarity search with tensor operations
	StreamingVectorSearch(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[VectorSearchRequest, VectorSearchResponse], error)
	// GetGPUMetrics returns current GPU utilization and performance metrics
	GetGPUMetrics(ctx context.Context, in *GPUMetricsRequest, opts ...grpc.CallOption) (*GPUMetricsResponse, error)
	// HealthCheck returns service status and capabilities
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type cUDAServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCUDAServiceClient(cc grpc.ClientConnInterface) CUDAServiceClient {
	return &cUDAServiceClient{cc}
}

func (c *cUDAServiceClient) StreamingInference(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InferenceRequest, InferenceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CUDAService_ServiceDesc.Streams[0], CUDAService_StreamingInference_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InferenceRequest, InferenceResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CUDAService_StreamingInferenceClient = grpc.BidiStreamingClient[InferenceRequest, InferenceResponse]

func (c *cUDAServiceClient) StreamingEmbedding(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EmbeddingRequest, EmbeddingResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CUDAService_ServiceDesc.Streams[1], CUDAService_StreamingEmbedding_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EmbeddingRequest, EmbeddingResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CUDAService_StreamingEmbeddingClient = grpc.BidiStreamingClient[EmbeddingRequest, EmbeddingResponse]

func (c *cUDAServiceClient) StreamingVectorSearch(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[VectorSearchRequest, VectorSearchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CUDAService_ServiceDesc.Streams[2], CUDAService_StreamingVectorSearch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[VectorSearchRequest, VectorSearchResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CUDAService_StreamingVectorSearchClient = grpc.BidiStreamingClient[VectorSearchRequest, VectorSearchResponse]

func (c *cUDAServiceClient) GetGPUMetrics(ctx context.Context, in *GPUMetricsRequest, opts ...grpc.CallOption) (*GPUMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GPUMetricsResponse)
	err := c.cc.Invoke(ctx, CUDAService_GetGPUMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cUDAServiceClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, CUDAService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CUDAServiceServer is the server API for CUDAService service.
// All implementations must embed UnimplementedCUDAServiceServer
// for forward compatibility.
//
// CUDAService provides high-performance tensor operations for AI inference
type CUDAServiceServer interface {
	// StreamingInference provides real-time AI inference with tensor streaming
	StreamingInference(grpc.BidiStreamingServer[InferenceRequest, InferenceResponse]) error
	// StreamingEmbedding generates embeddings with tensor streaming
	StreamingEmbedding(grpc.BidiStreamingServer[EmbeddingRequest, EmbeddingResponse]) error
	// StreamingVectorSearch performs similarity search with tensor operations
	StreamingVectorSearch(grpc.BidiStreamingServer[VectorSearchRequest, VectorSearchResponse]) error
	// GetGPUMetrics returns current GPU utilization and performance metrics
	GetGPUMetrics(context.Context, *GPUMetricsRequest) (*GPUMetricsResponse, error)
	// HealthCheck returns service status and capabilities
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedCUDAServiceServer()
}

// UnimplementedCUDAServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCUDAServiceServer struct{}

func (UnimplementedCUDAServiceServer) StreamingInference(grpc.BidiStreamingServer[InferenceRequest, InferenceResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamingInference not implemented")
}
func (UnimplementedCUDAServiceServer) StreamingEmbedding(grpc.BidiStreamingServer[EmbeddingRequest, EmbeddingResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamingEmbedding not implemented")
}
func (UnimplementedCUDAServiceServer) StreamingVectorSearch(grpc.BidiStreamingServer[VectorSearchRequest, VectorSearchResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamingVectorSearch not implemented")
}
func (UnimplementedCUDAServiceServer) GetGPUMetrics(context.Context, *GPUMetricsRequest) (*GPUMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGPUMetrics not implemented")
}
func (UnimplementedCUDAServiceServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedCUDAServiceServer) mustEmbedUnimplementedCUDAServiceServer() {}
func (UnimplementedCUDAServiceServer) testEmbeddedByValue()                     {}

// UnsafeCUDAServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CUDAServiceServer will
// result in compilation errors.
type UnsafeCUDAServiceServer interface {
	mustEmbedUnimplementedCUDAServiceServer()
}

func RegisterCUDAServiceServer(s grpc.ServiceRegistrar, srv CUDAServiceServer) {
	// If the following call pancis, it indicates UnimplementedCUDAServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CUDAService_ServiceDesc, srv)
}

func _CUDAService_StreamingInference_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CUDAServiceServer).StreamingInference(&grpc.GenericServerStream[InferenceRequest, InferenceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CUDAService_StreamingInferenceServer = grpc.BidiStreamingServer[InferenceRequest, InferenceResponse]

func _CUDAService_StreamingEmbedding_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CUDAServiceServer).StreamingEmbedding(&grpc.GenericServerStream[EmbeddingRequest, EmbeddingResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CUDAService_StreamingEmbeddingServer = grpc.BidiStreamingServer[EmbeddingRequest, EmbeddingResponse]

func _CUDAService_StreamingVectorSearch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CUDAServiceServer).StreamingVectorSearch(&grpc.GenericServerStream[VectorSearchRequest, VectorSearchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CUDAService_StreamingVectorSearchServer = grpc.BidiStreamingServer[VectorSearchRequest, VectorSearchResponse]

func _CUDAService_GetGPUMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GPUMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CUDAServiceServer).GetGPUMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CUDAService_GetGPUMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CUDAServiceServer).GetGPUMetrics(ctx, req.(*GPUMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CUDAService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CUDAServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CUDAService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CUDAServiceServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CUDAService_ServiceDesc is the grpc.ServiceDesc for CUDAService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CUDAService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cuda.CUDAService",
	HandlerType: (*CUDAServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGPUMetrics",
			Handler:    _CUDAService_GetGPUMetrics_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _CUDAService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamingInference",
			Handler:       _CUDAService_StreamingInference_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamingEmbedding",
			Handler:       _CUDAService_StreamingEmbedding_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamingVectorSearch",
			Handler:       _CUDAService_StreamingVectorSearch_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "cuda.proto",
}
