name: "gemma_projector"
platform: "onnxruntime_onnx"
max_batch_size: 4

input [
  {
    name: "image_features"
    data_type: TYPE_FP32
    dims: [ -1, 1152 ]
  }
]

output [
  {
    name: "projected_tokens"
    data_type: TYPE_FP32
    dims: [ -1, 3840 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 0 ]
  }
]

dynamic_batching {
  preferred_batch_size: [ 1, 2, 4 ]
  max_queue_delay_microseconds: 200
}
