
// Rust WASM Bridge for Legal AI Native Windows Integration
// Provides secure filesystem access, system monitoring, and performance optimization

import type { SystemInfo, FileSystemResult, PerformanceMetrics } from '$lib/types/rust-bridge';

// WASM module interface (generated by wasm-pack)
export interface WasmModule {
  WindowsServiceBridge: new () => WindowsServiceBridge;
  process_legal_text_fast: (text: string) => string;
  optimize_embedding_vector: (vector: Float32Array) => Float32Array;
  compute_cosine_similarity: (vec1: Float32Array, vec2: Float32Array) => number;
  batch_process_documents: (documents: string) => string;
}

export interface WindowsServiceBridge {
  get_system_info(): string;
  access_filesystem(path: string): string;
  detect_gpu_acceleration(): string;
  get_performance_metrics(): string;
  process_legal_document(documentData: string): string;
  check_windows_services(): string;
}

let wasmModule: WasmModule | null = null;
let bridge: WindowsServiceBridge | null = null;

// Initialize the Rust WASM bridge
export async function initRustBridge(): Promise<boolean> {
  try {
    // Dynamic import of WASM module (needs to be built with wasm-pack)
    // Note: This path assumes the WASM package is built to this location
    const wasm = await import('./pkg/webasm_bridge');
    await wasm.default(); // Initialize WASM module
    
    wasmModule = wasm as any as WasmModule;
    bridge = new wasmModule.WindowsServiceBridge();
    
    console.log('✅ Rust WASM bridge initialized successfully');
    return true;
  } catch (error: any) {
    console.warn('⚠️ Rust WASM bridge initialization failed:', error);
    console.log('💡 Run `wasm-pack build --target web --out-dir ../sveltekit-frontend/src/lib/wasm/pkg` in rust-services/webasm-bridge/');
    return false;
  }
}

// Get comprehensive system information
export function getSystemInfo(): SystemInfo | null {
  if (!bridge) {
    console.warn('Rust bridge not initialized');
    return null;
  }
  
  try {
    const info = bridge.get_system_info();
    return JSON.parse(info) as SystemInfo;
  } catch (error: any) {
    console.error('Failed to get system info:', error);
    return null;
  }
}

// Secure filesystem access for legal documents
export function accessFilesystem(path: string): FileSystemResult | null {
  if (!bridge) {
    console.warn('Rust bridge not initialized');
    return null;
  }
  
  try {
    const result = bridge.access_filesystem(path);
    return JSON.parse(result) as FileSystemResult;
  } catch (error: any) {
    console.error('Failed to access filesystem:', error);
    return null;
  }
}

// Detect GPU acceleration capabilities
export function detectGpuAcceleration(): string[] {
  if (!bridge) {
    console.warn('Rust bridge not initialized');
    return [];
  }
  
  try {
    const gpuInfo = bridge.detect_gpu_acceleration();
    return JSON.parse(gpuInfo) as string[];
  } catch (error: any) {
    console.error('Failed to detect GPU acceleration:', error);
    return [];
  }
}

// Get real-time performance metrics
export function getPerformanceMetrics(): PerformanceMetrics | null {
  if (!bridge) {
    console.warn('Rust bridge not initialized');
    return null;
  }
  
  try {
    const metrics = bridge.get_performance_metrics();
    return JSON.parse(metrics) as PerformanceMetrics;
  } catch (error: any) {
    console.error('Failed to get performance metrics:', error);
    return null;
  }
}

// Process legal document with native performance
export function processLegalDocument(documentData: string): object | null {
  if (!bridge) {
    console.warn('Rust bridge not initialized');
    return null;
  }
  
  try {
    const result = bridge.process_legal_document(documentData);
    return JSON.parse(result);
  } catch (error: any) {
    console.error('Failed to process legal document:', error);
    return null;
  }
}

// Check Windows services status
export function checkWindowsServices(): object[] {
  if (!bridge) {
    console.warn('Rust bridge not initialized');
    return [];
  }
  
  try {
    const services = bridge.check_windows_services();
    return JSON.parse(services) as object[];
  } catch (error: any) {
    console.error('Failed to check Windows services:', error);
    return [];
  }
}

// High-performance text processing
export function processLegalTextFast(text: string): object | null {
  if (!wasmModule) {
    console.warn('WASM module not initialized');
    return null;
  }
  
  try {
    const result = wasmModule.process_legal_text_fast(text);
    return JSON.parse(result);
  } catch (error: any) {
    console.error('Failed to process legal text:', error);
    return null;
  }
}

// Optimize embedding vectors for better performance
export function optimizeEmbeddingVector(vector: number[]): number[] | null {
  if (!wasmModule) {
    console.warn('WASM module not initialized');
    return null;
  }
  
  try {
    const float32Vector = new Float32Array(vector);
    const optimized = wasmModule.optimize_embedding_vector(float32Vector);
    return Array.from(optimized);
  } catch (error: any) {
    console.error('Failed to optimize embedding vector:', error);
    return null;
  }
}

// Fast cosine similarity computation
export function computeCosineSimilarity(vec1: number[], vec2: number[]): number {
  if (!wasmModule) {
    console.warn('WASM module not initialized');
    return 0;
  }
  
  try {
    const float32Vec1 = new Float32Array(vec1);
    const float32Vec2 = new Float32Array(vec2);
    return wasmModule.compute_cosine_similarity(float32Vec1, float32Vec2);
  } catch (error: any) {
    console.error('Failed to compute cosine similarity:', error);
    return 0;
  }
}

// Batch process multiple documents
export function batchProcessDocuments(documents: string[]): object[] {
  if (!wasmModule) {
    console.warn('WASM module not initialized');
    return [];
  }
  
  try {
    const documentsString = documents.join('\n');
    const result = wasmModule.batch_process_documents(documentsString);
    return JSON.parse(result) as object[];
  } catch (error: any) {
    console.error('Failed to batch process documents:', error);
    return [];
  }
}

// Health check for WASM bridge
export function isRustBridgeAvailable(): boolean {
  return bridge !== null && wasmModule !== null;
}

// Bridge status information
export function getBridgeStatus(): {
  initialized: boolean;
  capabilities: string[];
  performance: boolean;
} {
  return {
    initialized: isRustBridgeAvailable(),
    capabilities: isRustBridgeAvailable() ? [
      'System Information',
      'Secure File Access',
      'GPU Detection',
      'Performance Monitoring',
      'Document Processing',
      'Service Monitoring',
      'Vector Operations',
      'Batch Processing'
    ] : [],
    performance: isRustBridgeAvailable()
  };
}

// Performance benchmarking
export async function benchmarkRustBridge(): Promise<{
  textProcessing: number;
  vectorOperations: number;
  systemAccess: number;
  overallScore: number;
}> {
  if (!isRustBridgeAvailable()) {
    return { textProcessing: 0, vectorOperations: 0, systemAccess: 0, overallScore: 0 };
  }
  
  const startTime = performance.now();
  
  // Benchmark text processing
  const textStart = performance.now();
  const sampleText = "This is a sample legal document for benchmarking performance. ".repeat(100);
  processLegalTextFast(sampleText);
  const textTime = performance.now() - textStart;
  
  // Benchmark vector operations
  const vectorStart = performance.now();
  const sampleVector = new Array(384).fill(0).map(() => Math.random());
  optimizeEmbeddingVector(sampleVector);
  const vectorTime = performance.now() - vectorStart;
  
  // Benchmark system access
  const systemStart = performance.now();
  getSystemInfo();
  const systemTime = performance.now() - systemStart;
  
  const totalTime = performance.now() - startTime;
  
  return {
    textProcessing: textTime,
    vectorOperations: vectorTime,
    systemAccess: systemTime,
    overallScore: 1000 / totalTime // Higher is better
  };
}

// Cleanup function
export function cleanupRustBridge(): void {
  bridge = null;
  wasmModule = null;
  console.log('🧹 Rust WASM bridge cleaned up');
}