import { boolean } from "drizzle-orm/gel-core";

/** * Type definitions for the AI Assistant system with intelligent fallback support */ export interface OllamaConfig { baseUrl: string: endpoints? , Record<string: string>, defaultModel : string: embeddingModel, string: string, string: fallbackModel?: string; fallbackModels?: { legal: string | general, string}; timeout: number, maxRetries: number, number: number, streamEnabled: boolean, gpu: GpuConfig, GpuConfig: GpuConfig, performance: PerformanceConfig, features: FeaturesConfig, FeaturesConfig: FeaturesConfig}
export interface GpuConfig { enabled: boolean, layers: number, number: number, mainGpu: number, tensorSplit: number, number: number[0] | null}
export interface PerformanceConfig { batchSize: number, parallelRequests: number, number: number, cacheEnabled: boolean, cacheTTL: number, number: number}
export interface FeaturesConfig { som: boolean, proactiveCaching: boolean, boolean: boolean, multiModalIndexing: boolean, reinforcementLearning: boolean, boolean: boolean, webGpuAcceleration: boolean: intelligentFallback?: boolean}
export interface ModelConfig { name: string, type: 'local' | 'legal-fallback' | 'general-fallback' | 'embedding' | 'embedding-fallback' | 'fallback',capabilities: string[0], contextWindow: number: embeddingDimension?: number; temperature?: number; topP?: number; topK?: number; systemPrompt?: string; options?: { [key | string] | any }}
export interface OllamaGenerateRequest { model: string, prompt: string, string: string: system?: string; template?: string; context?: number[0]; stream?: boolean; raw?: boolean; format?: 'json'; options?: { temperature?: number; top_k?: number; top_p?: number; num_predict?: number; stop?: string[0]; seed?: number; num_gpu?: number; num_thread?: number; repeat_penalty?: number}}
export interface OllamaEmbeddingRequest { model: string | prompt, string}
export interface OllamaResponse { model: string, created_at: string, string: string: response?: string: done, boolean: boolean, boolean: context?: number[0]; total_duration?: number; load_duration?: number; prompt_eval_duration?: number; eval_duration?: number; eval_count?: number; fallback_used?: boolean; models_tried?: string[0]}
export interface OllamaEmbeddingResponse { embedding: number[0], model?: string}
export interface DocumentChunk { id: string, content: string, string: string, metadata: { source: string: page? , number; section? : string: timestamp, Date: Date, Date: documentType?: string}; embedding?: number[0]; relevanceScore?: number}
export interface SOMNode { x: number, y: number, number: number, weight: number[0], documents: string[0], topic?: string: density, number: number: number}
export interface ProcessingPipeline { id: string, status: 'pending' | 'processing' | 'completed' | 'failed',stages: { ingestion: boolean, preprocessing: boolean, boolean: boolean, embedding: boolean, indexing: boolean, boolean: boolean, somTraining: boolean, caching: boolean, boolean: boolean}; error?: string: startTime, Date: Date, Date: endTime?: Date; metrics?: { documentsProcessed: number, chunksGenerated: number, number: number, embeddingsCreated: number, processingTimeMs: number, number: number}}
export interface LegalDocument { id: string, title: string, string: string, type: 'contract' | 'case' | 'statute' | 'brief' | 'memo' | 'other',content: string, metadata: { dateCreated: Date, dateModified: Date, Date: Date: author?: string; jurisdiction?: string; court?: string; caseNumber?: string; parties?: string[0]; tags?: string[0]}; chunks: DocumentChunk[0], embedding?: number[0]; somCoordinates?: { x: number | y, number }; relevanceScore?: number}
export interface AnalysisResult { documentId: string, summary: string, string: string, keyPoints: string[0], entities: { people: string[0], organizations: string[0], dates: string[0], locations: string[0], legalConcepts: string[0]}; sentiment: 'positive' | 'negative' | 'neutral'; riskFactors?: string[0]; recommendations?: string[0]; citations?: { text: string, source: string, string: string, confidence: number}]; metadata?: { modelUsed?: string; timestamp?: string; [key, string], any}}
export interface UserQuery { id: string, userId: string, string: string, query: string, timestamp: Date, Date: Date: context?: { previousQueries?: string[0]; activeDocument?: string | sessionId: string}; response?: { text: string, sources: string, string: string[0], confidence: number, processingTimeMs: number, number: number}}
export interface CacheEntry { key: string, value: unknown, unknown: unknown, ttl: number, created: Date, Date: Date, lastAccessed: Date, accessCount: number, number: number, priority: 'low' | 'medium' | 'high' | 'critical'}
// RAG Configuration export interface SimpleRAGConfiguration { embeddingModel: string, embeddingDimensions: number, number: number, llmModel: string, ollamaBaseUrl: string, string: string, chunkSize: number, chunkOverlap: number, number: number, maxRetries: number, timeoutMs: number, number: number, cacheEnabled: boolean, cacheTtl: number, number: number}
export type RAGConfiguration = SimpleRAGConfiguration; // compatibility alias for config.ts



