// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/active/retrieval.proto

package retrieval

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvidenceSearchRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Query        string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	CaseId       string                 `protobuf:"bytes,2,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	Limit        int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Jurisdiction string                 `protobuf:"bytes,4,opt,name=jurisdiction,proto3" json:"jurisdiction,omitempty"`
	Hop          *GraphHopPolicy        `protobuf:"bytes,5,opt,name=hop,proto3" json:"hop,omitempty"`
	Prefilter    *PrefilterPolicy       `protobuf:"bytes,6,opt,name=prefilter,proto3" json:"prefilter,omitempty"`
	Rank         *RankPolicy            `protobuf:"bytes,7,opt,name=rank,proto3" json:"rank,omitempty"`
	// Pre-computed query embedding (768-dim embeddinggemma). Skip embed step if set.
	QueryEmbedding []float32 `protobuf:"fixed32,8,rep,packed,name=query_embedding,json=queryEmbedding,proto3" json:"query_embedding,omitempty"`
	IncludeDebug   bool      `protobuf:"varint,9,opt,name=include_debug,json=includeDebug,proto3" json:"include_debug,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EvidenceSearchRequest) Reset() {
	*x = EvidenceSearchRequest{}
	mi := &file_proto_active_retrieval_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceSearchRequest) ProtoMessage() {}

func (x *EvidenceSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_active_retrieval_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceSearchRequest.ProtoReflect.Descriptor instead.
func (*EvidenceSearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_active_retrieval_proto_rawDescGZIP(), []int{0}
}

func (x *EvidenceSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *EvidenceSearchRequest) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *EvidenceSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *EvidenceSearchRequest) GetJurisdiction() string {
	if x != nil {
		return x.Jurisdiction
	}
	return ""
}

func (x *EvidenceSearchRequest) GetHop() *GraphHopPolicy {
	if x != nil {
		return x.Hop
	}
	return nil
}

func (x *EvidenceSearchRequest) GetPrefilter() *PrefilterPolicy {
	if x != nil {
		return x.Prefilter
	}
	return nil
}

func (x *EvidenceSearchRequest) GetRank() *RankPolicy {
	if x != nil {
		return x.Rank
	}
	return nil
}

func (x *EvidenceSearchRequest) GetQueryEmbedding() []float32 {
	if x != nil {
		return x.QueryEmbedding
	}
	return nil
}

func (x *EvidenceSearchRequest) GetIncludeDebug() bool {
	if x != nil {
		return x.IncludeDebug
	}
	return false
}

type EvidenceSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Bundles       []*ContextBundle       `protobuf:"bytes,2,rep,name=bundles,proto3" json:"bundles,omitempty"`
	Timing        *SearchTiming          `protobuf:"bytes,3,opt,name=timing,proto3" json:"timing,omitempty"`
	CacheSource   string                 `protobuf:"bytes,4,opt,name=cache_source,json=cacheSource,proto3" json:"cache_source,omitempty"` // "memory", "redis", or ""
	DebugJson     string                 `protobuf:"bytes,5,opt,name=debug_json,json=debugJson,proto3" json:"debug_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvidenceSearchResponse) Reset() {
	*x = EvidenceSearchResponse{}
	mi := &file_proto_active_retrieval_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceSearchResponse) ProtoMessage() {}

func (x *EvidenceSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_active_retrieval_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceSearchResponse.ProtoReflect.Descriptor instead.
func (*EvidenceSearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_active_retrieval_proto_rawDescGZIP(), []int{1}
}

func (x *EvidenceSearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *EvidenceSearchResponse) GetBundles() []*ContextBundle {
	if x != nil {
		return x.Bundles
	}
	return nil
}

func (x *EvidenceSearchResponse) GetTiming() *SearchTiming {
	if x != nil {
		return x.Timing
	}
	return nil
}

func (x *EvidenceSearchResponse) GetCacheSource() string {
	if x != nil {
		return x.CacheSource
	}
	return ""
}

func (x *EvidenceSearchResponse) GetDebugJson() string {
	if x != nil {
		return x.DebugJson
	}
	return ""
}

type EvidenceBundleEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*EvidenceBundleEvent_Bundle
	//	*EvidenceBundleEvent_Progress
	//	*EvidenceBundleEvent_Error
	Event         isEvidenceBundleEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvidenceBundleEvent) Reset() {
	*x = EvidenceBundleEvent{}
	mi := &file_proto_active_retrieval_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceBundleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceBundleEvent) ProtoMessage() {}

func (x *EvidenceBundleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_active_retrieval_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceBundleEvent.ProtoReflect.Descriptor instead.
func (*EvidenceBundleEvent) Descriptor() ([]byte, []int) {
	return file_proto_active_retrieval_proto_rawDescGZIP(), []int{2}
}

func (x *EvidenceBundleEvent) GetEvent() isEvidenceBundleEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EvidenceBundleEvent) GetBundle() *ContextBundle {
	if x != nil {
		if x, ok := x.Event.(*EvidenceBundleEvent_Bundle); ok {
			return x.Bundle
		}
	}
	return nil
}

func (x *EvidenceBundleEvent) GetProgress() *RetrievalProgress {
	if x != nil {
		if x, ok := x.Event.(*EvidenceBundleEvent_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *EvidenceBundleEvent) GetError() *RetrievalError {
	if x != nil {
		if x, ok := x.Event.(*EvidenceBundleEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isEvidenceBundleEvent_Event interface {
	isEvidenceBundleEvent_Event()
}

type EvidenceBundleEvent_Bundle struct {
	Bundle *ContextBundle `protobuf:"bytes,1,opt,name=bundle,proto3,oneof"`
}

type EvidenceBundleEvent_Progress struct {
	Progress *RetrievalProgress `protobuf:"bytes,2,opt,name=progress,proto3,oneof"`
}

type EvidenceBundleEvent_Error struct {
	Error *RetrievalError `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*EvidenceBundleEvent_Bundle) isEvidenceBundleEvent_Event() {}

func (*EvidenceBundleEvent_Progress) isEvidenceBundleEvent_Event() {}

func (*EvidenceBundleEvent_Error) isEvidenceBundleEvent_Event() {}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EvidenceId    string                 `protobuf:"bytes,1,opt,name=evidence_id,json=evidenceId,proto3" json:"evidence_id,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Score         float32                `protobuf:"fixed32,4,opt,name=score,proto3" json:"score,omitempty"`
	Metadata      *ChunkMetadata         `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Rerank        *RerankExplain         `protobuf:"bytes,6,opt,name=rerank,proto3" json:"rerank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_proto_active_retrieval_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_active_retrieval_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_proto_active_retrieval_proto_rawDescGZIP(), []int{3}
}

func (x *SearchResult) GetEvidenceId() string {
	if x != nil {
		return x.EvidenceId
	}
	return ""
}

func (x *SearchResult) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *SearchResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetMetadata() *ChunkMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SearchResult) GetRerank() *RerankExplain {
	if x != nil {
		return x.Rerank
	}
	return nil
}

type ChunkMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SectionPath      []string               `protobuf:"bytes,1,rep,name=section_path,json=sectionPath,proto3" json:"section_path,omitempty"` // ["ARTICLE I", "SECTION 2", "§ 8"]
	Heading          string                 `protobuf:"bytes,2,opt,name=heading,proto3" json:"heading,omitempty"`
	Citations        []string               `protobuf:"bytes,3,rep,name=citations,proto3" json:"citations,omitempty"`
	FileName         string                 `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	TokenCount       int32                  `protobuf:"varint,5,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	ExtractionMethod string                 `protobuf:"bytes,6,opt,name=extraction_method,json=extractionMethod,proto3" json:"extraction_method,omitempty"` // "pdf-parse", "ocr-tesseract", "utf8"
	Jurisdiction     string                 `protobuf:"bytes,7,opt,name=jurisdiction,proto3" json:"jurisdiction,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChunkMetadata) Reset() {
	*x = ChunkMetadata{}
	mi := &file_proto_active_retrieval_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkMetadata) ProtoMessage() {}

func (x *ChunkMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_active_retrieval_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkMetadata.ProtoReflect.Descriptor instead.
func (*ChunkMetadata) Descriptor() ([]byte, []int) {
	return file_proto_active_retrieval_proto_rawDescGZIP(), []int{4}
}

func (x *ChunkMetadata) GetSectionPath() []string {
	if x != nil {
		return x.SectionPath
	}
	return nil
}

func (x *ChunkMetadata) GetHeading() string {
	if x != nil {
		return x.Heading
	}
	return ""
}

func (x *ChunkMetadata) GetCitations() []string {
	if x != nil {
		return x.Citations
	}
	return nil
}

func (x *ChunkMetadata) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ChunkMetadata) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *ChunkMetadata) GetExtractionMethod() string {
	if x != nil {
		return x.ExtractionMethod
	}
	return ""
}

func (x *ChunkMetadata) GetJurisdiction() string {
	if x != nil {
		return x.Jurisdiction
	}
	return ""
}

type RerankExplain struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Cosine            float32                `protobuf:"fixed32,1,opt,name=cosine,proto3" json:"cosine,omitempty"`                                                // Raw cosine similarity
	SharedCitations   float32                `protobuf:"fixed32,2,opt,name=shared_citations,json=sharedCitations,proto3" json:"shared_citations,omitempty"`       // Citation overlap count (capped at 3)
	JurisdictionMatch float32                `protobuf:"fixed32,3,opt,name=jurisdiction_match,json=jurisdictionMatch,proto3" json:"jurisdiction_match,omitempty"` // 1.0 = exact, 0.5 = text mention, 0.0 = absent
	SectionProximity  float32                `protobuf:"fixed32,4,opt,name=section_proximity,json=sectionProximity,proto3" json:"section_proximity,omitempty"`    // 0..1 based on section depth
	FinalScore        float32                `protobuf:"fixed32,5,opt,name=final_score,json=finalScore,proto3" json:"final_score,omitempty"`                      // 0.75*cosine + 0.15*citations + 0.10*context
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RerankExplain) Reset() {
	*x = RerankExplain{}
	mi := &file_proto_active_retrieval_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerankExplain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerankExplain) ProtoMessage() {}

func (x *RerankExplain) ProtoReflect() protoreflect.Message {
	mi := &file_proto_active_retrieval_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerankExplain.ProtoReflect.Descriptor instead.
func (*RerankExplain) Descriptor() ([]byte, []int) {
	return file_proto_active_retrieval_proto_rawDescGZIP(), []int{5}
}

func (x *RerankExplain) GetCosine() float32 {
	if x != nil {
		return x.Cosine
	}
	return 0
}

func (x *RerankExplain) GetSharedCitations() float32 {
	if x != nil {
		return x.SharedCitations
	}
	return 0
}

func (x *RerankExplain) GetJurisdictionMatch() float32 {
	if x != nil {
		return x.JurisdictionMatch
	}
	return 0
}

func (x *RerankExplain) GetSectionProximity() float32 {
	if x != nil {
		return x.SectionProximity
	}
	return 0
}

func (x *RerankExplain) GetFinalScore() float32 {
	if x != nil {
		return x.FinalScore
	}
	return 0
}

type ContextBundle struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Hit         *SearchResult          `protobuf:"bytes,1,opt,name=hit,proto3" json:"hit,omitempty"`           // Primary hit (anchor)
	Siblings    []*SearchResult        `protobuf:"bytes,2,rep,name=siblings,proto3" json:"siblings,omitempty"` // Sibling chunks from same section
	SectionPath []string               `protobuf:"bytes,3,rep,name=section_path,json=sectionPath,proto3" json:"section_path,omitempty"`
	Heading     string                 `protobuf:"bytes,4,opt,name=heading,proto3" json:"heading,omitempty"`
	Citations   []string               `protobuf:"bytes,5,rep,name=citations,proto3" json:"citations,omitempty"` // All citations in bundle
	// KAG: 1-hop graph neighbors from yorha_evidence_connections
	GraphNeighbors []*GraphNeighbor `protobuf:"bytes,6,rep,name=graph_neighbors,json=graphNeighbors,proto3" json:"graph_neighbors,omitempty"`
	// DAG: parent document context from evidence + yorha_evidence_nodes
	DocumentContext *DocumentContext `protobuf:"bytes,7,opt,name=document_context,json=documentContext,proto3" json:"document_context,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContextBundle) Reset() {
	*x = ContextBundle{}
	mi := &file_proto_active_retrieval_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextBundle) ProtoMessage() {}

func (x *ContextBundle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_active_retrieval_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextBundle.ProtoReflect.Descriptor instead.
func (*ContextBundle) Descriptor() ([]byte, []int) {
	return file_proto_active_retrieval_proto_rawDescGZIP(), []int{6}
}

func (x *ContextBundle) GetHit() *SearchResult {
	if x != nil {
		return x.Hit
	}
	return nil
}

func (x *ContextBundle) GetSiblings() []*SearchResult {
	if x != nil {
		return x.Siblings
	}
	return nil
}

func (x *ContextBundle) GetSectionPath() []string {
	if x != nil {
		return x.SectionPath
	}
	return nil
}

func (x *ContextBundle) GetHeading() string {
	if x != nil {
		return x.Heading
	}
	return ""
}

func (x *ContextBundle) GetCitations() []string {
	if x != nil {
		return x.Citations
	}
	return nil
}

func (x *ContextBundle) GetGraphNeighbors() []*GraphNeighbor {
	if x != nil {
		return x.GraphNeighbors
	}
	return nil
}

func (x *ContextBundle) GetDocumentContext() *DocumentContext {
	if x != nil {
		return x.DocumentContext
	}
	return nil
}

type GraphNeighbor struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // yorha_evidence_nodes.id
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	EvidenceType   string                 `protobuf:"bytes,3,opt,name=evidence_type,json=evidenceType,proto3" json:"evidence_type,omitempty"`       // "document-section", etc.
	ConnectionType string                 `protobuf:"bytes,4,opt,name=connection_type,json=connectionType,proto3" json:"connection_type,omitempty"` // "HAS_SECTION", "cites", "contradicts", "explains"
	Strength       int32                  `protobuf:"varint,5,opt,name=strength,proto3" json:"strength,omitempty"`                                  // 0-100
	Confidence     int32                  `protobuf:"varint,6,opt,name=confidence,proto3" json:"confidence,omitempty"`                              // 0-100
	AiReasoning    string                 `protobuf:"bytes,7,opt,name=ai_reasoning,json=aiReasoning,proto3" json:"ai_reasoning,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GraphNeighbor) Reset() {
	*x = GraphNeighbor{}
	mi := &file_proto_active_retrieval_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphNeighbor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphNeighbor) ProtoMessage() {}

func (x *GraphNeighbor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_active_retrieval_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphNeighbor.ProtoReflect.Descriptor instead.
func (*GraphNeighbor) Descriptor() ([]byte, []int) {
	return file_proto_active_retrieval_proto_rawDescGZIP(), []int{7}
}

func (x *GraphNeighbor) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GraphNeighbor) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GraphNeighbor) GetEvidenceType() string {
	if x != nil {
		return x.EvidenceType
	}
	return ""
}

func (x *GraphNeighbor) GetConnectionType() string {
	if x != nil {
		return x.ConnectionType
	}
	return ""
}

func (x *GraphNeighbor) GetStrength() int32 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *GraphNeighbor) GetConfidence() int32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *GraphNeighbor) GetAiReasoning() string {
	if x != nil {
		return x.AiReasoning
	}
	return ""
}

type DocumentContext struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EvidenceId      string                 `protobuf:"bytes,1,opt,name=evidence_id,json=evidenceId,proto3" json:"evidence_id,omitempty"`
	FileName        string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileType        string                 `protobuf:"bytes,3,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	AiSummary       string                 `protobuf:"bytes,5,opt,name=ai_summary,json=aiSummary,proto3" json:"ai_summary,omitempty"`                     // From yorha_evidence_nodes
	AiTagsJson      string                 `protobuf:"bytes,6,opt,name=ai_tags_json,json=aiTagsJson,proto3" json:"ai_tags_json,omitempty"`                // JSONB passthrough
	KeyEntitiesJson string                 `protobuf:"bytes,7,opt,name=key_entities_json,json=keyEntitiesJson,proto3" json:"key_entities_json,omitempty"` // JSONB passthrough
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DocumentContext) Reset() {
	*x = DocumentContext{}
	mi := &file_proto_active_retrieval_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentContext) ProtoMessage() {}

func (x *DocumentContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_active_retrieval_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentContext.ProtoReflect.Descriptor instead.
func (*DocumentContext) Descriptor() ([]byte, []int) {
	return file_proto_active_retrieval_proto_rawDescGZIP(), []int{8}
}

func (x *DocumentContext) GetEvidenceId() string {
	if x != nil {
		return x.EvidenceId
	}
	return ""
}

func (x *DocumentContext) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *DocumentContext) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *DocumentContext) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DocumentContext) GetAiSummary() string {
	if x != nil {
		return x.AiSummary
	}
	return ""
}

func (x *DocumentContext) GetAiTagsJson() string {
	if x != nil {
		return x.AiTagsJson
	}
	return ""
}

func (x *DocumentContext) GetKeyEntitiesJson() string {
	if x != nil {
		return x.KeyEntitiesJson
	}
	return ""
}

type SearchTiming struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmbedMs       float32                `protobuf:"fixed32,1,opt,name=embed_ms,json=embedMs,proto3" json:"embed_ms,omitempty"`
	SearchMs      float32                `protobuf:"fixed32,2,opt,name=search_ms,json=searchMs,proto3" json:"search_ms,omitempty"` // Dual: pgvector + Qdrant
	RerankMs      float32                `protobuf:"fixed32,3,opt,name=rerank_ms,json=rerankMs,proto3" json:"rerank_ms,omitempty"`
	HopMs         float32                `protobuf:"fixed32,4,opt,name=hop_ms,json=hopMs,proto3" json:"hop_ms,omitempty"` // Section sibling expansion
	KagMs         float32                `protobuf:"fixed32,5,opt,name=kag_ms,json=kagMs,proto3" json:"kag_ms,omitempty"` // Graph neighbor traversal
	DagMs         float32                `protobuf:"fixed32,6,opt,name=dag_ms,json=dagMs,proto3" json:"dag_ms,omitempty"` // Document context enrichment
	TotalMs       float32                `protobuf:"fixed32,7,opt,name=total_ms,json=totalMs,proto3" json:"total_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTiming) Reset() {
	*x = SearchTiming{}
	mi := &file_proto_active_retrieval_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTiming) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTiming) ProtoMessage() {}

func (x *SearchTiming) ProtoReflect() protoreflect.Message {
	mi := &file_proto_active_retrieval_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTiming.ProtoReflect.Descriptor instead.
func (*SearchTiming) Descriptor() ([]byte, []int) {
	return file_proto_active_retrieval_proto_rawDescGZIP(), []int{9}
}

func (x *SearchTiming) GetEmbedMs() float32 {
	if x != nil {
		return x.EmbedMs
	}
	return 0
}

func (x *SearchTiming) GetSearchMs() float32 {
	if x != nil {
		return x.SearchMs
	}
	return 0
}

func (x *SearchTiming) GetRerankMs() float32 {
	if x != nil {
		return x.RerankMs
	}
	return 0
}

func (x *SearchTiming) GetHopMs() float32 {
	if x != nil {
		return x.HopMs
	}
	return 0
}

func (x *SearchTiming) GetKagMs() float32 {
	if x != nil {
		return x.KagMs
	}
	return 0
}

func (x *SearchTiming) GetDagMs() float32 {
	if x != nil {
		return x.DagMs
	}
	return 0
}

func (x *SearchTiming) GetTotalMs() float32 {
	if x != nil {
		return x.TotalMs
	}
	return 0
}

type CodebaseSearchRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Query           string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit           int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	ContentWeight   float32                `protobuf:"fixed32,3,opt,name=content_weight,json=contentWeight,proto3" json:"content_weight,omitempty"`       // Default 0.6
	SignatureWeight float32                `protobuf:"fixed32,4,opt,name=signature_weight,json=signatureWeight,proto3" json:"signature_weight,omitempty"` // Default 0.4
	Kinds           []string               `protobuf:"bytes,5,rep,name=kinds,proto3" json:"kinds,omitempty"`                                              // "route", "component", "server", "lib"
	HttpMethod      string                 `protobuf:"bytes,6,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`
	PathPrefixes    []string               `protobuf:"bytes,7,rep,name=path_prefixes,json=pathPrefixes,proto3" json:"path_prefixes,omitempty"` // ["src/routes/api", "src/lib/server"]
	IncludeDebug    bool                   `protobuf:"varint,8,opt,name=include_debug,json=includeDebug,proto3" json:"include_debug,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CodebaseSearchRequest) Reset() {
	*x = CodebaseSearchRequest{}
	mi := &file_proto_active_retrieval_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodebaseSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodebaseSearchRequest) ProtoMessage() {}

func (x *CodebaseSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_active_retrieval_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodebaseSearchRequest.ProtoReflect.Descriptor instead.
func (*CodebaseSearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_active_retrieval_proto_rawDescGZIP(), []int{10}
}

func (x *CodebaseSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *CodebaseSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CodebaseSearchRequest) GetContentWeight() float32 {
	if x != nil {
		return x.ContentWeight
	}
	return 0
}

func (x *CodebaseSearchRequest) GetSignatureWeight() float32 {
	if x != nil {
		return x.SignatureWeight
	}
	return 0
}

func (x *CodebaseSearchRequest) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *CodebaseSearchRequest) GetHttpMethod() string {
	if x != nil {
		return x.HttpMethod
	}
	return ""
}

func (x *CodebaseSearchRequest) GetPathPrefixes() []string {
	if x != nil {
		return x.PathPrefixes
	}
	return nil
}

func (x *CodebaseSearchRequest) GetIncludeDebug() bool {
	if x != nil {
		return x.IncludeDebug
	}
	return false
}

type CodebaseSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*CodebaseChunk       `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	TotalMs       float32                `protobuf:"fixed32,2,opt,name=total_ms,json=totalMs,proto3" json:"total_ms,omitempty"`
	DebugJson     string                 `protobuf:"bytes,3,opt,name=debug_json,json=debugJson,proto3" json:"debug_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodebaseSearchResponse) Reset() {
	*x = CodebaseSearchResponse{}
	mi := &file_proto_active_retrieval_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodebaseSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodebaseSearchResponse) ProtoMessage() {}

func (x *CodebaseSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_active_retrieval_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodebaseSearchResponse.ProtoReflect.Descriptor instead.
func (*CodebaseSearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_active_retrieval_proto_rawDescGZIP(), []int{11}
}

func (x *CodebaseSearchResponse) GetChunks() []*CodebaseChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *CodebaseSearchResponse) GetTotalMs() float32 {
	if x != nil {
		return x.TotalMs
	}
	return 0
}

func (x *CodebaseSearchResponse) GetDebugJson() string {
	if x != nil {
		return x.DebugJson
	}
	return ""
}

type CodebaseChunkEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*CodebaseChunkEvent_Chunk
	//	*CodebaseChunkEvent_Progress
	//	*CodebaseChunkEvent_Error
	Event         isCodebaseChunkEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodebaseChunkEvent) Reset() {
	*x = CodebaseChunkEvent{}
	mi := &file_proto_active_retrieval_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodebaseChunkEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodebaseChunkEvent) ProtoMessage() {}

func (x *CodebaseChunkEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_active_retrieval_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodebaseChunkEvent.ProtoReflect.Descriptor instead.
func (*CodebaseChunkEvent) Descriptor() ([]byte, []int) {
	return file_proto_active_retrieval_proto_rawDescGZIP(), []int{12}
}

func (x *CodebaseChunkEvent) GetEvent() isCodebaseChunkEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *CodebaseChunkEvent) GetChunk() *CodebaseChunk {
	if x != nil {
		if x, ok := x.Event.(*CodebaseChunkEvent_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *CodebaseChunkEvent) GetProgress() *RetrievalProgress {
	if x != nil {
		if x, ok := x.Event.(*CodebaseChunkEvent_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *CodebaseChunkEvent) GetError() *RetrievalError {
	if x != nil {
		if x, ok := x.Event.(*CodebaseChunkEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCodebaseChunkEvent_Event interface {
	isCodebaseChunkEvent_Event()
}

type CodebaseChunkEvent_Chunk struct {
	Chunk *CodebaseChunk `protobuf:"bytes,1,opt,name=chunk,proto3,oneof"`
}

type CodebaseChunkEvent_Progress struct {
	Progress *RetrievalProgress `protobuf:"bytes,2,opt,name=progress,proto3,oneof"`
}

type CodebaseChunkEvent_Error struct {
	Error *RetrievalError `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*CodebaseChunkEvent_Chunk) isCodebaseChunkEvent_Event() {}

func (*CodebaseChunkEvent_Progress) isCodebaseChunkEvent_Event() {}

func (*CodebaseChunkEvent_Error) isCodebaseChunkEvent_Event() {}

type CodebaseChunk struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChunkId        string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	FilePath       string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Kind           string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	HttpMethod     string                 `protobuf:"bytes,4,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`
	RouteId        string                 `protobuf:"bytes,5,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Tags           []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	ContentPreview string                 `protobuf:"bytes,7,opt,name=content_preview,json=contentPreview,proto3" json:"content_preview,omitempty"`
	Score          float32                `protobuf:"fixed32,8,opt,name=score,proto3" json:"score,omitempty"`
	StartLine      int32                  `protobuf:"varint,9,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	EndLine        int32                  `protobuf:"varint,10,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CodebaseChunk) Reset() {
	*x = CodebaseChunk{}
	mi := &file_proto_active_retrieval_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodebaseChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodebaseChunk) ProtoMessage() {}

func (x *CodebaseChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_active_retrieval_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodebaseChunk.ProtoReflect.Descriptor instead.
func (*CodebaseChunk) Descriptor() ([]byte, []int) {
	return file_proto_active_retrieval_proto_rawDescGZIP(), []int{13}
}

func (x *CodebaseChunk) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *CodebaseChunk) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *CodebaseChunk) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CodebaseChunk) GetHttpMethod() string {
	if x != nil {
		return x.HttpMethod
	}
	return ""
}

func (x *CodebaseChunk) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *CodebaseChunk) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CodebaseChunk) GetContentPreview() string {
	if x != nil {
		return x.ContentPreview
	}
	return ""
}

func (x *CodebaseChunk) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *CodebaseChunk) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *CodebaseChunk) GetEndLine() int32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

type GraphHopPolicy struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Mode                   int32                  `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`                                       // 0=off, 1=siblings, 2=siblings+parent/child
	MaxHopChunks           int32                  `protobuf:"varint,2,opt,name=max_hop_chunks,json=maxHopChunks,proto3" json:"max_hop_chunks,omitempty"` // Default 10
	WithinSameEvidenceOnly bool                   `protobuf:"varint,3,opt,name=within_same_evidence_only,json=withinSameEvidenceOnly,proto3" json:"within_same_evidence_only,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GraphHopPolicy) Reset() {
	*x = GraphHopPolicy{}
	mi := &file_proto_active_retrieval_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphHopPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphHopPolicy) ProtoMessage() {}

func (x *GraphHopPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_active_retrieval_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphHopPolicy.ProtoReflect.Descriptor instead.
func (*GraphHopPolicy) Descriptor() ([]byte, []int) {
	return file_proto_active_retrieval_proto_rawDescGZIP(), []int{14}
}

func (x *GraphHopPolicy) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *GraphHopPolicy) GetMaxHopChunks() int32 {
	if x != nil {
		return x.MaxHopChunks
	}
	return 0
}

func (x *GraphHopPolicy) GetWithinSameEvidenceOnly() bool {
	if x != nil {
		return x.WithinSameEvidenceOnly
	}
	return false
}

type PrefilterPolicy struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	EnableQdrant          bool                   `protobuf:"varint,1,opt,name=enable_qdrant,json=enableQdrant,proto3" json:"enable_qdrant,omitempty"`                              // Default true
	QdrantShortlist       int32                  `protobuf:"varint,2,opt,name=qdrant_shortlist,json=qdrantShortlist,proto3" json:"qdrant_shortlist,omitempty"`                     // Default 3x limit
	ScoreThreshold        float32                `protobuf:"fixed32,3,opt,name=score_threshold,json=scoreThreshold,proto3" json:"score_threshold,omitempty"`                       // Default 0.3
	AllowPgvectorFallback bool                   `protobuf:"varint,4,opt,name=allow_pgvector_fallback,json=allowPgvectorFallback,proto3" json:"allow_pgvector_fallback,omitempty"` // Default true
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PrefilterPolicy) Reset() {
	*x = PrefilterPolicy{}
	mi := &file_proto_active_retrieval_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefilterPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefilterPolicy) ProtoMessage() {}

func (x *PrefilterPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_active_retrieval_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefilterPolicy.ProtoReflect.Descriptor instead.
func (*PrefilterPolicy) Descriptor() ([]byte, []int) {
	return file_proto_active_retrieval_proto_rawDescGZIP(), []int{15}
}

func (x *PrefilterPolicy) GetEnableQdrant() bool {
	if x != nil {
		return x.EnableQdrant
	}
	return false
}

func (x *PrefilterPolicy) GetQdrantShortlist() int32 {
	if x != nil {
		return x.QdrantShortlist
	}
	return 0
}

func (x *PrefilterPolicy) GetScoreThreshold() float32 {
	if x != nil {
		return x.ScoreThreshold
	}
	return 0
}

func (x *PrefilterPolicy) GetAllowPgvectorFallback() bool {
	if x != nil {
		return x.AllowPgvectorFallback
	}
	return false
}

type RankPolicy struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CosineWeight       float32                `protobuf:"fixed32,1,opt,name=cosine_weight,json=cosineWeight,proto3" json:"cosine_weight,omitempty"`                   // Default 0.75
	CitationsWeight    float32                `protobuf:"fixed32,2,opt,name=citations_weight,json=citationsWeight,proto3" json:"citations_weight,omitempty"`          // Default 0.15
	JurisdictionWeight float32                `protobuf:"fixed32,3,opt,name=jurisdiction_weight,json=jurisdictionWeight,proto3" json:"jurisdiction_weight,omitempty"` // Default 0.10
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RankPolicy) Reset() {
	*x = RankPolicy{}
	mi := &file_proto_active_retrieval_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankPolicy) ProtoMessage() {}

func (x *RankPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_active_retrieval_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankPolicy.ProtoReflect.Descriptor instead.
func (*RankPolicy) Descriptor() ([]byte, []int) {
	return file_proto_active_retrieval_proto_rawDescGZIP(), []int{16}
}

func (x *RankPolicy) GetCosineWeight() float32 {
	if x != nil {
		return x.CosineWeight
	}
	return 0
}

func (x *RankPolicy) GetCitationsWeight() float32 {
	if x != nil {
		return x.CitationsWeight
	}
	return 0
}

func (x *RankPolicy) GetJurisdictionWeight() float32 {
	if x != nil {
		return x.JurisdictionWeight
	}
	return 0
}

type RetrievalProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"` // "embed", "search", "rerank", "hop", "kag", "dag"
	Current       int32                  `protobuf:"varint,2,opt,name=current,proto3" json:"current,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrievalProgress) Reset() {
	*x = RetrievalProgress{}
	mi := &file_proto_active_retrieval_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievalProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievalProgress) ProtoMessage() {}

func (x *RetrievalProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_active_retrieval_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievalProgress.ProtoReflect.Descriptor instead.
func (*RetrievalProgress) Descriptor() ([]byte, []int) {
	return file_proto_active_retrieval_proto_rawDescGZIP(), []int{17}
}

func (x *RetrievalProgress) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *RetrievalProgress) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *RetrievalProgress) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *RetrievalProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RetrievalError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // "UNAVAILABLE", "TIMEOUT", "INVALID_ARGUMENT"
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DetailsJson   string                 `protobuf:"bytes,3,opt,name=details_json,json=detailsJson,proto3" json:"details_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrievalError) Reset() {
	*x = RetrievalError{}
	mi := &file_proto_active_retrieval_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievalError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievalError) ProtoMessage() {}

func (x *RetrievalError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_active_retrieval_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievalError.ProtoReflect.Descriptor instead.
func (*RetrievalError) Descriptor() ([]byte, []int) {
	return file_proto_active_retrieval_proto_rawDescGZIP(), []int{18}
}

func (x *RetrievalError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RetrievalError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RetrievalError) GetDetailsJson() string {
	if x != nil {
		return x.DetailsJson
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_active_retrieval_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_active_retrieval_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_active_retrieval_proto_rawDescGZIP(), []int{19}
}

func (x *HealthRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Status             string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PgvectorConnected  bool                   `protobuf:"varint,2,opt,name=pgvector_connected,json=pgvectorConnected,proto3" json:"pgvector_connected,omitempty"`
	QdrantConnected    bool                   `protobuf:"varint,3,opt,name=qdrant_connected,json=qdrantConnected,proto3" json:"qdrant_connected,omitempty"`
	RedisConnected     bool                   `protobuf:"varint,4,opt,name=redis_connected,json=redisConnected,proto3" json:"redis_connected,omitempty"`
	EmbeddingServiceUp bool                   `protobuf:"varint,5,opt,name=embedding_service_up,json=embeddingServiceUp,proto3" json:"embedding_service_up,omitempty"`
	Timestamp          int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_active_retrieval_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_active_retrieval_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_active_retrieval_proto_rawDescGZIP(), []int{20}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetPgvectorConnected() bool {
	if x != nil {
		return x.PgvectorConnected
	}
	return false
}

func (x *HealthResponse) GetQdrantConnected() bool {
	if x != nil {
		return x.QdrantConnected
	}
	return false
}

func (x *HealthResponse) GetRedisConnected() bool {
	if x != nil {
		return x.RedisConnected
	}
	return false
}

func (x *HealthResponse) GetEmbeddingServiceUp() bool {
	if x != nil {
		return x.EmbeddingServiceUp
	}
	return false
}

func (x *HealthResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_active_retrieval_proto protoreflect.FileDescriptor

const file_proto_active_retrieval_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/active/retrieval.proto\x12\x0fyorha.retrieval\"\xf6\x02\n" +
	"\x15EvidenceSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x17\n" +
	"\acase_id\x18\x02 \x01(\tR\x06caseId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\"\n" +
	"\fjurisdiction\x18\x04 \x01(\tR\fjurisdiction\x121\n" +
	"\x03hop\x18\x05 \x01(\v2\x1f.yorha.retrieval.GraphHopPolicyR\x03hop\x12>\n" +
	"\tprefilter\x18\x06 \x01(\v2 .yorha.retrieval.PrefilterPolicyR\tprefilter\x12/\n" +
	"\x04rank\x18\a \x01(\v2\x1b.yorha.retrieval.RankPolicyR\x04rank\x12+\n" +
	"\x0fquery_embedding\x18\b \x03(\x02B\x02\x10\x01R\x0equeryEmbedding\x12#\n" +
	"\rinclude_debug\x18\t \x01(\bR\fincludeDebug\"\x84\x02\n" +
	"\x16EvidenceSearchResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.yorha.retrieval.SearchResultR\aresults\x128\n" +
	"\abundles\x18\x02 \x03(\v2\x1e.yorha.retrieval.ContextBundleR\abundles\x125\n" +
	"\x06timing\x18\x03 \x01(\v2\x1d.yorha.retrieval.SearchTimingR\x06timing\x12!\n" +
	"\fcache_source\x18\x04 \x01(\tR\vcacheSource\x12\x1d\n" +
	"\n" +
	"debug_json\x18\x05 \x01(\tR\tdebugJson\"\xd3\x01\n" +
	"\x13EvidenceBundleEvent\x128\n" +
	"\x06bundle\x18\x01 \x01(\v2\x1e.yorha.retrieval.ContextBundleH\x00R\x06bundle\x12@\n" +
	"\bprogress\x18\x02 \x01(\v2\".yorha.retrieval.RetrievalProgressH\x00R\bprogress\x127\n" +
	"\x05error\x18\x03 \x01(\v2\x1f.yorha.retrieval.RetrievalErrorH\x00R\x05errorB\a\n" +
	"\x05event\"\xf4\x01\n" +
	"\fSearchResult\x12\x1f\n" +
	"\vevidence_id\x18\x01 \x01(\tR\n" +
	"evidenceId\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x02R\x05score\x12:\n" +
	"\bmetadata\x18\x05 \x01(\v2\x1e.yorha.retrieval.ChunkMetadataR\bmetadata\x126\n" +
	"\x06rerank\x18\x06 \x01(\v2\x1e.yorha.retrieval.RerankExplainR\x06rerank\"\xf9\x01\n" +
	"\rChunkMetadata\x12!\n" +
	"\fsection_path\x18\x01 \x03(\tR\vsectionPath\x12\x18\n" +
	"\aheading\x18\x02 \x01(\tR\aheading\x12\x1c\n" +
	"\tcitations\x18\x03 \x03(\tR\tcitations\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\x12\x1f\n" +
	"\vtoken_count\x18\x05 \x01(\x05R\n" +
	"tokenCount\x12+\n" +
	"\x11extraction_method\x18\x06 \x01(\tR\x10extractionMethod\x12\"\n" +
	"\fjurisdiction\x18\a \x01(\tR\fjurisdiction\"\xcf\x01\n" +
	"\rRerankExplain\x12\x16\n" +
	"\x06cosine\x18\x01 \x01(\x02R\x06cosine\x12)\n" +
	"\x10shared_citations\x18\x02 \x01(\x02R\x0fsharedCitations\x12-\n" +
	"\x12jurisdiction_match\x18\x03 \x01(\x02R\x11jurisdictionMatch\x12+\n" +
	"\x11section_proximity\x18\x04 \x01(\x02R\x10sectionProximity\x12\x1f\n" +
	"\vfinal_score\x18\x05 \x01(\x02R\n" +
	"finalScore\"\xec\x02\n" +
	"\rContextBundle\x12/\n" +
	"\x03hit\x18\x01 \x01(\v2\x1d.yorha.retrieval.SearchResultR\x03hit\x129\n" +
	"\bsiblings\x18\x02 \x03(\v2\x1d.yorha.retrieval.SearchResultR\bsiblings\x12!\n" +
	"\fsection_path\x18\x03 \x03(\tR\vsectionPath\x12\x18\n" +
	"\aheading\x18\x04 \x01(\tR\aheading\x12\x1c\n" +
	"\tcitations\x18\x05 \x03(\tR\tcitations\x12G\n" +
	"\x0fgraph_neighbors\x18\x06 \x03(\v2\x1e.yorha.retrieval.GraphNeighborR\x0egraphNeighbors\x12K\n" +
	"\x10document_context\x18\a \x01(\v2 .yorha.retrieval.DocumentContextR\x0fdocumentContext\"\xeb\x01\n" +
	"\rGraphNeighbor\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12#\n" +
	"\revidence_type\x18\x03 \x01(\tR\fevidenceType\x12'\n" +
	"\x0fconnection_type\x18\x04 \x01(\tR\x0econnectionType\x12\x1a\n" +
	"\bstrength\x18\x05 \x01(\x05R\bstrength\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x05R\n" +
	"confidence\x12!\n" +
	"\fai_reasoning\x18\a \x01(\tR\vaiReasoning\"\xfb\x01\n" +
	"\x0fDocumentContext\x12\x1f\n" +
	"\vevidence_id\x18\x01 \x01(\tR\n" +
	"evidenceId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_type\x18\x03 \x01(\tR\bfileType\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"ai_summary\x18\x05 \x01(\tR\taiSummary\x12 \n" +
	"\fai_tags_json\x18\x06 \x01(\tR\n" +
	"aiTagsJson\x12*\n" +
	"\x11key_entities_json\x18\a \x01(\tR\x0fkeyEntitiesJson\"\xc3\x01\n" +
	"\fSearchTiming\x12\x19\n" +
	"\bembed_ms\x18\x01 \x01(\x02R\aembedMs\x12\x1b\n" +
	"\tsearch_ms\x18\x02 \x01(\x02R\bsearchMs\x12\x1b\n" +
	"\trerank_ms\x18\x03 \x01(\x02R\brerankMs\x12\x15\n" +
	"\x06hop_ms\x18\x04 \x01(\x02R\x05hopMs\x12\x15\n" +
	"\x06kag_ms\x18\x05 \x01(\x02R\x05kagMs\x12\x15\n" +
	"\x06dag_ms\x18\x06 \x01(\x02R\x05dagMs\x12\x19\n" +
	"\btotal_ms\x18\a \x01(\x02R\atotalMs\"\x96\x02\n" +
	"\x15CodebaseSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12%\n" +
	"\x0econtent_weight\x18\x03 \x01(\x02R\rcontentWeight\x12)\n" +
	"\x10signature_weight\x18\x04 \x01(\x02R\x0fsignatureWeight\x12\x14\n" +
	"\x05kinds\x18\x05 \x03(\tR\x05kinds\x12\x1f\n" +
	"\vhttp_method\x18\x06 \x01(\tR\n" +
	"httpMethod\x12#\n" +
	"\rpath_prefixes\x18\a \x03(\tR\fpathPrefixes\x12#\n" +
	"\rinclude_debug\x18\b \x01(\bR\fincludeDebug\"\x8a\x01\n" +
	"\x16CodebaseSearchResponse\x126\n" +
	"\x06chunks\x18\x01 \x03(\v2\x1e.yorha.retrieval.CodebaseChunkR\x06chunks\x12\x19\n" +
	"\btotal_ms\x18\x02 \x01(\x02R\atotalMs\x12\x1d\n" +
	"\n" +
	"debug_json\x18\x03 \x01(\tR\tdebugJson\"\xd0\x01\n" +
	"\x12CodebaseChunkEvent\x126\n" +
	"\x05chunk\x18\x01 \x01(\v2\x1e.yorha.retrieval.CodebaseChunkH\x00R\x05chunk\x12@\n" +
	"\bprogress\x18\x02 \x01(\v2\".yorha.retrieval.RetrievalProgressH\x00R\bprogress\x127\n" +
	"\x05error\x18\x03 \x01(\v2\x1f.yorha.retrieval.RetrievalErrorH\x00R\x05errorB\a\n" +
	"\x05event\"\xa4\x02\n" +
	"\rCodebaseChunk\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1f\n" +
	"\vhttp_method\x18\x04 \x01(\tR\n" +
	"httpMethod\x12\x19\n" +
	"\broute_id\x18\x05 \x01(\tR\arouteId\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12'\n" +
	"\x0fcontent_preview\x18\a \x01(\tR\x0econtentPreview\x12\x14\n" +
	"\x05score\x18\b \x01(\x02R\x05score\x12\x1d\n" +
	"\n" +
	"start_line\x18\t \x01(\x05R\tstartLine\x12\x19\n" +
	"\bend_line\x18\n" +
	" \x01(\x05R\aendLine\"\x85\x01\n" +
	"\x0eGraphHopPolicy\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\x05R\x04mode\x12$\n" +
	"\x0emax_hop_chunks\x18\x02 \x01(\x05R\fmaxHopChunks\x129\n" +
	"\x19within_same_evidence_only\x18\x03 \x01(\bR\x16withinSameEvidenceOnly\"\xc2\x01\n" +
	"\x0fPrefilterPolicy\x12#\n" +
	"\renable_qdrant\x18\x01 \x01(\bR\fenableQdrant\x12)\n" +
	"\x10qdrant_shortlist\x18\x02 \x01(\x05R\x0fqdrantShortlist\x12'\n" +
	"\x0fscore_threshold\x18\x03 \x01(\x02R\x0escoreThreshold\x126\n" +
	"\x17allow_pgvector_fallback\x18\x04 \x01(\bR\x15allowPgvectorFallback\"\x8d\x01\n" +
	"\n" +
	"RankPolicy\x12#\n" +
	"\rcosine_weight\x18\x01 \x01(\x02R\fcosineWeight\x12)\n" +
	"\x10citations_weight\x18\x02 \x01(\x02R\x0fcitationsWeight\x12/\n" +
	"\x13jurisdiction_weight\x18\x03 \x01(\x02R\x12jurisdictionWeight\"s\n" +
	"\x11RetrievalProgress\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x18\n" +
	"\acurrent\x18\x02 \x01(\x05R\acurrent\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"a\n" +
	"\x0eRetrievalError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fdetails_json\x18\x03 \x01(\tR\vdetailsJson\")\n" +
	"\rHealthRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xfb\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12-\n" +
	"\x12pgvector_connected\x18\x02 \x01(\bR\x11pgvectorConnected\x12)\n" +
	"\x10qdrant_connected\x18\x03 \x01(\bR\x0fqdrantConnected\x12'\n" +
	"\x0fredis_connected\x18\x04 \x01(\bR\x0eredisConnected\x120\n" +
	"\x14embedding_service_up\x18\x05 \x01(\bR\x12embeddingServiceUp\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp2\xe6\x03\n" +
	"\x10RetrievalService\x12a\n" +
	"\x0eSearchEvidence\x12&.yorha.retrieval.EvidenceSearchRequest\x1a'.yorha.retrieval.EvidenceSearchResponse\x12`\n" +
	"\x0eStreamEvidence\x12&.yorha.retrieval.EvidenceSearchRequest\x1a$.yorha.retrieval.EvidenceBundleEvent0\x01\x12a\n" +
	"\x0eSearchCodebase\x12&.yorha.retrieval.CodebaseSearchRequest\x1a'.yorha.retrieval.CodebaseSearchResponse\x12_\n" +
	"\x0eStreamCodebase\x12&.yorha.retrieval.CodebaseSearchRequest\x1a#.yorha.retrieval.CodebaseChunkEvent0\x01\x12I\n" +
	"\x06Health\x12\x1e.yorha.retrieval.HealthRequest\x1a\x1f.yorha.retrieval.HealthResponseB*Z(github.com/deeds-web-app/proto/retrievalb\x06proto3"

var (
	file_proto_active_retrieval_proto_rawDescOnce sync.Once
	file_proto_active_retrieval_proto_rawDescData []byte
)

func file_proto_active_retrieval_proto_rawDescGZIP() []byte {
	file_proto_active_retrieval_proto_rawDescOnce.Do(func() {
		file_proto_active_retrieval_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_active_retrieval_proto_rawDesc), len(file_proto_active_retrieval_proto_rawDesc)))
	})
	return file_proto_active_retrieval_proto_rawDescData
}

var file_proto_active_retrieval_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_active_retrieval_proto_goTypes = []any{
	(*EvidenceSearchRequest)(nil),  // 0: yorha.retrieval.EvidenceSearchRequest
	(*EvidenceSearchResponse)(nil), // 1: yorha.retrieval.EvidenceSearchResponse
	(*EvidenceBundleEvent)(nil),    // 2: yorha.retrieval.EvidenceBundleEvent
	(*SearchResult)(nil),           // 3: yorha.retrieval.SearchResult
	(*ChunkMetadata)(nil),          // 4: yorha.retrieval.ChunkMetadata
	(*RerankExplain)(nil),          // 5: yorha.retrieval.RerankExplain
	(*ContextBundle)(nil),          // 6: yorha.retrieval.ContextBundle
	(*GraphNeighbor)(nil),          // 7: yorha.retrieval.GraphNeighbor
	(*DocumentContext)(nil),        // 8: yorha.retrieval.DocumentContext
	(*SearchTiming)(nil),           // 9: yorha.retrieval.SearchTiming
	(*CodebaseSearchRequest)(nil),  // 10: yorha.retrieval.CodebaseSearchRequest
	(*CodebaseSearchResponse)(nil), // 11: yorha.retrieval.CodebaseSearchResponse
	(*CodebaseChunkEvent)(nil),     // 12: yorha.retrieval.CodebaseChunkEvent
	(*CodebaseChunk)(nil),          // 13: yorha.retrieval.CodebaseChunk
	(*GraphHopPolicy)(nil),         // 14: yorha.retrieval.GraphHopPolicy
	(*PrefilterPolicy)(nil),        // 15: yorha.retrieval.PrefilterPolicy
	(*RankPolicy)(nil),             // 16: yorha.retrieval.RankPolicy
	(*RetrievalProgress)(nil),      // 17: yorha.retrieval.RetrievalProgress
	(*RetrievalError)(nil),         // 18: yorha.retrieval.RetrievalError
	(*HealthRequest)(nil),          // 19: yorha.retrieval.HealthRequest
	(*HealthResponse)(nil),         // 20: yorha.retrieval.HealthResponse
}
var file_proto_active_retrieval_proto_depIdxs = []int32{
	14, // 0: yorha.retrieval.EvidenceSearchRequest.hop:type_name -> yorha.retrieval.GraphHopPolicy
	15, // 1: yorha.retrieval.EvidenceSearchRequest.prefilter:type_name -> yorha.retrieval.PrefilterPolicy
	16, // 2: yorha.retrieval.EvidenceSearchRequest.rank:type_name -> yorha.retrieval.RankPolicy
	3,  // 3: yorha.retrieval.EvidenceSearchResponse.results:type_name -> yorha.retrieval.SearchResult
	6,  // 4: yorha.retrieval.EvidenceSearchResponse.bundles:type_name -> yorha.retrieval.ContextBundle
	9,  // 5: yorha.retrieval.EvidenceSearchResponse.timing:type_name -> yorha.retrieval.SearchTiming
	6,  // 6: yorha.retrieval.EvidenceBundleEvent.bundle:type_name -> yorha.retrieval.ContextBundle
	17, // 7: yorha.retrieval.EvidenceBundleEvent.progress:type_name -> yorha.retrieval.RetrievalProgress
	18, // 8: yorha.retrieval.EvidenceBundleEvent.error:type_name -> yorha.retrieval.RetrievalError
	4,  // 9: yorha.retrieval.SearchResult.metadata:type_name -> yorha.retrieval.ChunkMetadata
	5,  // 10: yorha.retrieval.SearchResult.rerank:type_name -> yorha.retrieval.RerankExplain
	3,  // 11: yorha.retrieval.ContextBundle.hit:type_name -> yorha.retrieval.SearchResult
	3,  // 12: yorha.retrieval.ContextBundle.siblings:type_name -> yorha.retrieval.SearchResult
	7,  // 13: yorha.retrieval.ContextBundle.graph_neighbors:type_name -> yorha.retrieval.GraphNeighbor
	8,  // 14: yorha.retrieval.ContextBundle.document_context:type_name -> yorha.retrieval.DocumentContext
	13, // 15: yorha.retrieval.CodebaseSearchResponse.chunks:type_name -> yorha.retrieval.CodebaseChunk
	13, // 16: yorha.retrieval.CodebaseChunkEvent.chunk:type_name -> yorha.retrieval.CodebaseChunk
	17, // 17: yorha.retrieval.CodebaseChunkEvent.progress:type_name -> yorha.retrieval.RetrievalProgress
	18, // 18: yorha.retrieval.CodebaseChunkEvent.error:type_name -> yorha.retrieval.RetrievalError
	0,  // 19: yorha.retrieval.RetrievalService.SearchEvidence:input_type -> yorha.retrieval.EvidenceSearchRequest
	0,  // 20: yorha.retrieval.RetrievalService.StreamEvidence:input_type -> yorha.retrieval.EvidenceSearchRequest
	10, // 21: yorha.retrieval.RetrievalService.SearchCodebase:input_type -> yorha.retrieval.CodebaseSearchRequest
	10, // 22: yorha.retrieval.RetrievalService.StreamCodebase:input_type -> yorha.retrieval.CodebaseSearchRequest
	19, // 23: yorha.retrieval.RetrievalService.Health:input_type -> yorha.retrieval.HealthRequest
	1,  // 24: yorha.retrieval.RetrievalService.SearchEvidence:output_type -> yorha.retrieval.EvidenceSearchResponse
	2,  // 25: yorha.retrieval.RetrievalService.StreamEvidence:output_type -> yorha.retrieval.EvidenceBundleEvent
	11, // 26: yorha.retrieval.RetrievalService.SearchCodebase:output_type -> yorha.retrieval.CodebaseSearchResponse
	12, // 27: yorha.retrieval.RetrievalService.StreamCodebase:output_type -> yorha.retrieval.CodebaseChunkEvent
	20, // 28: yorha.retrieval.RetrievalService.Health:output_type -> yorha.retrieval.HealthResponse
	24, // [24:29] is the sub-list for method output_type
	19, // [19:24] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_active_retrieval_proto_init() }
func file_proto_active_retrieval_proto_init() {
	if File_proto_active_retrieval_proto != nil {
		return
	}
	file_proto_active_retrieval_proto_msgTypes[2].OneofWrappers = []any{
		(*EvidenceBundleEvent_Bundle)(nil),
		(*EvidenceBundleEvent_Progress)(nil),
		(*EvidenceBundleEvent_Error)(nil),
	}
	file_proto_active_retrieval_proto_msgTypes[12].OneofWrappers = []any{
		(*CodebaseChunkEvent_Chunk)(nil),
		(*CodebaseChunkEvent_Progress)(nil),
		(*CodebaseChunkEvent_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_active_retrieval_proto_rawDesc), len(file_proto_active_retrieval_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_active_retrieval_proto_goTypes,
		DependencyIndexes: file_proto_active_retrieval_proto_depIdxs,
		MessageInfos:      file_proto_active_retrieval_proto_msgTypes,
	}.Build()
	File_proto_active_retrieval_proto = out.File
	file_proto_active_retrieval_proto_goTypes = nil
	file_proto_active_retrieval_proto_depIdxs = nil
}
