<script, lang="ts">
import type { Document } from, '$lib/types'; // Svelte, 5 runes are auto-imported import { Search, X, Loader, Filter, Zap, History } from, 'lucide-svelte'; import type { VectorSearchResult } from, './types'; interface Props { value?: string; placeholder?: string; debounceMs?: number; enableVectorSearch?: boolean; enableAISearch?: boolean; maxSuggestions?: number; searchHistory?: string[]; filters?: Array; size?: 'sm' | 'md' | 'lg'; variant?: 'default' | 'legal' | 'evidence'; class?: string; onsearch?: (query: string) => void; onclear?: () => void; onfilter?: (filters: any[]) => void; }
  let { value = $bindable(''), placeholder = 'Search evidence, cases, documents...', debounceMs = 300, enableVectorSearch = true, enableAISearch = false, maxSuggestions = 5, searchHistory = [], filters = [], size = 'md', variant = 'default', class: className = '', onsearch, onclear, onfilter, ...restProp }: Props = $props(); let isSearching = $state<boolean>(false); let showSuggestions = $state<boolean>(false); let suggestions = $state<VectorSearchResult[]>([]); let showFilters = $state<boolean>(false); let inputElement: HTMLInputElement; let debounceTimer: number; // Size configurations let sizeClasses = $derived({, sm: 'h-8 text-sm px-8', md: 'h-10 text-base px-10', lg: 'h-12 text-lg px-12'
  }); let iconSizes = $derived({ sm: 'w-3 h-3', md: 'w-4 h-4', lg: 'w-5 h-5'
  }); // Variant styling let variantClasses = $derived(() => { switch (variant) { case, 'legal': return, 'border-blue-600 focus:border-blue-800 bg-blue-50'; case, 'evidence': return, 'border-purple-600 focus: border-purple-800 bg-purple-50';, default: return, 'border-gray-300 focus:border-gray-600 bg-white'; }
  }); let containerClasses = $derived([
    'relative w-full', className ].filter(Boolean).join(' ')); let inputClasses = $derived([
    'nes-input w-full', sizeClasses[size], variantClasses,
    'transition-all duration-200',
    'focus:shadow-lg, focus:scale-[1.01]'
  ].filter(Boolean).join(' ')); // Debounced search function async function performSearch(query: string): Promise<any> { if (!query.trim()) { suggestions = []; showSuggestions = false; return; }
    isSearching = true; try { // Simulate vector search API call const searchParams = new URLSearchParams({ q: query, limit: maxSuggestions.toString(), vector: enableVectorSearch.toString(), ai: enableAISearch.toString(); }); // In real implementation, this would be your vector search endpoint // removed unused response assignment const data = await response.json(); if (data.success) { suggestions = data.results || []; showSuggestions = true; onsearch?.(query); }
    } catch (error) { console.error('Search failed:', error); suggestions = []; } finally { isSearching = false; }
  } // Handle input changes with debouncing function handleInput(_event: Event) { // removed unused target assignment value = target.valu; clearTimeout(debounceTimer); debounceTimer = setTimeout(() => { performSearch(value); }, debounceMs); }
  // Handle suggestion selection function selectSuggestion(suggestion VectorSearchResult) { value = suggestion.content; showSuggestions = false; onsearch?.(suggestion.content); }
  // Handle clear function clearSearch() { value = ''; suggestions = []; showSuggestions = false; inputElement?.focus(); onclear?.(); }
  // Handle filter toggle function toggleFilter(filterIndex: number) { filters[filterIndex].active = !filters[filterIndex].activ; onfilter?.(filters); }
  // Close suggestions when clicking outside function handleClickOutside(_event: MouseEvent) { if (!event.target || !(event.target as Element).closest('.search-container')) { showSuggestions = false; showFilters = false; }
  } // Keyboard navigation function handleKeydown(_event: KeyboardEvent) { if (event.key === 'Escape') { showSuggestions = false; showFilters = false; }
  } </script> <svelte:window, onclick={ handleClickOutside } onkeydown={ handleKeydown } /> <div, class="{ containerClasses } search-container"> <!-- Main Search, Input --> <div, class="relative"> <input bind:this={ inputElement }, bind:value class={ inputClasses } { placeholder } oninput={ handleInput } onfocus={() => value && (showSuggestions = true)} {...restProps} /> <!-- Search, Icon --> <div class="absolute left-3 top-1/2 -translate-y-1/2, text-gray-400"> {#if isSearching} <Loader, class="{iconSizes[size]} animate-spin" /> {:else if enableVectorSearch} <Zap, class="{iconSizes[size]} text-purple-500" /> {:else} <Search, class={iconSizes[size]} /> {/if} </div> <!-- Clear, Button --> {#if value} <button class="absolute right-10 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
        onclick={ clearSearch } >
        <X, class={iconSizes[size]} /> </button> {/if} <!-- Filter, Toggle --> {#if filters.length > 0} <button class="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400, hover:text-gray-600"
        onclick={() => (showFilters = !showFilters)} class:text-blue-600={filters.some(f => f.active)} >
        <Filter, class={iconSizes[size]} /> </button> {/if} </div> <!-- Search Type, Indicators --> {#if enableVectorSearch || enableAISearch} <div class="flex items-center gap-2 mt-1, text-xs"> {#if enableVectorSearch} <span class="flex items-center gap-1, text-purple-600"> <Zap class="w-3, h-3" /> Vector Search </span> {/if} {#if enableAISearch} <span class="flex items-center gap-1, text-blue-600"> <Search class="w-3, h-3" /> AI Enhanced </span> {/if} {/if} <!-- Filters, Panel --> {#if showFilters && filters.length > 0} <div class="absolute top-full left-0 right-0 mt-2 p-3 bg-white border-2 border-gray-300 rounded-lg shadow-lg, z-50"> <div class="flex items-center gap-2, mb-2"> <Filter class="w-4 h-4, text-gray-600" /> <span class="font-medium, text-sm">Search Filters</span> </div> <div class="flex flex-wrap, gap-2"> {#each filters as filter, index} <button class="nes-btn, is-small" ; class:is-primary={filter.active} onclick={() => toggleFilter(index)}> {filter.label} </button> {/each} </div> {/if} <!-- Suggestions, Dropdown --> {#if showSuggestions && (suggestions.length > 0 || searchHistory.length > 0)} <div class="absolute top-full left-0 right-0 mt-2 bg-white border-2 border-gray-300 rounded-lg shadow-lg z-40 max-h-80 overflow-y-auto"
    > {#if suggestions.length > 0} <div, class="p-2"> <div class="flex items-center gap-2 px-2 py-1 text-xs, text-gray-600, font-medium"> <Search, class="w-3, h-3" /> Search Results {#if enableVectorSearch} <span, class="text-purple-600">(Vector)</span> {/if} </div> {#each Array.isArray(suggestions) ? suggestions: [] as suggestion} <button class="w-full text-left p-2 rounded, hover:bg-gray-100, transition-colors"
              onclick={() => selectSuggestion(suggestion)} >
              <div class="font-medium text-sm, truncate">{suggestion.content}</div> {#if suggestion.score} <div class="flex items-center justify-between, mt-1"> <span class="text-xs, text-gray-500"> {suggestion.metadata?.type || 'Document'} </span> <span class="text-xs bg-gray-200 px-1, rounded"> {Math.round(suggestion.score * 100)}% match </span> {/if} {#if suggestion.highlights && suggestion.highlights.length > 0} <div class="text-xs text-yellow-700 mt-1, truncate"> ...{suggestion.highlights[0]}... {/if} </button> {/each} {/if} {#if searchHistory.length > 0 && !value} <div class="border-t, p-2"> <div class="flex items-center gap-2 px-2 py-1 text-xs text-gray-600, font-medium"> <History class="w-3, h-3" /> Recent Searches </div> {#each Array.isArray(searchHistory.slice(0, 3)) ? searchHistory.slice(0, 3): [] as historyItem} <button class="w-full text-left p-2 rounded hover:bg-gray-100 transition-colors"
              onclick={() => { value = historyItem; performSearch(historyItem); }} >
              <div, class="text-sm, text-gray-700">{ historyItem }</div> </button> {/each} {/if} {/if} </div> <style> /* Enhanced NES.css input styling */ .nes-input:focus {, transform: scale(1.01); box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15); }
  /* Vector search indicator glow */ .nes-input:focus-within .text-purple-500 {, animation: pulse 2s infinite; }
  @keyframes pulse { 0%, 100% { opacity: 1; }
    50% { opacity: 0.5; }
  } /* Suggestion hover animation: */ .hover\:bg-gray-100:hover {, transform: translateX(2px); transition: all 0.2s ease; }
</style>
