// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.1
// source: tensor_cache.proto

package tensor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type TensorType int32

const (
	TensorType_TENSOR_TYPE_UNKNOWN      TensorType = 0
	TensorType_TENSOR_TYPE_EMBEDDING    TensorType = 1 // Text/document embeddings
	TensorType_TENSOR_TYPE_ATTENTION    TensorType = 2 // Attention weights
	TensorType_TENSOR_TYPE_HIDDEN_STATE TensorType = 3 // Hidden layer states
	TensorType_TENSOR_TYPE_LOGITS       TensorType = 4 // Model output logits
	TensorType_TENSOR_TYPE_KV_CACHE     TensorType = 5 // Key-value cache for inference
	TensorType_TENSOR_TYPE_GRADIENT     TensorType = 6 // Gradient tensors
	TensorType_TENSOR_TYPE_WEIGHTS      TensorType = 7 // Model weights
	TensorType_TENSOR_TYPE_ACTIVATIONS  TensorType = 8 // Layer activations
)

// Enum value maps for TensorType.
var (
	TensorType_name = map[int32]string{
		0: "TENSOR_TYPE_UNKNOWN",
		1: "TENSOR_TYPE_EMBEDDING",
		2: "TENSOR_TYPE_ATTENTION",
		3: "TENSOR_TYPE_HIDDEN_STATE",
		4: "TENSOR_TYPE_LOGITS",
		5: "TENSOR_TYPE_KV_CACHE",
		6: "TENSOR_TYPE_GRADIENT",
		7: "TENSOR_TYPE_WEIGHTS",
		8: "TENSOR_TYPE_ACTIVATIONS",
	}
	TensorType_value = map[string]int32{
		"TENSOR_TYPE_UNKNOWN":      0,
		"TENSOR_TYPE_EMBEDDING":    1,
		"TENSOR_TYPE_ATTENTION":    2,
		"TENSOR_TYPE_HIDDEN_STATE": 3,
		"TENSOR_TYPE_LOGITS":       4,
		"TENSOR_TYPE_KV_CACHE":     5,
		"TENSOR_TYPE_GRADIENT":     6,
		"TENSOR_TYPE_WEIGHTS":      7,
		"TENSOR_TYPE_ACTIVATIONS":  8,
	}
)

func (x TensorType) Enum() *TensorType {
	p := new(TensorType)
	*p = x
	return p
}

func (x TensorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TensorType) Descriptor() protoreflect.EnumDescriptor {
	return file_tensor_cache_proto_enumTypes[0].Descriptor()
}

func (TensorType) Type() protoreflect.EnumType {
	return &file_tensor_cache_proto_enumTypes[0]
}

func (x TensorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TensorType.Descriptor instead.
func (TensorType) EnumDescriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{0}
}

type CompressionType int32

const (
	CompressionType_COMPRESSION_NONE    CompressionType = 0
	CompressionType_COMPRESSION_FLOAT16 CompressionType = 1 // 50% reduction
	CompressionType_COMPRESSION_INT8    CompressionType = 2 // 75% reduction
	CompressionType_COMPRESSION_INT4    CompressionType = 3 // 87.5% reduction
	CompressionType_COMPRESSION_HUFFMAN CompressionType = 4 // Variable compression
	CompressionType_COMPRESSION_LZ4     CompressionType = 5 // Fast compression
	CompressionType_COMPRESSION_ZSTD    CompressionType = 6 // High ratio compression
)

// Enum value maps for CompressionType.
var (
	CompressionType_name = map[int32]string{
		0: "COMPRESSION_NONE",
		1: "COMPRESSION_FLOAT16",
		2: "COMPRESSION_INT8",
		3: "COMPRESSION_INT4",
		4: "COMPRESSION_HUFFMAN",
		5: "COMPRESSION_LZ4",
		6: "COMPRESSION_ZSTD",
	}
	CompressionType_value = map[string]int32{
		"COMPRESSION_NONE":    0,
		"COMPRESSION_FLOAT16": 1,
		"COMPRESSION_INT8":    2,
		"COMPRESSION_INT4":    3,
		"COMPRESSION_HUFFMAN": 4,
		"COMPRESSION_LZ4":     5,
		"COMPRESSION_ZSTD":    6,
	}
)

func (x CompressionType) Enum() *CompressionType {
	p := new(CompressionType)
	*p = x
	return p
}

func (x CompressionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompressionType) Descriptor() protoreflect.EnumDescriptor {
	return file_tensor_cache_proto_enumTypes[1].Descriptor()
}

func (CompressionType) Type() protoreflect.EnumType {
	return &file_tensor_cache_proto_enumTypes[1]
}

func (x CompressionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompressionType.Descriptor instead.
func (CompressionType) EnumDescriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{1}
}

type CacheLocation int32

const (
	CacheLocation_LOCATION_UNKNOWN      CacheLocation = 0
	CacheLocation_LOCATION_GPU_VRAM     CacheLocation = 1 // Fastest access
	CacheLocation_LOCATION_RAM          CacheLocation = 2 // Fast access
	CacheLocation_LOCATION_REDIS        CacheLocation = 3 // Network access
	CacheLocation_LOCATION_MMAP         CacheLocation = 4 // Disk access
	CacheLocation_LOCATION_COLD_STORAGE CacheLocation = 5 // Archive storage
)

// Enum value maps for CacheLocation.
var (
	CacheLocation_name = map[int32]string{
		0: "LOCATION_UNKNOWN",
		1: "LOCATION_GPU_VRAM",
		2: "LOCATION_RAM",
		3: "LOCATION_REDIS",
		4: "LOCATION_MMAP",
		5: "LOCATION_COLD_STORAGE",
	}
	CacheLocation_value = map[string]int32{
		"LOCATION_UNKNOWN":      0,
		"LOCATION_GPU_VRAM":     1,
		"LOCATION_RAM":          2,
		"LOCATION_REDIS":        3,
		"LOCATION_MMAP":         4,
		"LOCATION_COLD_STORAGE": 5,
	}
)

func (x CacheLocation) Enum() *CacheLocation {
	p := new(CacheLocation)
	*p = x
	return p
}

func (x CacheLocation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CacheLocation) Descriptor() protoreflect.EnumDescriptor {
	return file_tensor_cache_proto_enumTypes[2].Descriptor()
}

func (CacheLocation) Type() protoreflect.EnumType {
	return &file_tensor_cache_proto_enumTypes[2]
}

func (x CacheLocation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CacheLocation.Descriptor instead.
func (CacheLocation) EnumDescriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{2}
}

type Priority int32

const (
	Priority_PRIORITY_LOW      Priority = 0
	Priority_PRIORITY_NORMAL   Priority = 1
	Priority_PRIORITY_HIGH     Priority = 2
	Priority_PRIORITY_CRITICAL Priority = 3 // Never evict
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_LOW",
		1: "PRIORITY_NORMAL",
		2: "PRIORITY_HIGH",
		3: "PRIORITY_CRITICAL",
	}
	Priority_value = map[string]int32{
		"PRIORITY_LOW":      0,
		"PRIORITY_NORMAL":   1,
		"PRIORITY_HIGH":     2,
		"PRIORITY_CRITICAL": 3,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_tensor_cache_proto_enumTypes[3].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_tensor_cache_proto_enumTypes[3]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{3}
}

type EvictionPolicy int32

const (
	EvictionPolicy_EVICTION_LRU      EvictionPolicy = 0 // Least Recently Used
	EvictionPolicy_EVICTION_LFU      EvictionPolicy = 1 // Least Frequently Used
	EvictionPolicy_EVICTION_FIFO     EvictionPolicy = 2 // First In, First Out
	EvictionPolicy_EVICTION_RANDOM   EvictionPolicy = 3 // Random eviction
	EvictionPolicy_EVICTION_PRIORITY EvictionPolicy = 4 // Priority-based
	EvictionPolicy_EVICTION_SIZE     EvictionPolicy = 5 // Largest first
	EvictionPolicy_EVICTION_AGE      EvictionPolicy = 6 // Oldest first
)

// Enum value maps for EvictionPolicy.
var (
	EvictionPolicy_name = map[int32]string{
		0: "EVICTION_LRU",
		1: "EVICTION_LFU",
		2: "EVICTION_FIFO",
		3: "EVICTION_RANDOM",
		4: "EVICTION_PRIORITY",
		5: "EVICTION_SIZE",
		6: "EVICTION_AGE",
	}
	EvictionPolicy_value = map[string]int32{
		"EVICTION_LRU":      0,
		"EVICTION_LFU":      1,
		"EVICTION_FIFO":     2,
		"EVICTION_RANDOM":   3,
		"EVICTION_PRIORITY": 4,
		"EVICTION_SIZE":     5,
		"EVICTION_AGE":      6,
	}
)

func (x EvictionPolicy) Enum() *EvictionPolicy {
	p := new(EvictionPolicy)
	*p = x
	return p
}

func (x EvictionPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EvictionPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_tensor_cache_proto_enumTypes[4].Descriptor()
}

func (EvictionPolicy) Type() protoreflect.EnumType {
	return &file_tensor_cache_proto_enumTypes[4]
}

func (x EvictionPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EvictionPolicy.Descriptor instead.
func (EvictionPolicy) EnumDescriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{4}
}

type OptimizationStrategy int32

const (
	OptimizationStrategy_OPTIMIZE_NONE       OptimizationStrategy = 0
	OptimizationStrategy_OPTIMIZE_MEMORY     OptimizationStrategy = 1 // Minimize memory usage
	OptimizationStrategy_OPTIMIZE_SPEED      OptimizationStrategy = 2 // Minimize access time
	OptimizationStrategy_OPTIMIZE_BALANCED   OptimizationStrategy = 3 // Balance memory and speed
	OptimizationStrategy_OPTIMIZE_AGGRESSIVE OptimizationStrategy = 4 // Maximum optimization
)

// Enum value maps for OptimizationStrategy.
var (
	OptimizationStrategy_name = map[int32]string{
		0: "OPTIMIZE_NONE",
		1: "OPTIMIZE_MEMORY",
		2: "OPTIMIZE_SPEED",
		3: "OPTIMIZE_BALANCED",
		4: "OPTIMIZE_AGGRESSIVE",
	}
	OptimizationStrategy_value = map[string]int32{
		"OPTIMIZE_NONE":       0,
		"OPTIMIZE_MEMORY":     1,
		"OPTIMIZE_SPEED":      2,
		"OPTIMIZE_BALANCED":   3,
		"OPTIMIZE_AGGRESSIVE": 4,
	}
)

func (x OptimizationStrategy) Enum() *OptimizationStrategy {
	p := new(OptimizationStrategy)
	*p = x
	return p
}

func (x OptimizationStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OptimizationStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_tensor_cache_proto_enumTypes[5].Descriptor()
}

func (OptimizationStrategy) Type() protoreflect.EnumType {
	return &file_tensor_cache_proto_enumTypes[5]
}

func (x OptimizationStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OptimizationStrategy.Descriptor instead.
func (OptimizationStrategy) EnumDescriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{5}
}

type GPUBufferUsage int32

const (
	GPUBufferUsage_GPU_BUFFER_VERTEX   GPUBufferUsage = 0
	GPUBufferUsage_GPU_BUFFER_INDEX    GPUBufferUsage = 1
	GPUBufferUsage_GPU_BUFFER_UNIFORM  GPUBufferUsage = 2
	GPUBufferUsage_GPU_BUFFER_STORAGE  GPUBufferUsage = 3
	GPUBufferUsage_GPU_BUFFER_INDIRECT GPUBufferUsage = 4
	GPUBufferUsage_GPU_BUFFER_COPY_SRC GPUBufferUsage = 5
	GPUBufferUsage_GPU_BUFFER_COPY_DST GPUBufferUsage = 6
)

// Enum value maps for GPUBufferUsage.
var (
	GPUBufferUsage_name = map[int32]string{
		0: "GPU_BUFFER_VERTEX",
		1: "GPU_BUFFER_INDEX",
		2: "GPU_BUFFER_UNIFORM",
		3: "GPU_BUFFER_STORAGE",
		4: "GPU_BUFFER_INDIRECT",
		5: "GPU_BUFFER_COPY_SRC",
		6: "GPU_BUFFER_COPY_DST",
	}
	GPUBufferUsage_value = map[string]int32{
		"GPU_BUFFER_VERTEX":   0,
		"GPU_BUFFER_INDEX":    1,
		"GPU_BUFFER_UNIFORM":  2,
		"GPU_BUFFER_STORAGE":  3,
		"GPU_BUFFER_INDIRECT": 4,
		"GPU_BUFFER_COPY_SRC": 5,
		"GPU_BUFFER_COPY_DST": 6,
	}
)

func (x GPUBufferUsage) Enum() *GPUBufferUsage {
	p := new(GPUBufferUsage)
	*p = x
	return p
}

func (x GPUBufferUsage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GPUBufferUsage) Descriptor() protoreflect.EnumDescriptor {
	return file_tensor_cache_proto_enumTypes[6].Descriptor()
}

func (GPUBufferUsage) Type() protoreflect.EnumType {
	return &file_tensor_cache_proto_enumTypes[6]
}

func (x GPUBufferUsage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GPUBufferUsage.Descriptor instead.
func (GPUBufferUsage) EnumDescriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{6}
}

// Core tensor data structure
type TensorCache struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                 // Unique tensor identifier
	Shape         []uint64               `protobuf:"varint,2,rep,packed,name=shape,proto3" json:"shape,omitempty"`                   // Tensor dimensions
	Dtype         string                 `protobuf:"bytes,3,opt,name=dtype,proto3" json:"dtype,omitempty"`                           // "float32", "float16", "int8", etc.
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                             // Bit-packed tensor data
	References    []string               `protobuf:"bytes,5,rep,name=references,proto3" json:"references,omitempty"`                 // Parent case/document IDs
	LodLevel      int32                  `protobuf:"varint,6,opt,name=lod_level,json=lodLevel,proto3" json:"lod_level,omitempty"`    // Level of Detail: 0=full, 1=half, 2=quarter
	GpuOffset     uint64                 `protobuf:"varint,7,opt,name=gpu_offset,json=gpuOffset,proto3" json:"gpu_offset,omitempty"` // Offset in GPU buffer if loaded
	Timestamp     int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                  // Creation/access timestamp
	Metadata      *TensorMetadata        `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`                     // Additional metadata
	Compression   *CompressionInfo       `protobuf:"bytes,10,opt,name=compression,proto3" json:"compression,omitempty"`              // Compression details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TensorCache) Reset() {
	*x = TensorCache{}
	mi := &file_tensor_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TensorCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TensorCache) ProtoMessage() {}

func (x *TensorCache) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TensorCache.ProtoReflect.Descriptor instead.
func (*TensorCache) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{0}
}

func (x *TensorCache) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TensorCache) GetShape() []uint64 {
	if x != nil {
		return x.Shape
	}
	return nil
}

func (x *TensorCache) GetDtype() string {
	if x != nil {
		return x.Dtype
	}
	return ""
}

func (x *TensorCache) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TensorCache) GetReferences() []string {
	if x != nil {
		return x.References
	}
	return nil
}

func (x *TensorCache) GetLodLevel() int32 {
	if x != nil {
		return x.LodLevel
	}
	return 0
}

func (x *TensorCache) GetGpuOffset() uint64 {
	if x != nil {
		return x.GpuOffset
	}
	return 0
}

func (x *TensorCache) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TensorCache) GetMetadata() *TensorMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TensorCache) GetCompression() *CompressionInfo {
	if x != nil {
		return x.Compression
	}
	return nil
}

// Tensor metadata for cache management
type TensorMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                  // User session
	CaseId        string                 `protobuf:"bytes,2,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`                                           // Legal case identifier
	DocumentId    string                 `protobuf:"bytes,3,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`                               // Source document
	ModelName     string                 `protobuf:"bytes,4,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`                                  // Model that generated tensor
	TensorType    TensorType             `protobuf:"varint,5,opt,name=tensor_type,json=tensorType,proto3,enum=tensor_cache.TensorType" json:"tensor_type,omitempty"` // Type of tensor
	AccessCount   uint64                 `protobuf:"varint,6,opt,name=access_count,json=accessCount,proto3" json:"access_count,omitempty"`                           // Number of times accessed
	LastAccessed  int64                  `protobuf:"varint,7,opt,name=last_accessed,json=lastAccessed,proto3" json:"last_accessed,omitempty"`                        // Last access timestamp
	Priority      Priority               `protobuf:"varint,8,opt,name=priority,proto3,enum=tensor_cache.Priority" json:"priority,omitempty"`                         // Cache priority
	Tags          []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`                                                             // Searchable tags
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TensorMetadata) Reset() {
	*x = TensorMetadata{}
	mi := &file_tensor_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TensorMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TensorMetadata) ProtoMessage() {}

func (x *TensorMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TensorMetadata.ProtoReflect.Descriptor instead.
func (*TensorMetadata) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{1}
}

func (x *TensorMetadata) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TensorMetadata) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *TensorMetadata) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *TensorMetadata) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *TensorMetadata) GetTensorType() TensorType {
	if x != nil {
		return x.TensorType
	}
	return TensorType_TENSOR_TYPE_UNKNOWN
}

func (x *TensorMetadata) GetAccessCount() uint64 {
	if x != nil {
		return x.AccessCount
	}
	return 0
}

func (x *TensorMetadata) GetLastAccessed() int64 {
	if x != nil {
		return x.LastAccessed
	}
	return 0
}

func (x *TensorMetadata) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_LOW
}

func (x *TensorMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Compression information for bit-packing
type CompressionInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           CompressionType        `protobuf:"varint,1,opt,name=type,proto3,enum=tensor_cache.CompressionType" json:"type,omitempty"`         // Compression algorithm used
	ScaleFactor    float32                `protobuf:"fixed32,2,opt,name=scale_factor,json=scaleFactor,proto3" json:"scale_factor,omitempty"`         // Quantization scale
	Offset         float32                `protobuf:"fixed32,3,opt,name=offset,proto3" json:"offset,omitempty"`                                      // Quantization offset
	OriginalSize   uint64                 `protobuf:"varint,4,opt,name=original_size,json=originalSize,proto3" json:"original_size,omitempty"`       // Original uncompressed size
	CompressedSize uint64                 `protobuf:"varint,5,opt,name=compressed_size,json=compressedSize,proto3" json:"compressed_size,omitempty"` // Compressed size
	Checksum       string                 `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"`                                    // Data integrity check
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompressionInfo) Reset() {
	*x = CompressionInfo{}
	mi := &file_tensor_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompressionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressionInfo) ProtoMessage() {}

func (x *CompressionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressionInfo.ProtoReflect.Descriptor instead.
func (*CompressionInfo) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{2}
}

func (x *CompressionInfo) GetType() CompressionType {
	if x != nil {
		return x.Type
	}
	return CompressionType_COMPRESSION_NONE
}

func (x *CompressionInfo) GetScaleFactor() float32 {
	if x != nil {
		return x.ScaleFactor
	}
	return 0
}

func (x *CompressionInfo) GetOffset() float32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *CompressionInfo) GetOriginalSize() uint64 {
	if x != nil {
		return x.OriginalSize
	}
	return 0
}

func (x *CompressionInfo) GetCompressedSize() uint64 {
	if x != nil {
		return x.CompressedSize
	}
	return 0
}

func (x *CompressionInfo) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

// Request/Response messages
type StoreTensorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tensor        *TensorCache           `protobuf:"bytes,1,opt,name=tensor,proto3" json:"tensor,omitempty"`
	GenerateLod   bool                   `protobuf:"varint,2,opt,name=generate_lod,json=generateLod,proto3" json:"generate_lod,omitempty"` // Auto-generate LoD versions
	ForceGpu      bool                   `protobuf:"varint,3,opt,name=force_gpu,json=forceGpu,proto3" json:"force_gpu,omitempty"`          // Force GPU storage
	Options       *CacheOptions          `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`                             // Storage options
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreTensorRequest) Reset() {
	*x = StoreTensorRequest{}
	mi := &file_tensor_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreTensorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreTensorRequest) ProtoMessage() {}

func (x *StoreTensorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreTensorRequest.ProtoReflect.Descriptor instead.
func (*StoreTensorRequest) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{3}
}

func (x *StoreTensorRequest) GetTensor() *TensorCache {
	if x != nil {
		return x.Tensor
	}
	return nil
}

func (x *StoreTensorRequest) GetGenerateLod() bool {
	if x != nil {
		return x.GenerateLod
	}
	return false
}

func (x *StoreTensorRequest) GetForceGpu() bool {
	if x != nil {
		return x.ForceGpu
	}
	return false
}

func (x *StoreTensorRequest) GetOptions() *CacheOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type StoreTensorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TensorId      string                 `protobuf:"bytes,2,opt,name=tensor_id,json=tensorId,proto3" json:"tensor_id,omitempty"`
	LodIds        []string               `protobuf:"bytes,3,rep,name=lod_ids,json=lodIds,proto3" json:"lod_ids,omitempty"`                        // IDs of generated LoD versions
	Location      CacheLocation          `protobuf:"varint,4,opt,name=location,proto3,enum=tensor_cache.CacheLocation" json:"location,omitempty"` // Where tensor was stored
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreTensorResponse) Reset() {
	*x = StoreTensorResponse{}
	mi := &file_tensor_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreTensorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreTensorResponse) ProtoMessage() {}

func (x *StoreTensorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreTensorResponse.ProtoReflect.Descriptor instead.
func (*StoreTensorResponse) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{4}
}

func (x *StoreTensorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreTensorResponse) GetTensorId() string {
	if x != nil {
		return x.TensorId
	}
	return ""
}

func (x *StoreTensorResponse) GetLodIds() []string {
	if x != nil {
		return x.LodIds
	}
	return nil
}

func (x *StoreTensorResponse) GetLocation() CacheLocation {
	if x != nil {
		return x.Location
	}
	return CacheLocation_LOCATION_UNKNOWN
}

func (x *StoreTensorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetTensorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TensorId      string                 `protobuf:"bytes,1,opt,name=tensor_id,json=tensorId,proto3" json:"tensor_id,omitempty"`
	RequiredLod   int32                  `protobuf:"varint,2,opt,name=required_lod,json=requiredLod,proto3" json:"required_lod,omitempty"`      // Minimum LoD level required
	PreferGpu     bool                   `protobuf:"varint,3,opt,name=prefer_gpu,json=preferGpu,proto3" json:"prefer_gpu,omitempty"`            // Prefer GPU version if available
	PromoteToGpu  bool                   `protobuf:"varint,4,opt,name=promote_to_gpu,json=promoteToGpu,proto3" json:"promote_to_gpu,omitempty"` // Promote to GPU after retrieval
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTensorRequest) Reset() {
	*x = GetTensorRequest{}
	mi := &file_tensor_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTensorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTensorRequest) ProtoMessage() {}

func (x *GetTensorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTensorRequest.ProtoReflect.Descriptor instead.
func (*GetTensorRequest) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{5}
}

func (x *GetTensorRequest) GetTensorId() string {
	if x != nil {
		return x.TensorId
	}
	return ""
}

func (x *GetTensorRequest) GetRequiredLod() int32 {
	if x != nil {
		return x.RequiredLod
	}
	return 0
}

func (x *GetTensorRequest) GetPreferGpu() bool {
	if x != nil {
		return x.PreferGpu
	}
	return false
}

func (x *GetTensorRequest) GetPromoteToGpu() bool {
	if x != nil {
		return x.PromoteToGpu
	}
	return false
}

type GetTensorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Tensor        *TensorCache           `protobuf:"bytes,2,opt,name=tensor,proto3" json:"tensor,omitempty"`
	Source        CacheLocation          `protobuf:"varint,3,opt,name=source,proto3,enum=tensor_cache.CacheLocation" json:"source,omitempty"` // Which cache tier provided the tensor
	Metrics       *PerformanceMetrics    `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`                                // Retrieval performance
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTensorResponse) Reset() {
	*x = GetTensorResponse{}
	mi := &file_tensor_cache_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTensorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTensorResponse) ProtoMessage() {}

func (x *GetTensorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTensorResponse.ProtoReflect.Descriptor instead.
func (*GetTensorResponse) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{6}
}

func (x *GetTensorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTensorResponse) GetTensor() *TensorCache {
	if x != nil {
		return x.Tensor
	}
	return nil
}

func (x *GetTensorResponse) GetSource() CacheLocation {
	if x != nil {
		return x.Source
	}
	return CacheLocation_LOCATION_UNKNOWN
}

func (x *GetTensorResponse) GetMetrics() *PerformanceMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *GetTensorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BatchStoreTensorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*StoreTensorRequest  `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	Atomic        bool                   `protobuf:"varint,2,opt,name=atomic,proto3" json:"atomic,omitempty"` // All or nothing storage
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchStoreTensorRequest) Reset() {
	*x = BatchStoreTensorRequest{}
	mi := &file_tensor_cache_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchStoreTensorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStoreTensorRequest) ProtoMessage() {}

func (x *BatchStoreTensorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStoreTensorRequest.ProtoReflect.Descriptor instead.
func (*BatchStoreTensorRequest) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{7}
}

func (x *BatchStoreTensorRequest) GetRequests() []*StoreTensorRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *BatchStoreTensorRequest) GetAtomic() bool {
	if x != nil {
		return x.Atomic
	}
	return false
}

type BatchStoreTensorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*StoreTensorResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	AllSucceeded  bool                   `protobuf:"varint,2,opt,name=all_succeeded,json=allSucceeded,proto3" json:"all_succeeded,omitempty"`
	Metrics       *PerformanceMetrics    `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchStoreTensorResponse) Reset() {
	*x = BatchStoreTensorResponse{}
	mi := &file_tensor_cache_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchStoreTensorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStoreTensorResponse) ProtoMessage() {}

func (x *BatchStoreTensorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStoreTensorResponse.ProtoReflect.Descriptor instead.
func (*BatchStoreTensorResponse) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{8}
}

func (x *BatchStoreTensorResponse) GetResponses() []*StoreTensorResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *BatchStoreTensorResponse) GetAllSucceeded() bool {
	if x != nil {
		return x.AllSucceeded
	}
	return false
}

func (x *BatchStoreTensorResponse) GetMetrics() *PerformanceMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type BatchGetTensorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*GetTensorRequest    `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	PrefetchToGpu bool                   `protobuf:"varint,2,opt,name=prefetch_to_gpu,json=prefetchToGpu,proto3" json:"prefetch_to_gpu,omitempty"` // Prefetch results to GPU
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetTensorRequest) Reset() {
	*x = BatchGetTensorRequest{}
	mi := &file_tensor_cache_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetTensorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetTensorRequest) ProtoMessage() {}

func (x *BatchGetTensorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetTensorRequest.ProtoReflect.Descriptor instead.
func (*BatchGetTensorRequest) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{9}
}

func (x *BatchGetTensorRequest) GetRequests() []*GetTensorRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *BatchGetTensorRequest) GetPrefetchToGpu() bool {
	if x != nil {
		return x.PrefetchToGpu
	}
	return false
}

type BatchGetTensorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*GetTensorResponse   `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	Metrics       *PerformanceMetrics    `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetTensorResponse) Reset() {
	*x = BatchGetTensorResponse{}
	mi := &file_tensor_cache_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetTensorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetTensorResponse) ProtoMessage() {}

func (x *BatchGetTensorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetTensorResponse.ProtoReflect.Descriptor instead.
func (*BatchGetTensorResponse) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{10}
}

func (x *BatchGetTensorResponse) GetResponses() []*GetTensorResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *BatchGetTensorResponse) GetMetrics() *PerformanceMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type EvictTensorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TensorIds     []string               `protobuf:"bytes,1,rep,name=tensor_ids,json=tensorIds,proto3" json:"tensor_ids,omitempty"`                                     // Specific tensors to evict
	Policy        EvictionPolicy         `protobuf:"varint,2,opt,name=policy,proto3,enum=tensor_cache.EvictionPolicy" json:"policy,omitempty"`                          // Eviction strategy
	TargetTier    CacheLocation          `protobuf:"varint,3,opt,name=target_tier,json=targetTier,proto3,enum=tensor_cache.CacheLocation" json:"target_tier,omitempty"` // Which tier to evict from
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvictTensorsRequest) Reset() {
	*x = EvictTensorsRequest{}
	mi := &file_tensor_cache_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvictTensorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictTensorsRequest) ProtoMessage() {}

func (x *EvictTensorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictTensorsRequest.ProtoReflect.Descriptor instead.
func (*EvictTensorsRequest) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{11}
}

func (x *EvictTensorsRequest) GetTensorIds() []string {
	if x != nil {
		return x.TensorIds
	}
	return nil
}

func (x *EvictTensorsRequest) GetPolicy() EvictionPolicy {
	if x != nil {
		return x.Policy
	}
	return EvictionPolicy_EVICTION_LRU
}

func (x *EvictTensorsRequest) GetTargetTier() CacheLocation {
	if x != nil {
		return x.TargetTier
	}
	return CacheLocation_LOCATION_UNKNOWN
}

type EvictTensorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	EvictedCount  uint32                 `protobuf:"varint,2,opt,name=evicted_count,json=evictedCount,proto3" json:"evicted_count,omitempty"`
	FreedBytes    uint64                 `protobuf:"varint,3,opt,name=freed_bytes,json=freedBytes,proto3" json:"freed_bytes,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvictTensorsResponse) Reset() {
	*x = EvictTensorsResponse{}
	mi := &file_tensor_cache_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvictTensorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictTensorsResponse) ProtoMessage() {}

func (x *EvictTensorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictTensorsResponse.ProtoReflect.Descriptor instead.
func (*EvictTensorsResponse) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{12}
}

func (x *EvictTensorsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EvictTensorsResponse) GetEvictedCount() uint32 {
	if x != nil {
		return x.EvictedCount
	}
	return 0
}

func (x *EvictTensorsResponse) GetFreedBytes() uint64 {
	if x != nil {
		return x.FreedBytes
	}
	return 0
}

func (x *EvictTensorsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetCacheMetricsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IncludeDetailed bool                   `protobuf:"varint,1,opt,name=include_detailed,json=includeDetailed,proto3" json:"include_detailed,omitempty"`
	TensorIds       []string               `protobuf:"bytes,2,rep,name=tensor_ids,json=tensorIds,proto3" json:"tensor_ids,omitempty"` // Specific tensors to get metrics for
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCacheMetricsRequest) Reset() {
	*x = GetCacheMetricsRequest{}
	mi := &file_tensor_cache_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCacheMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheMetricsRequest) ProtoMessage() {}

func (x *GetCacheMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetCacheMetricsRequest) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{13}
}

func (x *GetCacheMetricsRequest) GetIncludeDetailed() bool {
	if x != nil {
		return x.IncludeDetailed
	}
	return false
}

func (x *GetCacheMetricsRequest) GetTensorIds() []string {
	if x != nil {
		return x.TensorIds
	}
	return nil
}

type GetCacheMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *CacheMetrics          `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	TensorMetrics []*TensorMetrics       `protobuf:"bytes,2,rep,name=tensor_metrics,json=tensorMetrics,proto3" json:"tensor_metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCacheMetricsResponse) Reset() {
	*x = GetCacheMetricsResponse{}
	mi := &file_tensor_cache_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCacheMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheMetricsResponse) ProtoMessage() {}

func (x *GetCacheMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetCacheMetricsResponse) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{14}
}

func (x *GetCacheMetricsResponse) GetMetrics() *CacheMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *GetCacheMetricsResponse) GetTensorMetrics() []*TensorMetrics {
	if x != nil {
		return x.TensorMetrics
	}
	return nil
}

type PromoteToGPURequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TensorIds      []string               `protobuf:"bytes,1,rep,name=tensor_ids,json=tensorIds,proto3" json:"tensor_ids,omitempty"`
	MaxLodLevel    int32                  `protobuf:"varint,2,opt,name=max_lod_level,json=maxLodLevel,proto3" json:"max_lod_level,omitempty"`        // Maximum LoD to load
	ForcePromotion bool                   `protobuf:"varint,3,opt,name=force_promotion,json=forcePromotion,proto3" json:"force_promotion,omitempty"` // Evict other tensors if needed
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PromoteToGPURequest) Reset() {
	*x = PromoteToGPURequest{}
	mi := &file_tensor_cache_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteToGPURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteToGPURequest) ProtoMessage() {}

func (x *PromoteToGPURequest) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteToGPURequest.ProtoReflect.Descriptor instead.
func (*PromoteToGPURequest) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{15}
}

func (x *PromoteToGPURequest) GetTensorIds() []string {
	if x != nil {
		return x.TensorIds
	}
	return nil
}

func (x *PromoteToGPURequest) GetMaxLodLevel() int32 {
	if x != nil {
		return x.MaxLodLevel
	}
	return 0
}

func (x *PromoteToGPURequest) GetForcePromotion() bool {
	if x != nil {
		return x.ForcePromotion
	}
	return false
}

type PromoteToGPUResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PromotedIds   []string               `protobuf:"bytes,2,rep,name=promoted_ids,json=promotedIds,proto3" json:"promoted_ids,omitempty"`
	FailedIds     []string               `protobuf:"bytes,3,rep,name=failed_ids,json=failedIds,proto3" json:"failed_ids,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteToGPUResponse) Reset() {
	*x = PromoteToGPUResponse{}
	mi := &file_tensor_cache_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteToGPUResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteToGPUResponse) ProtoMessage() {}

func (x *PromoteToGPUResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteToGPUResponse.ProtoReflect.Descriptor instead.
func (*PromoteToGPUResponse) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{16}
}

func (x *PromoteToGPUResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PromoteToGPUResponse) GetPromotedIds() []string {
	if x != nil {
		return x.PromotedIds
	}
	return nil
}

func (x *PromoteToGPUResponse) GetFailedIds() []string {
	if x != nil {
		return x.FailedIds
	}
	return nil
}

func (x *PromoteToGPUResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type OptimizeGPUMemoryRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Strategy          OptimizationStrategy   `protobuf:"varint,1,opt,name=strategy,proto3,enum=tensor_cache.OptimizationStrategy" json:"strategy,omitempty"`
	TargetUtilization float32                `protobuf:"fixed32,2,opt,name=target_utilization,json=targetUtilization,proto3" json:"target_utilization,omitempty"` // Target GPU memory utilization (0.0-1.0)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OptimizeGPUMemoryRequest) Reset() {
	*x = OptimizeGPUMemoryRequest{}
	mi := &file_tensor_cache_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeGPUMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeGPUMemoryRequest) ProtoMessage() {}

func (x *OptimizeGPUMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeGPUMemoryRequest.ProtoReflect.Descriptor instead.
func (*OptimizeGPUMemoryRequest) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{17}
}

func (x *OptimizeGPUMemoryRequest) GetStrategy() OptimizationStrategy {
	if x != nil {
		return x.Strategy
	}
	return OptimizationStrategy_OPTIMIZE_NONE
}

func (x *OptimizeGPUMemoryRequest) GetTargetUtilization() float32 {
	if x != nil {
		return x.TargetUtilization
	}
	return 0
}

type OptimizeGPUMemoryResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	FreedBytes       uint64                 `protobuf:"varint,2,opt,name=freed_bytes,json=freedBytes,proto3" json:"freed_bytes,omitempty"`
	OptimizedTensors uint32                 `protobuf:"varint,3,opt,name=optimized_tensors,json=optimizedTensors,proto3" json:"optimized_tensors,omitempty"`
	Metrics          *PerformanceMetrics    `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Error            string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OptimizeGPUMemoryResponse) Reset() {
	*x = OptimizeGPUMemoryResponse{}
	mi := &file_tensor_cache_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeGPUMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeGPUMemoryResponse) ProtoMessage() {}

func (x *OptimizeGPUMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeGPUMemoryResponse.ProtoReflect.Descriptor instead.
func (*OptimizeGPUMemoryResponse) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{18}
}

func (x *OptimizeGPUMemoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OptimizeGPUMemoryResponse) GetFreedBytes() uint64 {
	if x != nil {
		return x.FreedBytes
	}
	return 0
}

func (x *OptimizeGPUMemoryResponse) GetOptimizedTensors() uint32 {
	if x != nil {
		return x.OptimizedTensors
	}
	return 0
}

func (x *OptimizeGPUMemoryResponse) GetMetrics() *PerformanceMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *OptimizeGPUMemoryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Supporting data structures
type CacheOptions struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Ttl               *Duration              `protobuf:"bytes,1,opt,name=ttl,proto3" json:"ttl,omitempty"`                                                       // Time to live
	PersistToDisk     bool                   `protobuf:"varint,2,opt,name=persist_to_disk,json=persistToDisk,proto3" json:"persist_to_disk,omitempty"`           // Create memory-mapped backup
	EnableCompression bool                   `protobuf:"varint,3,opt,name=enable_compression,json=enableCompression,proto3" json:"enable_compression,omitempty"` // Use bit-packing
	CompressionType   CompressionType        `protobuf:"varint,4,opt,name=compression_type,json=compressionType,proto3,enum=tensor_cache.CompressionType" json:"compression_type,omitempty"`
	Priority          Priority               `protobuf:"varint,5,opt,name=priority,proto3,enum=tensor_cache.Priority" json:"priority,omitempty"` // Cache priority
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CacheOptions) Reset() {
	*x = CacheOptions{}
	mi := &file_tensor_cache_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheOptions) ProtoMessage() {}

func (x *CacheOptions) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheOptions.ProtoReflect.Descriptor instead.
func (*CacheOptions) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{19}
}

func (x *CacheOptions) GetTtl() *Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *CacheOptions) GetPersistToDisk() bool {
	if x != nil {
		return x.PersistToDisk
	}
	return false
}

func (x *CacheOptions) GetEnableCompression() bool {
	if x != nil {
		return x.EnableCompression
	}
	return false
}

func (x *CacheOptions) GetCompressionType() CompressionType {
	if x != nil {
		return x.CompressionType
	}
	return CompressionType_COMPRESSION_NONE
}

func (x *CacheOptions) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_LOW
}

type PerformanceMetrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RetrievalTimeNs  int64                  `protobuf:"varint,1,opt,name=retrieval_time_ns,json=retrievalTimeNs,proto3" json:"retrieval_time_ns,omitempty"` // Nanoseconds
	BytesTransferred uint64                 `protobuf:"varint,2,opt,name=bytes_transferred,json=bytesTransferred,proto3" json:"bytes_transferred,omitempty"`
	SourceTier       CacheLocation          `protobuf:"varint,3,opt,name=source_tier,json=sourceTier,proto3,enum=tensor_cache.CacheLocation" json:"source_tier,omitempty"`
	CacheHit         bool                   `protobuf:"varint,4,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"`
	HitRate          float32                `protobuf:"fixed32,5,opt,name=hit_rate,json=hitRate,proto3" json:"hit_rate,omitempty"`
	LodLevelUsed     int32                  `protobuf:"varint,6,opt,name=lod_level_used,json=lodLevelUsed,proto3" json:"lod_level_used,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PerformanceMetrics) Reset() {
	*x = PerformanceMetrics{}
	mi := &file_tensor_cache_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformanceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformanceMetrics) ProtoMessage() {}

func (x *PerformanceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformanceMetrics.ProtoReflect.Descriptor instead.
func (*PerformanceMetrics) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{20}
}

func (x *PerformanceMetrics) GetRetrievalTimeNs() int64 {
	if x != nil {
		return x.RetrievalTimeNs
	}
	return 0
}

func (x *PerformanceMetrics) GetBytesTransferred() uint64 {
	if x != nil {
		return x.BytesTransferred
	}
	return 0
}

func (x *PerformanceMetrics) GetSourceTier() CacheLocation {
	if x != nil {
		return x.SourceTier
	}
	return CacheLocation_LOCATION_UNKNOWN
}

func (x *PerformanceMetrics) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

func (x *PerformanceMetrics) GetHitRate() float32 {
	if x != nil {
		return x.HitRate
	}
	return 0
}

func (x *PerformanceMetrics) GetLodLevelUsed() int32 {
	if x != nil {
		return x.LodLevelUsed
	}
	return 0
}

type CacheMetrics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalQueries   uint64                 `protobuf:"varint,1,opt,name=total_queries,json=totalQueries,proto3" json:"total_queries,omitempty"`
	GpuHits        uint64                 `protobuf:"varint,2,opt,name=gpu_hits,json=gpuHits,proto3" json:"gpu_hits,omitempty"`
	RamHits        uint64                 `protobuf:"varint,3,opt,name=ram_hits,json=ramHits,proto3" json:"ram_hits,omitempty"`
	RedisHits      uint64                 `protobuf:"varint,4,opt,name=redis_hits,json=redisHits,proto3" json:"redis_hits,omitempty"`
	MmapHits       uint64                 `protobuf:"varint,5,opt,name=mmap_hits,json=mmapHits,proto3" json:"mmap_hits,omitempty"`
	CacheMisses    uint64                 `protobuf:"varint,6,opt,name=cache_misses,json=cacheMisses,proto3" json:"cache_misses,omitempty"`
	OverallHitRate float32                `protobuf:"fixed32,7,opt,name=overall_hit_rate,json=overallHitRate,proto3" json:"overall_hit_rate,omitempty"`
	// Memory usage by tier
	GpuMemory   *MemoryUsage `protobuf:"bytes,8,opt,name=gpu_memory,json=gpuMemory,proto3" json:"gpu_memory,omitempty"`
	RamMemory   *MemoryUsage `protobuf:"bytes,9,opt,name=ram_memory,json=ramMemory,proto3" json:"ram_memory,omitempty"`
	RedisMemory *MemoryUsage `protobuf:"bytes,10,opt,name=redis_memory,json=redisMemory,proto3" json:"redis_memory,omitempty"`
	DiskMemory  *MemoryUsage `protobuf:"bytes,11,opt,name=disk_memory,json=diskMemory,proto3" json:"disk_memory,omitempty"`
	// Performance metrics
	AvgRetrievalTimeMs float32 `protobuf:"fixed32,12,opt,name=avg_retrieval_time_ms,json=avgRetrievalTimeMs,proto3" json:"avg_retrieval_time_ms,omitempty"`
	TotalEvictions     uint64  `protobuf:"varint,13,opt,name=total_evictions,json=totalEvictions,proto3" json:"total_evictions,omitempty"`
	LastGcTime         int64   `protobuf:"varint,14,opt,name=last_gc_time,json=lastGcTime,proto3" json:"last_gc_time,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CacheMetrics) Reset() {
	*x = CacheMetrics{}
	mi := &file_tensor_cache_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheMetrics) ProtoMessage() {}

func (x *CacheMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheMetrics.ProtoReflect.Descriptor instead.
func (*CacheMetrics) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{21}
}

func (x *CacheMetrics) GetTotalQueries() uint64 {
	if x != nil {
		return x.TotalQueries
	}
	return 0
}

func (x *CacheMetrics) GetGpuHits() uint64 {
	if x != nil {
		return x.GpuHits
	}
	return 0
}

func (x *CacheMetrics) GetRamHits() uint64 {
	if x != nil {
		return x.RamHits
	}
	return 0
}

func (x *CacheMetrics) GetRedisHits() uint64 {
	if x != nil {
		return x.RedisHits
	}
	return 0
}

func (x *CacheMetrics) GetMmapHits() uint64 {
	if x != nil {
		return x.MmapHits
	}
	return 0
}

func (x *CacheMetrics) GetCacheMisses() uint64 {
	if x != nil {
		return x.CacheMisses
	}
	return 0
}

func (x *CacheMetrics) GetOverallHitRate() float32 {
	if x != nil {
		return x.OverallHitRate
	}
	return 0
}

func (x *CacheMetrics) GetGpuMemory() *MemoryUsage {
	if x != nil {
		return x.GpuMemory
	}
	return nil
}

func (x *CacheMetrics) GetRamMemory() *MemoryUsage {
	if x != nil {
		return x.RamMemory
	}
	return nil
}

func (x *CacheMetrics) GetRedisMemory() *MemoryUsage {
	if x != nil {
		return x.RedisMemory
	}
	return nil
}

func (x *CacheMetrics) GetDiskMemory() *MemoryUsage {
	if x != nil {
		return x.DiskMemory
	}
	return nil
}

func (x *CacheMetrics) GetAvgRetrievalTimeMs() float32 {
	if x != nil {
		return x.AvgRetrievalTimeMs
	}
	return 0
}

func (x *CacheMetrics) GetTotalEvictions() uint64 {
	if x != nil {
		return x.TotalEvictions
	}
	return 0
}

func (x *CacheMetrics) GetLastGcTime() int64 {
	if x != nil {
		return x.LastGcTime
	}
	return 0
}

type MemoryUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsedBytes     uint64                 `protobuf:"varint,1,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	Utilization   float32                `protobuf:"fixed32,3,opt,name=utilization,proto3" json:"utilization,omitempty"` // 0.0 to 1.0
	ObjectCount   uint32                 `protobuf:"varint,4,opt,name=object_count,json=objectCount,proto3" json:"object_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryUsage) Reset() {
	*x = MemoryUsage{}
	mi := &file_tensor_cache_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryUsage) ProtoMessage() {}

func (x *MemoryUsage) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryUsage.ProtoReflect.Descriptor instead.
func (*MemoryUsage) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{22}
}

func (x *MemoryUsage) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *MemoryUsage) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *MemoryUsage) GetUtilization() float32 {
	if x != nil {
		return x.Utilization
	}
	return 0
}

func (x *MemoryUsage) GetObjectCount() uint32 {
	if x != nil {
		return x.ObjectCount
	}
	return 0
}

type TensorMetrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TensorId           string                 `protobuf:"bytes,1,opt,name=tensor_id,json=tensorId,proto3" json:"tensor_id,omitempty"`
	AccessCount        uint64                 `protobuf:"varint,2,opt,name=access_count,json=accessCount,proto3" json:"access_count,omitempty"`
	LastAccessed       int64                  `protobuf:"varint,3,opt,name=last_accessed,json=lastAccessed,proto3" json:"last_accessed,omitempty"`
	SizeBytes          uint64                 `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CurrentLocation    CacheLocation          `protobuf:"varint,5,opt,name=current_location,json=currentLocation,proto3,enum=tensor_cache.CacheLocation" json:"current_location,omitempty"`
	CurrentLod         int32                  `protobuf:"varint,6,opt,name=current_lod,json=currentLod,proto3" json:"current_lod,omitempty"`
	AvailableLocations []CacheLocation        `protobuf:"varint,7,rep,packed,name=available_locations,json=availableLocations,proto3,enum=tensor_cache.CacheLocation" json:"available_locations,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TensorMetrics) Reset() {
	*x = TensorMetrics{}
	mi := &file_tensor_cache_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TensorMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TensorMetrics) ProtoMessage() {}

func (x *TensorMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TensorMetrics.ProtoReflect.Descriptor instead.
func (*TensorMetrics) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{23}
}

func (x *TensorMetrics) GetTensorId() string {
	if x != nil {
		return x.TensorId
	}
	return ""
}

func (x *TensorMetrics) GetAccessCount() uint64 {
	if x != nil {
		return x.AccessCount
	}
	return 0
}

func (x *TensorMetrics) GetLastAccessed() int64 {
	if x != nil {
		return x.LastAccessed
	}
	return 0
}

func (x *TensorMetrics) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *TensorMetrics) GetCurrentLocation() CacheLocation {
	if x != nil {
		return x.CurrentLocation
	}
	return CacheLocation_LOCATION_UNKNOWN
}

func (x *TensorMetrics) GetCurrentLod() int32 {
	if x != nil {
		return x.CurrentLod
	}
	return 0
}

func (x *TensorMetrics) GetAvailableLocations() []CacheLocation {
	if x != nil {
		return x.AvailableLocations
	}
	return nil
}

type Duration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seconds       int64                  `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos         int32                  `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Duration) Reset() {
	*x = Duration{}
	mi := &file_tensor_cache_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Duration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duration) ProtoMessage() {}

func (x *Duration) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duration.ProtoReflect.Descriptor instead.
func (*Duration) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{24}
}

func (x *Duration) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Duration) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

// WebGPU Integration Messages
type WebGPUBuffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BufferId      string                 `protobuf:"bytes,1,opt,name=buffer_id,json=bufferId,proto3" json:"buffer_id,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Usage         GPUBufferUsage         `protobuf:"varint,3,opt,name=usage,proto3,enum=tensor_cache.GPUBufferUsage" json:"usage,omitempty"`
	Mapped        bool                   `protobuf:"varint,4,opt,name=mapped,proto3" json:"mapped,omitempty"`
	TensorIds     []string               `protobuf:"bytes,5,rep,name=tensor_ids,json=tensorIds,proto3" json:"tensor_ids,omitempty"` // Tensors stored in this buffer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebGPUBuffer) Reset() {
	*x = WebGPUBuffer{}
	mi := &file_tensor_cache_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebGPUBuffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebGPUBuffer) ProtoMessage() {}

func (x *WebGPUBuffer) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebGPUBuffer.ProtoReflect.Descriptor instead.
func (*WebGPUBuffer) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{25}
}

func (x *WebGPUBuffer) GetBufferId() string {
	if x != nil {
		return x.BufferId
	}
	return ""
}

func (x *WebGPUBuffer) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *WebGPUBuffer) GetUsage() GPUBufferUsage {
	if x != nil {
		return x.Usage
	}
	return GPUBufferUsage_GPU_BUFFER_VERTEX
}

func (x *WebGPUBuffer) GetMapped() bool {
	if x != nil {
		return x.Mapped
	}
	return false
}

func (x *WebGPUBuffer) GetTensorIds() []string {
	if x != nil {
		return x.TensorIds
	}
	return nil
}

type GPUBufferLayout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bindings      []*BufferBinding       `protobuf:"bytes,1,rep,name=bindings,proto3" json:"bindings,omitempty"`
	TotalSize     uint64                 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	Alignment     uint32                 `protobuf:"varint,3,opt,name=alignment,proto3" json:"alignment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUBufferLayout) Reset() {
	*x = GPUBufferLayout{}
	mi := &file_tensor_cache_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUBufferLayout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUBufferLayout) ProtoMessage() {}

func (x *GPUBufferLayout) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUBufferLayout.ProtoReflect.Descriptor instead.
func (*GPUBufferLayout) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{26}
}

func (x *GPUBufferLayout) GetBindings() []*BufferBinding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

func (x *GPUBufferLayout) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *GPUBufferLayout) GetAlignment() uint32 {
	if x != nil {
		return x.Alignment
	}
	return 0
}

type BufferBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Binding       uint32                 `protobuf:"varint,1,opt,name=binding,proto3" json:"binding,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	TensorId      string                 `protobuf:"bytes,4,opt,name=tensor_id,json=tensorId,proto3" json:"tensor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BufferBinding) Reset() {
	*x = BufferBinding{}
	mi := &file_tensor_cache_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BufferBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BufferBinding) ProtoMessage() {}

func (x *BufferBinding) ProtoReflect() protoreflect.Message {
	mi := &file_tensor_cache_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BufferBinding.ProtoReflect.Descriptor instead.
func (*BufferBinding) Descriptor() ([]byte, []int) {
	return file_tensor_cache_proto_rawDescGZIP(), []int{27}
}

func (x *BufferBinding) GetBinding() uint32 {
	if x != nil {
		return x.Binding
	}
	return 0
}

func (x *BufferBinding) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *BufferBinding) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BufferBinding) GetTensorId() string {
	if x != nil {
		return x.TensorId
	}
	return ""
}

var File_tensor_cache_proto protoreflect.FileDescriptor

const file_tensor_cache_proto_rawDesc = "" +
	"\n" +
	"\x12tensor_cache.proto\x12\ftensor_cache\"\xd2\x02\n" +
	"\vTensorCache\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05shape\x18\x02 \x03(\x04R\x05shape\x12\x14\n" +
	"\x05dtype\x18\x03 \x01(\tR\x05dtype\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1e\n" +
	"\n" +
	"references\x18\x05 \x03(\tR\n" +
	"references\x12\x1b\n" +
	"\tlod_level\x18\x06 \x01(\x05R\blodLevel\x12\x1d\n" +
	"\n" +
	"gpu_offset\x18\a \x01(\x04R\tgpuOffset\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x128\n" +
	"\bmetadata\x18\t \x01(\v2\x1c.tensor_cache.TensorMetadataR\bmetadata\x12?\n" +
	"\vcompression\x18\n" +
	" \x01(\v2\x1d.tensor_cache.CompressionInfoR\vcompression\"\xd3\x02\n" +
	"\x0eTensorMetadata\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\acase_id\x18\x02 \x01(\tR\x06caseId\x12\x1f\n" +
	"\vdocument_id\x18\x03 \x01(\tR\n" +
	"documentId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x04 \x01(\tR\tmodelName\x129\n" +
	"\vtensor_type\x18\x05 \x01(\x0e2\x18.tensor_cache.TensorTypeR\n" +
	"tensorType\x12!\n" +
	"\faccess_count\x18\x06 \x01(\x04R\vaccessCount\x12#\n" +
	"\rlast_accessed\x18\a \x01(\x03R\flastAccessed\x122\n" +
	"\bpriority\x18\b \x01(\x0e2\x16.tensor_cache.PriorityR\bpriority\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\"\xe9\x01\n" +
	"\x0fCompressionInfo\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.tensor_cache.CompressionTypeR\x04type\x12!\n" +
	"\fscale_factor\x18\x02 \x01(\x02R\vscaleFactor\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x02R\x06offset\x12#\n" +
	"\roriginal_size\x18\x04 \x01(\x04R\foriginalSize\x12'\n" +
	"\x0fcompressed_size\x18\x05 \x01(\x04R\x0ecompressedSize\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\tR\bchecksum\"\xbd\x01\n" +
	"\x12StoreTensorRequest\x121\n" +
	"\x06tensor\x18\x01 \x01(\v2\x19.tensor_cache.TensorCacheR\x06tensor\x12!\n" +
	"\fgenerate_lod\x18\x02 \x01(\bR\vgenerateLod\x12\x1b\n" +
	"\tforce_gpu\x18\x03 \x01(\bR\bforceGpu\x124\n" +
	"\aoptions\x18\x04 \x01(\v2\x1a.tensor_cache.CacheOptionsR\aoptions\"\xb4\x01\n" +
	"\x13StoreTensorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\ttensor_id\x18\x02 \x01(\tR\btensorId\x12\x17\n" +
	"\alod_ids\x18\x03 \x03(\tR\x06lodIds\x127\n" +
	"\blocation\x18\x04 \x01(\x0e2\x1b.tensor_cache.CacheLocationR\blocation\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\x97\x01\n" +
	"\x10GetTensorRequest\x12\x1b\n" +
	"\ttensor_id\x18\x01 \x01(\tR\btensorId\x12!\n" +
	"\frequired_lod\x18\x02 \x01(\x05R\vrequiredLod\x12\x1d\n" +
	"\n" +
	"prefer_gpu\x18\x03 \x01(\bR\tpreferGpu\x12$\n" +
	"\x0epromote_to_gpu\x18\x04 \x01(\bR\fpromoteToGpu\"\xe7\x01\n" +
	"\x11GetTensorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x121\n" +
	"\x06tensor\x18\x02 \x01(\v2\x19.tensor_cache.TensorCacheR\x06tensor\x123\n" +
	"\x06source\x18\x03 \x01(\x0e2\x1b.tensor_cache.CacheLocationR\x06source\x12:\n" +
	"\ametrics\x18\x04 \x01(\v2 .tensor_cache.PerformanceMetricsR\ametrics\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"o\n" +
	"\x17BatchStoreTensorRequest\x12<\n" +
	"\brequests\x18\x01 \x03(\v2 .tensor_cache.StoreTensorRequestR\brequests\x12\x16\n" +
	"\x06atomic\x18\x02 \x01(\bR\x06atomic\"\xbc\x01\n" +
	"\x18BatchStoreTensorResponse\x12?\n" +
	"\tresponses\x18\x01 \x03(\v2!.tensor_cache.StoreTensorResponseR\tresponses\x12#\n" +
	"\rall_succeeded\x18\x02 \x01(\bR\fallSucceeded\x12:\n" +
	"\ametrics\x18\x03 \x01(\v2 .tensor_cache.PerformanceMetricsR\ametrics\"{\n" +
	"\x15BatchGetTensorRequest\x12:\n" +
	"\brequests\x18\x01 \x03(\v2\x1e.tensor_cache.GetTensorRequestR\brequests\x12&\n" +
	"\x0fprefetch_to_gpu\x18\x02 \x01(\bR\rprefetchToGpu\"\x93\x01\n" +
	"\x16BatchGetTensorResponse\x12=\n" +
	"\tresponses\x18\x01 \x03(\v2\x1f.tensor_cache.GetTensorResponseR\tresponses\x12:\n" +
	"\ametrics\x18\x02 \x01(\v2 .tensor_cache.PerformanceMetricsR\ametrics\"\xa8\x01\n" +
	"\x13EvictTensorsRequest\x12\x1d\n" +
	"\n" +
	"tensor_ids\x18\x01 \x03(\tR\ttensorIds\x124\n" +
	"\x06policy\x18\x02 \x01(\x0e2\x1c.tensor_cache.EvictionPolicyR\x06policy\x12<\n" +
	"\vtarget_tier\x18\x03 \x01(\x0e2\x1b.tensor_cache.CacheLocationR\n" +
	"targetTier\"\x8c\x01\n" +
	"\x14EvictTensorsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\revicted_count\x18\x02 \x01(\rR\fevictedCount\x12\x1f\n" +
	"\vfreed_bytes\x18\x03 \x01(\x04R\n" +
	"freedBytes\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"b\n" +
	"\x16GetCacheMetricsRequest\x12)\n" +
	"\x10include_detailed\x18\x01 \x01(\bR\x0fincludeDetailed\x12\x1d\n" +
	"\n" +
	"tensor_ids\x18\x02 \x03(\tR\ttensorIds\"\x93\x01\n" +
	"\x17GetCacheMetricsResponse\x124\n" +
	"\ametrics\x18\x01 \x01(\v2\x1a.tensor_cache.CacheMetricsR\ametrics\x12B\n" +
	"\x0etensor_metrics\x18\x02 \x03(\v2\x1b.tensor_cache.TensorMetricsR\rtensorMetrics\"\x81\x01\n" +
	"\x13PromoteToGPURequest\x12\x1d\n" +
	"\n" +
	"tensor_ids\x18\x01 \x03(\tR\ttensorIds\x12\"\n" +
	"\rmax_lod_level\x18\x02 \x01(\x05R\vmaxLodLevel\x12'\n" +
	"\x0fforce_promotion\x18\x03 \x01(\bR\x0eforcePromotion\"\x88\x01\n" +
	"\x14PromoteToGPUResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fpromoted_ids\x18\x02 \x03(\tR\vpromotedIds\x12\x1d\n" +
	"\n" +
	"failed_ids\x18\x03 \x03(\tR\tfailedIds\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x89\x01\n" +
	"\x18OptimizeGPUMemoryRequest\x12>\n" +
	"\bstrategy\x18\x01 \x01(\x0e2\".tensor_cache.OptimizationStrategyR\bstrategy\x12-\n" +
	"\x12target_utilization\x18\x02 \x01(\x02R\x11targetUtilization\"\xd5\x01\n" +
	"\x19OptimizeGPUMemoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vfreed_bytes\x18\x02 \x01(\x04R\n" +
	"freedBytes\x12+\n" +
	"\x11optimized_tensors\x18\x03 \x01(\rR\x10optimizedTensors\x12:\n" +
	"\ametrics\x18\x04 \x01(\v2 .tensor_cache.PerformanceMetricsR\ametrics\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\x8d\x02\n" +
	"\fCacheOptions\x12(\n" +
	"\x03ttl\x18\x01 \x01(\v2\x16.tensor_cache.DurationR\x03ttl\x12&\n" +
	"\x0fpersist_to_disk\x18\x02 \x01(\bR\rpersistToDisk\x12-\n" +
	"\x12enable_compression\x18\x03 \x01(\bR\x11enableCompression\x12H\n" +
	"\x10compression_type\x18\x04 \x01(\x0e2\x1d.tensor_cache.CompressionTypeR\x0fcompressionType\x122\n" +
	"\bpriority\x18\x05 \x01(\x0e2\x16.tensor_cache.PriorityR\bpriority\"\x89\x02\n" +
	"\x12PerformanceMetrics\x12*\n" +
	"\x11retrieval_time_ns\x18\x01 \x01(\x03R\x0fretrievalTimeNs\x12+\n" +
	"\x11bytes_transferred\x18\x02 \x01(\x04R\x10bytesTransferred\x12<\n" +
	"\vsource_tier\x18\x03 \x01(\x0e2\x1b.tensor_cache.CacheLocationR\n" +
	"sourceTier\x12\x1b\n" +
	"\tcache_hit\x18\x04 \x01(\bR\bcacheHit\x12\x19\n" +
	"\bhit_rate\x18\x05 \x01(\x02R\ahitRate\x12$\n" +
	"\x0elod_level_used\x18\x06 \x01(\x05R\flodLevelUsed\"\xde\x04\n" +
	"\fCacheMetrics\x12#\n" +
	"\rtotal_queries\x18\x01 \x01(\x04R\ftotalQueries\x12\x19\n" +
	"\bgpu_hits\x18\x02 \x01(\x04R\agpuHits\x12\x19\n" +
	"\bram_hits\x18\x03 \x01(\x04R\aramHits\x12\x1d\n" +
	"\n" +
	"redis_hits\x18\x04 \x01(\x04R\tredisHits\x12\x1b\n" +
	"\tmmap_hits\x18\x05 \x01(\x04R\bmmapHits\x12!\n" +
	"\fcache_misses\x18\x06 \x01(\x04R\vcacheMisses\x12(\n" +
	"\x10overall_hit_rate\x18\a \x01(\x02R\x0eoverallHitRate\x128\n" +
	"\n" +
	"gpu_memory\x18\b \x01(\v2\x19.tensor_cache.MemoryUsageR\tgpuMemory\x128\n" +
	"\n" +
	"ram_memory\x18\t \x01(\v2\x19.tensor_cache.MemoryUsageR\tramMemory\x12<\n" +
	"\fredis_memory\x18\n" +
	" \x01(\v2\x19.tensor_cache.MemoryUsageR\vredisMemory\x12:\n" +
	"\vdisk_memory\x18\v \x01(\v2\x19.tensor_cache.MemoryUsageR\n" +
	"diskMemory\x121\n" +
	"\x15avg_retrieval_time_ms\x18\f \x01(\x02R\x12avgRetrievalTimeMs\x12'\n" +
	"\x0ftotal_evictions\x18\r \x01(\x04R\x0etotalEvictions\x12 \n" +
	"\flast_gc_time\x18\x0e \x01(\x03R\n" +
	"lastGcTime\"\x92\x01\n" +
	"\vMemoryUsage\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x01 \x01(\x04R\tusedBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x04R\n" +
	"totalBytes\x12 \n" +
	"\vutilization\x18\x03 \x01(\x02R\vutilization\x12!\n" +
	"\fobject_count\x18\x04 \x01(\rR\vobjectCount\"\xca\x02\n" +
	"\rTensorMetrics\x12\x1b\n" +
	"\ttensor_id\x18\x01 \x01(\tR\btensorId\x12!\n" +
	"\faccess_count\x18\x02 \x01(\x04R\vaccessCount\x12#\n" +
	"\rlast_accessed\x18\x03 \x01(\x03R\flastAccessed\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x04R\tsizeBytes\x12F\n" +
	"\x10current_location\x18\x05 \x01(\x0e2\x1b.tensor_cache.CacheLocationR\x0fcurrentLocation\x12\x1f\n" +
	"\vcurrent_lod\x18\x06 \x01(\x05R\n" +
	"currentLod\x12L\n" +
	"\x13available_locations\x18\a \x03(\x0e2\x1b.tensor_cache.CacheLocationR\x12availableLocations\":\n" +
	"\bDuration\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x03R\aseconds\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\x05R\x05nanos\"\xaa\x01\n" +
	"\fWebGPUBuffer\x12\x1b\n" +
	"\tbuffer_id\x18\x01 \x01(\tR\bbufferId\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x122\n" +
	"\x05usage\x18\x03 \x01(\x0e2\x1c.tensor_cache.GPUBufferUsageR\x05usage\x12\x16\n" +
	"\x06mapped\x18\x04 \x01(\bR\x06mapped\x12\x1d\n" +
	"\n" +
	"tensor_ids\x18\x05 \x03(\tR\ttensorIds\"\x87\x01\n" +
	"\x0fGPUBufferLayout\x127\n" +
	"\bbindings\x18\x01 \x03(\v2\x1b.tensor_cache.BufferBindingR\bbindings\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x04R\ttotalSize\x12\x1c\n" +
	"\talignment\x18\x03 \x01(\rR\talignment\"r\n" +
	"\rBufferBinding\x12\x18\n" +
	"\abinding\x18\x01 \x01(\rR\abinding\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x1b\n" +
	"\ttensor_id\x18\x04 \x01(\tR\btensorId*\xfb\x01\n" +
	"\n" +
	"TensorType\x12\x17\n" +
	"\x13TENSOR_TYPE_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15TENSOR_TYPE_EMBEDDING\x10\x01\x12\x19\n" +
	"\x15TENSOR_TYPE_ATTENTION\x10\x02\x12\x1c\n" +
	"\x18TENSOR_TYPE_HIDDEN_STATE\x10\x03\x12\x16\n" +
	"\x12TENSOR_TYPE_LOGITS\x10\x04\x12\x18\n" +
	"\x14TENSOR_TYPE_KV_CACHE\x10\x05\x12\x18\n" +
	"\x14TENSOR_TYPE_GRADIENT\x10\x06\x12\x17\n" +
	"\x13TENSOR_TYPE_WEIGHTS\x10\a\x12\x1b\n" +
	"\x17TENSOR_TYPE_ACTIVATIONS\x10\b*\xb0\x01\n" +
	"\x0fCompressionType\x12\x14\n" +
	"\x10COMPRESSION_NONE\x10\x00\x12\x17\n" +
	"\x13COMPRESSION_FLOAT16\x10\x01\x12\x14\n" +
	"\x10COMPRESSION_INT8\x10\x02\x12\x14\n" +
	"\x10COMPRESSION_INT4\x10\x03\x12\x17\n" +
	"\x13COMPRESSION_HUFFMAN\x10\x04\x12\x13\n" +
	"\x0fCOMPRESSION_LZ4\x10\x05\x12\x14\n" +
	"\x10COMPRESSION_ZSTD\x10\x06*\x90\x01\n" +
	"\rCacheLocation\x12\x14\n" +
	"\x10LOCATION_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11LOCATION_GPU_VRAM\x10\x01\x12\x10\n" +
	"\fLOCATION_RAM\x10\x02\x12\x12\n" +
	"\x0eLOCATION_REDIS\x10\x03\x12\x11\n" +
	"\rLOCATION_MMAP\x10\x04\x12\x19\n" +
	"\x15LOCATION_COLD_STORAGE\x10\x05*[\n" +
	"\bPriority\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x00\x12\x13\n" +
	"\x0fPRIORITY_NORMAL\x10\x01\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x02\x12\x15\n" +
	"\x11PRIORITY_CRITICAL\x10\x03*\x98\x01\n" +
	"\x0eEvictionPolicy\x12\x10\n" +
	"\fEVICTION_LRU\x10\x00\x12\x10\n" +
	"\fEVICTION_LFU\x10\x01\x12\x11\n" +
	"\rEVICTION_FIFO\x10\x02\x12\x13\n" +
	"\x0fEVICTION_RANDOM\x10\x03\x12\x15\n" +
	"\x11EVICTION_PRIORITY\x10\x04\x12\x11\n" +
	"\rEVICTION_SIZE\x10\x05\x12\x10\n" +
	"\fEVICTION_AGE\x10\x06*\x82\x01\n" +
	"\x14OptimizationStrategy\x12\x11\n" +
	"\rOPTIMIZE_NONE\x10\x00\x12\x13\n" +
	"\x0fOPTIMIZE_MEMORY\x10\x01\x12\x12\n" +
	"\x0eOPTIMIZE_SPEED\x10\x02\x12\x15\n" +
	"\x11OPTIMIZE_BALANCED\x10\x03\x12\x17\n" +
	"\x13OPTIMIZE_AGGRESSIVE\x10\x04*\xb8\x01\n" +
	"\x0eGPUBufferUsage\x12\x15\n" +
	"\x11GPU_BUFFER_VERTEX\x10\x00\x12\x14\n" +
	"\x10GPU_BUFFER_INDEX\x10\x01\x12\x16\n" +
	"\x12GPU_BUFFER_UNIFORM\x10\x02\x12\x16\n" +
	"\x12GPU_BUFFER_STORAGE\x10\x03\x12\x17\n" +
	"\x13GPU_BUFFER_INDIRECT\x10\x04\x12\x17\n" +
	"\x13GPU_BUFFER_COPY_SRC\x10\x05\x12\x17\n" +
	"\x13GPU_BUFFER_COPY_DST\x10\x062\xec\x05\n" +
	"\x12TensorCacheService\x12R\n" +
	"\vStoreTensor\x12 .tensor_cache.StoreTensorRequest\x1a!.tensor_cache.StoreTensorResponse\x12L\n" +
	"\tGetTensor\x12\x1e.tensor_cache.GetTensorRequest\x1a\x1f.tensor_cache.GetTensorResponse\x12b\n" +
	"\x11BatchStoreTensors\x12%.tensor_cache.BatchStoreTensorRequest\x1a&.tensor_cache.BatchStoreTensorResponse\x12\\\n" +
	"\x0fBatchGetTensors\x12#.tensor_cache.BatchGetTensorRequest\x1a$.tensor_cache.BatchGetTensorResponse\x12U\n" +
	"\fEvictTensors\x12!.tensor_cache.EvictTensorsRequest\x1a\".tensor_cache.EvictTensorsResponse\x12^\n" +
	"\x0fGetCacheMetrics\x12$.tensor_cache.GetCacheMetricsRequest\x1a%.tensor_cache.GetCacheMetricsResponse\x12U\n" +
	"\fPromoteToGPU\x12!.tensor_cache.PromoteToGPURequest\x1a\".tensor_cache.PromoteToGPUResponse\x12d\n" +
	"\x11OptimizeGPUMemory\x12&.tensor_cache.OptimizeGPUMemoryRequest\x1a'.tensor_cache.OptimizeGPUMemoryResponseB\"Z github.com/legal-ai/proto/tensorb\x06proto3"

var (
	file_tensor_cache_proto_rawDescOnce sync.Once
	file_tensor_cache_proto_rawDescData []byte
)

func file_tensor_cache_proto_rawDescGZIP() []byte {
	file_tensor_cache_proto_rawDescOnce.Do(func() {
		file_tensor_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tensor_cache_proto_rawDesc), len(file_tensor_cache_proto_rawDesc)))
	})
	return file_tensor_cache_proto_rawDescData
}

var file_tensor_cache_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_tensor_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_tensor_cache_proto_goTypes = []any{
	(TensorType)(0),                   // 0: tensor_cache.TensorType
	(CompressionType)(0),              // 1: tensor_cache.CompressionType
	(CacheLocation)(0),                // 2: tensor_cache.CacheLocation
	(Priority)(0),                     // 3: tensor_cache.Priority
	(EvictionPolicy)(0),               // 4: tensor_cache.EvictionPolicy
	(OptimizationStrategy)(0),         // 5: tensor_cache.OptimizationStrategy
	(GPUBufferUsage)(0),               // 6: tensor_cache.GPUBufferUsage
	(*TensorCache)(nil),               // 7: tensor_cache.TensorCache
	(*TensorMetadata)(nil),            // 8: tensor_cache.TensorMetadata
	(*CompressionInfo)(nil),           // 9: tensor_cache.CompressionInfo
	(*StoreTensorRequest)(nil),        // 10: tensor_cache.StoreTensorRequest
	(*StoreTensorResponse)(nil),       // 11: tensor_cache.StoreTensorResponse
	(*GetTensorRequest)(nil),          // 12: tensor_cache.GetTensorRequest
	(*GetTensorResponse)(nil),         // 13: tensor_cache.GetTensorResponse
	(*BatchStoreTensorRequest)(nil),   // 14: tensor_cache.BatchStoreTensorRequest
	(*BatchStoreTensorResponse)(nil),  // 15: tensor_cache.BatchStoreTensorResponse
	(*BatchGetTensorRequest)(nil),     // 16: tensor_cache.BatchGetTensorRequest
	(*BatchGetTensorResponse)(nil),    // 17: tensor_cache.BatchGetTensorResponse
	(*EvictTensorsRequest)(nil),       // 18: tensor_cache.EvictTensorsRequest
	(*EvictTensorsResponse)(nil),      // 19: tensor_cache.EvictTensorsResponse
	(*GetCacheMetricsRequest)(nil),    // 20: tensor_cache.GetCacheMetricsRequest
	(*GetCacheMetricsResponse)(nil),   // 21: tensor_cache.GetCacheMetricsResponse
	(*PromoteToGPURequest)(nil),       // 22: tensor_cache.PromoteToGPURequest
	(*PromoteToGPUResponse)(nil),      // 23: tensor_cache.PromoteToGPUResponse
	(*OptimizeGPUMemoryRequest)(nil),  // 24: tensor_cache.OptimizeGPUMemoryRequest
	(*OptimizeGPUMemoryResponse)(nil), // 25: tensor_cache.OptimizeGPUMemoryResponse
	(*CacheOptions)(nil),              // 26: tensor_cache.CacheOptions
	(*PerformanceMetrics)(nil),        // 27: tensor_cache.PerformanceMetrics
	(*CacheMetrics)(nil),              // 28: tensor_cache.CacheMetrics
	(*MemoryUsage)(nil),               // 29: tensor_cache.MemoryUsage
	(*TensorMetrics)(nil),             // 30: tensor_cache.TensorMetrics
	(*Duration)(nil),                  // 31: tensor_cache.Duration
	(*WebGPUBuffer)(nil),              // 32: tensor_cache.WebGPUBuffer
	(*GPUBufferLayout)(nil),           // 33: tensor_cache.GPUBufferLayout
	(*BufferBinding)(nil),             // 34: tensor_cache.BufferBinding
}
var file_tensor_cache_proto_depIdxs = []int32{
	8,  // 0: tensor_cache.TensorCache.metadata:type_name -> tensor_cache.TensorMetadata
	9,  // 1: tensor_cache.TensorCache.compression:type_name -> tensor_cache.CompressionInfo
	0,  // 2: tensor_cache.TensorMetadata.tensor_type:type_name -> tensor_cache.TensorType
	3,  // 3: tensor_cache.TensorMetadata.priority:type_name -> tensor_cache.Priority
	1,  // 4: tensor_cache.CompressionInfo.type:type_name -> tensor_cache.CompressionType
	7,  // 5: tensor_cache.StoreTensorRequest.tensor:type_name -> tensor_cache.TensorCache
	26, // 6: tensor_cache.StoreTensorRequest.options:type_name -> tensor_cache.CacheOptions
	2,  // 7: tensor_cache.StoreTensorResponse.location:type_name -> tensor_cache.CacheLocation
	7,  // 8: tensor_cache.GetTensorResponse.tensor:type_name -> tensor_cache.TensorCache
	2,  // 9: tensor_cache.GetTensorResponse.source:type_name -> tensor_cache.CacheLocation
	27, // 10: tensor_cache.GetTensorResponse.metrics:type_name -> tensor_cache.PerformanceMetrics
	10, // 11: tensor_cache.BatchStoreTensorRequest.requests:type_name -> tensor_cache.StoreTensorRequest
	11, // 12: tensor_cache.BatchStoreTensorResponse.responses:type_name -> tensor_cache.StoreTensorResponse
	27, // 13: tensor_cache.BatchStoreTensorResponse.metrics:type_name -> tensor_cache.PerformanceMetrics
	12, // 14: tensor_cache.BatchGetTensorRequest.requests:type_name -> tensor_cache.GetTensorRequest
	13, // 15: tensor_cache.BatchGetTensorResponse.responses:type_name -> tensor_cache.GetTensorResponse
	27, // 16: tensor_cache.BatchGetTensorResponse.metrics:type_name -> tensor_cache.PerformanceMetrics
	4,  // 17: tensor_cache.EvictTensorsRequest.policy:type_name -> tensor_cache.EvictionPolicy
	2,  // 18: tensor_cache.EvictTensorsRequest.target_tier:type_name -> tensor_cache.CacheLocation
	28, // 19: tensor_cache.GetCacheMetricsResponse.metrics:type_name -> tensor_cache.CacheMetrics
	30, // 20: tensor_cache.GetCacheMetricsResponse.tensor_metrics:type_name -> tensor_cache.TensorMetrics
	5,  // 21: tensor_cache.OptimizeGPUMemoryRequest.strategy:type_name -> tensor_cache.OptimizationStrategy
	27, // 22: tensor_cache.OptimizeGPUMemoryResponse.metrics:type_name -> tensor_cache.PerformanceMetrics
	31, // 23: tensor_cache.CacheOptions.ttl:type_name -> tensor_cache.Duration
	1,  // 24: tensor_cache.CacheOptions.compression_type:type_name -> tensor_cache.CompressionType
	3,  // 25: tensor_cache.CacheOptions.priority:type_name -> tensor_cache.Priority
	2,  // 26: tensor_cache.PerformanceMetrics.source_tier:type_name -> tensor_cache.CacheLocation
	29, // 27: tensor_cache.CacheMetrics.gpu_memory:type_name -> tensor_cache.MemoryUsage
	29, // 28: tensor_cache.CacheMetrics.ram_memory:type_name -> tensor_cache.MemoryUsage
	29, // 29: tensor_cache.CacheMetrics.redis_memory:type_name -> tensor_cache.MemoryUsage
	29, // 30: tensor_cache.CacheMetrics.disk_memory:type_name -> tensor_cache.MemoryUsage
	2,  // 31: tensor_cache.TensorMetrics.current_location:type_name -> tensor_cache.CacheLocation
	2,  // 32: tensor_cache.TensorMetrics.available_locations:type_name -> tensor_cache.CacheLocation
	6,  // 33: tensor_cache.WebGPUBuffer.usage:type_name -> tensor_cache.GPUBufferUsage
	34, // 34: tensor_cache.GPUBufferLayout.bindings:type_name -> tensor_cache.BufferBinding
	10, // 35: tensor_cache.TensorCacheService.StoreTensor:input_type -> tensor_cache.StoreTensorRequest
	12, // 36: tensor_cache.TensorCacheService.GetTensor:input_type -> tensor_cache.GetTensorRequest
	14, // 37: tensor_cache.TensorCacheService.BatchStoreTensors:input_type -> tensor_cache.BatchStoreTensorRequest
	16, // 38: tensor_cache.TensorCacheService.BatchGetTensors:input_type -> tensor_cache.BatchGetTensorRequest
	18, // 39: tensor_cache.TensorCacheService.EvictTensors:input_type -> tensor_cache.EvictTensorsRequest
	20, // 40: tensor_cache.TensorCacheService.GetCacheMetrics:input_type -> tensor_cache.GetCacheMetricsRequest
	22, // 41: tensor_cache.TensorCacheService.PromoteToGPU:input_type -> tensor_cache.PromoteToGPURequest
	24, // 42: tensor_cache.TensorCacheService.OptimizeGPUMemory:input_type -> tensor_cache.OptimizeGPUMemoryRequest
	11, // 43: tensor_cache.TensorCacheService.StoreTensor:output_type -> tensor_cache.StoreTensorResponse
	13, // 44: tensor_cache.TensorCacheService.GetTensor:output_type -> tensor_cache.GetTensorResponse
	15, // 45: tensor_cache.TensorCacheService.BatchStoreTensors:output_type -> tensor_cache.BatchStoreTensorResponse
	17, // 46: tensor_cache.TensorCacheService.BatchGetTensors:output_type -> tensor_cache.BatchGetTensorResponse
	19, // 47: tensor_cache.TensorCacheService.EvictTensors:output_type -> tensor_cache.EvictTensorsResponse
	21, // 48: tensor_cache.TensorCacheService.GetCacheMetrics:output_type -> tensor_cache.GetCacheMetricsResponse
	23, // 49: tensor_cache.TensorCacheService.PromoteToGPU:output_type -> tensor_cache.PromoteToGPUResponse
	25, // 50: tensor_cache.TensorCacheService.OptimizeGPUMemory:output_type -> tensor_cache.OptimizeGPUMemoryResponse
	43, // [43:51] is the sub-list for method output_type
	35, // [35:43] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_tensor_cache_proto_init() }
func file_tensor_cache_proto_init() {
	if File_tensor_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tensor_cache_proto_rawDesc), len(file_tensor_cache_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tensor_cache_proto_goTypes,
		DependencyIndexes: file_tensor_cache_proto_depIdxs,
		EnumInfos:         file_tensor_cache_proto_enumTypes,
		MessageInfos:      file_tensor_cache_proto_msgTypes,
	}.Build()
	File_tensor_cache_proto = out.File
	file_tensor_cache_proto_goTypes = nil
	file_tensor_cache_proto_depIdxs = nil
}
