// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: tensor_cache.proto

package tensor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TensorCacheService_StoreTensor_FullMethodName       = "/tensor_cache.TensorCacheService/StoreTensor"
	TensorCacheService_GetTensor_FullMethodName         = "/tensor_cache.TensorCacheService/GetTensor"
	TensorCacheService_BatchStoreTensors_FullMethodName = "/tensor_cache.TensorCacheService/BatchStoreTensors"
	TensorCacheService_BatchGetTensors_FullMethodName   = "/tensor_cache.TensorCacheService/BatchGetTensors"
	TensorCacheService_EvictTensors_FullMethodName      = "/tensor_cache.TensorCacheService/EvictTensors"
	TensorCacheService_GetCacheMetrics_FullMethodName   = "/tensor_cache.TensorCacheService/GetCacheMetrics"
	TensorCacheService_PromoteToGPU_FullMethodName      = "/tensor_cache.TensorCacheService/PromoteToGPU"
	TensorCacheService_OptimizeGPUMemory_FullMethodName = "/tensor_cache.TensorCacheService/OptimizeGPUMemory"
)

// TensorCacheServiceClient is the client API for TensorCacheService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Tensor Cache Service for GPU-aware multi-tier storage
type TensorCacheServiceClient interface {
	// Store tensor with automatic LoD generation
	StoreTensor(ctx context.Context, in *StoreTensorRequest, opts ...grpc.CallOption) (*StoreTensorResponse, error)
	// Retrieve tensor from multi-tier cache
	GetTensor(ctx context.Context, in *GetTensorRequest, opts ...grpc.CallOption) (*GetTensorResponse, error)
	// Batch operations for efficiency
	BatchStoreTensors(ctx context.Context, in *BatchStoreTensorRequest, opts ...grpc.CallOption) (*BatchStoreTensorResponse, error)
	BatchGetTensors(ctx context.Context, in *BatchGetTensorRequest, opts ...grpc.CallOption) (*BatchGetTensorResponse, error)
	// Memory management
	EvictTensors(ctx context.Context, in *EvictTensorsRequest, opts ...grpc.CallOption) (*EvictTensorsResponse, error)
	GetCacheMetrics(ctx context.Context, in *GetCacheMetricsRequest, opts ...grpc.CallOption) (*GetCacheMetricsResponse, error)
	// GPU buffer operations
	PromoteToGPU(ctx context.Context, in *PromoteToGPURequest, opts ...grpc.CallOption) (*PromoteToGPUResponse, error)
	OptimizeGPUMemory(ctx context.Context, in *OptimizeGPUMemoryRequest, opts ...grpc.CallOption) (*OptimizeGPUMemoryResponse, error)
}

type tensorCacheServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTensorCacheServiceClient(cc grpc.ClientConnInterface) TensorCacheServiceClient {
	return &tensorCacheServiceClient{cc}
}

func (c *tensorCacheServiceClient) StoreTensor(ctx context.Context, in *StoreTensorRequest, opts ...grpc.CallOption) (*StoreTensorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreTensorResponse)
	err := c.cc.Invoke(ctx, TensorCacheService_StoreTensor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tensorCacheServiceClient) GetTensor(ctx context.Context, in *GetTensorRequest, opts ...grpc.CallOption) (*GetTensorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTensorResponse)
	err := c.cc.Invoke(ctx, TensorCacheService_GetTensor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tensorCacheServiceClient) BatchStoreTensors(ctx context.Context, in *BatchStoreTensorRequest, opts ...grpc.CallOption) (*BatchStoreTensorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchStoreTensorResponse)
	err := c.cc.Invoke(ctx, TensorCacheService_BatchStoreTensors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tensorCacheServiceClient) BatchGetTensors(ctx context.Context, in *BatchGetTensorRequest, opts ...grpc.CallOption) (*BatchGetTensorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetTensorResponse)
	err := c.cc.Invoke(ctx, TensorCacheService_BatchGetTensors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tensorCacheServiceClient) EvictTensors(ctx context.Context, in *EvictTensorsRequest, opts ...grpc.CallOption) (*EvictTensorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvictTensorsResponse)
	err := c.cc.Invoke(ctx, TensorCacheService_EvictTensors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tensorCacheServiceClient) GetCacheMetrics(ctx context.Context, in *GetCacheMetricsRequest, opts ...grpc.CallOption) (*GetCacheMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCacheMetricsResponse)
	err := c.cc.Invoke(ctx, TensorCacheService_GetCacheMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tensorCacheServiceClient) PromoteToGPU(ctx context.Context, in *PromoteToGPURequest, opts ...grpc.CallOption) (*PromoteToGPUResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromoteToGPUResponse)
	err := c.cc.Invoke(ctx, TensorCacheService_PromoteToGPU_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tensorCacheServiceClient) OptimizeGPUMemory(ctx context.Context, in *OptimizeGPUMemoryRequest, opts ...grpc.CallOption) (*OptimizeGPUMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OptimizeGPUMemoryResponse)
	err := c.cc.Invoke(ctx, TensorCacheService_OptimizeGPUMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TensorCacheServiceServer is the server API for TensorCacheService service.
// All implementations must embed UnimplementedTensorCacheServiceServer
// for forward compatibility.
//
// Tensor Cache Service for GPU-aware multi-tier storage
type TensorCacheServiceServer interface {
	// Store tensor with automatic LoD generation
	StoreTensor(context.Context, *StoreTensorRequest) (*StoreTensorResponse, error)
	// Retrieve tensor from multi-tier cache
	GetTensor(context.Context, *GetTensorRequest) (*GetTensorResponse, error)
	// Batch operations for efficiency
	BatchStoreTensors(context.Context, *BatchStoreTensorRequest) (*BatchStoreTensorResponse, error)
	BatchGetTensors(context.Context, *BatchGetTensorRequest) (*BatchGetTensorResponse, error)
	// Memory management
	EvictTensors(context.Context, *EvictTensorsRequest) (*EvictTensorsResponse, error)
	GetCacheMetrics(context.Context, *GetCacheMetricsRequest) (*GetCacheMetricsResponse, error)
	// GPU buffer operations
	PromoteToGPU(context.Context, *PromoteToGPURequest) (*PromoteToGPUResponse, error)
	OptimizeGPUMemory(context.Context, *OptimizeGPUMemoryRequest) (*OptimizeGPUMemoryResponse, error)
	mustEmbedUnimplementedTensorCacheServiceServer()
}

// UnimplementedTensorCacheServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTensorCacheServiceServer struct{}

func (UnimplementedTensorCacheServiceServer) StoreTensor(context.Context, *StoreTensorRequest) (*StoreTensorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreTensor not implemented")
}
func (UnimplementedTensorCacheServiceServer) GetTensor(context.Context, *GetTensorRequest) (*GetTensorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTensor not implemented")
}
func (UnimplementedTensorCacheServiceServer) BatchStoreTensors(context.Context, *BatchStoreTensorRequest) (*BatchStoreTensorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchStoreTensors not implemented")
}
func (UnimplementedTensorCacheServiceServer) BatchGetTensors(context.Context, *BatchGetTensorRequest) (*BatchGetTensorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetTensors not implemented")
}
func (UnimplementedTensorCacheServiceServer) EvictTensors(context.Context, *EvictTensorsRequest) (*EvictTensorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvictTensors not implemented")
}
func (UnimplementedTensorCacheServiceServer) GetCacheMetrics(context.Context, *GetCacheMetricsRequest) (*GetCacheMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCacheMetrics not implemented")
}
func (UnimplementedTensorCacheServiceServer) PromoteToGPU(context.Context, *PromoteToGPURequest) (*PromoteToGPUResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PromoteToGPU not implemented")
}
func (UnimplementedTensorCacheServiceServer) OptimizeGPUMemory(context.Context, *OptimizeGPUMemoryRequest) (*OptimizeGPUMemoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OptimizeGPUMemory not implemented")
}
func (UnimplementedTensorCacheServiceServer) mustEmbedUnimplementedTensorCacheServiceServer() {}
func (UnimplementedTensorCacheServiceServer) testEmbeddedByValue()                            {}

// UnsafeTensorCacheServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TensorCacheServiceServer will
// result in compilation errors.
type UnsafeTensorCacheServiceServer interface {
	mustEmbedUnimplementedTensorCacheServiceServer()
}

func RegisterTensorCacheServiceServer(s grpc.ServiceRegistrar, srv TensorCacheServiceServer) {
	// If the following call pancis, it indicates UnimplementedTensorCacheServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TensorCacheService_ServiceDesc, srv)
}

func _TensorCacheService_StoreTensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreTensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TensorCacheServiceServer).StoreTensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TensorCacheService_StoreTensor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TensorCacheServiceServer).StoreTensor(ctx, req.(*StoreTensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TensorCacheService_GetTensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TensorCacheServiceServer).GetTensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TensorCacheService_GetTensor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TensorCacheServiceServer).GetTensor(ctx, req.(*GetTensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TensorCacheService_BatchStoreTensors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchStoreTensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TensorCacheServiceServer).BatchStoreTensors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TensorCacheService_BatchStoreTensors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TensorCacheServiceServer).BatchStoreTensors(ctx, req.(*BatchStoreTensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TensorCacheService_BatchGetTensors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetTensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TensorCacheServiceServer).BatchGetTensors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TensorCacheService_BatchGetTensors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TensorCacheServiceServer).BatchGetTensors(ctx, req.(*BatchGetTensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TensorCacheService_EvictTensors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvictTensorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TensorCacheServiceServer).EvictTensors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TensorCacheService_EvictTensors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TensorCacheServiceServer).EvictTensors(ctx, req.(*EvictTensorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TensorCacheService_GetCacheMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCacheMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TensorCacheServiceServer).GetCacheMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TensorCacheService_GetCacheMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TensorCacheServiceServer).GetCacheMetrics(ctx, req.(*GetCacheMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TensorCacheService_PromoteToGPU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoteToGPURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TensorCacheServiceServer).PromoteToGPU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TensorCacheService_PromoteToGPU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TensorCacheServiceServer).PromoteToGPU(ctx, req.(*PromoteToGPURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TensorCacheService_OptimizeGPUMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptimizeGPUMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TensorCacheServiceServer).OptimizeGPUMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TensorCacheService_OptimizeGPUMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TensorCacheServiceServer).OptimizeGPUMemory(ctx, req.(*OptimizeGPUMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TensorCacheService_ServiceDesc is the grpc.ServiceDesc for TensorCacheService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TensorCacheService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tensor_cache.TensorCacheService",
	HandlerType: (*TensorCacheServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreTensor",
			Handler:    _TensorCacheService_StoreTensor_Handler,
		},
		{
			MethodName: "GetTensor",
			Handler:    _TensorCacheService_GetTensor_Handler,
		},
		{
			MethodName: "BatchStoreTensors",
			Handler:    _TensorCacheService_BatchStoreTensors_Handler,
		},
		{
			MethodName: "BatchGetTensors",
			Handler:    _TensorCacheService_BatchGetTensors_Handler,
		},
		{
			MethodName: "EvictTensors",
			Handler:    _TensorCacheService_EvictTensors_Handler,
		},
		{
			MethodName: "GetCacheMetrics",
			Handler:    _TensorCacheService_GetCacheMetrics_Handler,
		},
		{
			MethodName: "PromoteToGPU",
			Handler:    _TensorCacheService_PromoteToGPU_Handler,
		},
		{
			MethodName: "OptimizeGPUMemory",
			Handler:    _TensorCacheService_OptimizeGPUMemory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tensor_cache.proto",
}
