// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.23.4
// source: gpu_service.proto

package gpu

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessingStatus int32

const (
	ProcessingStatus_QUEUED     ProcessingStatus = 0
	ProcessingStatus_PROCESSING ProcessingStatus = 1
	ProcessingStatus_COMPLETED  ProcessingStatus = 2
	ProcessingStatus_FAILED     ProcessingStatus = 3
	ProcessingStatus_CANCELLED  ProcessingStatus = 4
)

// Enum value maps for ProcessingStatus.
var (
	ProcessingStatus_name = map[int32]string{
		0: "QUEUED",
		1: "PROCESSING",
		2: "COMPLETED",
		3: "FAILED",
		4: "CANCELLED",
	}
	ProcessingStatus_value = map[string]int32{
		"QUEUED":     0,
		"PROCESSING": 1,
		"COMPLETED":  2,
		"FAILED":     3,
		"CANCELLED":  4,
	}
)

func (x ProcessingStatus) Enum() *ProcessingStatus {
	p := new(ProcessingStatus)
	*p = x
	return p
}

func (x ProcessingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_gpu_service_proto_enumTypes[0].Descriptor()
}

func (ProcessingStatus) Type() protoreflect.EnumType {
	return &file_gpu_service_proto_enumTypes[0]
}

func (x ProcessingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessingStatus.Descriptor instead.
func (ProcessingStatus) EnumDescriptor() ([]byte, []int) {
	return file_gpu_service_proto_rawDescGZIP(), []int{0}
}

type RecommendationType int32

const (
	RecommendationType_DOCUMENTS       RecommendationType = 0
	RecommendationType_CASES           RecommendationType = 1
	RecommendationType_LEGAL_CONCEPTS  RecommendationType = 2
	RecommendationType_SIMILAR_QUERIES RecommendationType = 3
)

// Enum value maps for RecommendationType.
var (
	RecommendationType_name = map[int32]string{
		0: "DOCUMENTS",
		1: "CASES",
		2: "LEGAL_CONCEPTS",
		3: "SIMILAR_QUERIES",
	}
	RecommendationType_value = map[string]int32{
		"DOCUMENTS":       0,
		"CASES":           1,
		"LEGAL_CONCEPTS":  2,
		"SIMILAR_QUERIES": 3,
	}
)

func (x RecommendationType) Enum() *RecommendationType {
	p := new(RecommendationType)
	*p = x
	return p
}

func (x RecommendationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecommendationType) Descriptor() protoreflect.EnumDescriptor {
	return file_gpu_service_proto_enumTypes[1].Descriptor()
}

func (RecommendationType) Type() protoreflect.EnumType {
	return &file_gpu_service_proto_enumTypes[1]
}

func (x RecommendationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecommendationType.Descriptor instead.
func (RecommendationType) EnumDescriptor() ([]byte, []int) {
	return file_gpu_service_proto_rawDescGZIP(), []int{1}
}

// Core data types for embeddings and chunks
type EmbeddingVector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`               // 384-dim nomic-embed or custom dimensions
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"` // "nomic-embed-text-v1.5", etc
	Dimensions    int32                  `protobuf:"varint,3,opt,name=dimensions,proto3" json:"dimensions,omitempty"`               // vector dimensions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingVector) Reset() {
	*x = EmbeddingVector{}
	mi := &file_gpu_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingVector) ProtoMessage() {}

func (x *EmbeddingVector) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingVector.ProtoReflect.Descriptor instead.
func (*EmbeddingVector) Descriptor() ([]byte, []int) {
	return file_gpu_service_proto_rawDescGZIP(), []int{0}
}

func (x *EmbeddingVector) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *EmbeddingVector) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *EmbeddingVector) GetDimensions() int32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

type TextChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`                                                                             // UTF-8 text content
	ChunkIndex    int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`                                                    // position in document
	DocumentId    string                 `protobuf:"bytes,3,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`                                                     // source document ID
	CaseId        string                 `protobuf:"bytes,4,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`                                                                 // optional case grouping
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // additional context
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextChunk) Reset() {
	*x = TextChunk{}
	mi := &file_gpu_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextChunk) ProtoMessage() {}

func (x *TextChunk) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextChunk.ProtoReflect.Descriptor instead.
func (*TextChunk) Descriptor() ([]byte, []int) {
	return file_gpu_service_proto_rawDescGZIP(), []int{1}
}

func (x *TextChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TextChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *TextChunk) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *TextChunk) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *TextChunk) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// GPU processing data containers
type DataChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*DataChunk_Utf8Bytes
	//	*DataChunk_Embedding
	//	*DataChunk_JsonData
	Data          isDataChunk_Data `protobuf_oneof:"data"`
	SequenceId    int32            `protobuf:"varint,4,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`         // Order in stream
	IsFinal       bool             `protobuf:"varint,5,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`                  // Last chunk indicator
	OperationType string           `protobuf:"bytes,6,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"` // "embed", "cluster", "search", "rank"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataChunk) Reset() {
	*x = DataChunk{}
	mi := &file_gpu_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataChunk) ProtoMessage() {}

func (x *DataChunk) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataChunk.ProtoReflect.Descriptor instead.
func (*DataChunk) Descriptor() ([]byte, []int) {
	return file_gpu_service_proto_rawDescGZIP(), []int{2}
}

func (x *DataChunk) GetData() isDataChunk_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataChunk) GetUtf8Bytes() []byte {
	if x != nil {
		if x, ok := x.Data.(*DataChunk_Utf8Bytes); ok {
			return x.Utf8Bytes
		}
	}
	return nil
}

func (x *DataChunk) GetEmbedding() *EmbeddingVector {
	if x != nil {
		if x, ok := x.Data.(*DataChunk_Embedding); ok {
			return x.Embedding
		}
	}
	return nil
}

func (x *DataChunk) GetJsonData() string {
	if x != nil {
		if x, ok := x.Data.(*DataChunk_JsonData); ok {
			return x.JsonData
		}
	}
	return ""
}

func (x *DataChunk) GetSequenceId() int32 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

func (x *DataChunk) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *DataChunk) GetOperationType() string {
	if x != nil {
		return x.OperationType
	}
	return ""
}

type isDataChunk_Data interface {
	isDataChunk_Data()
}

type DataChunk_Utf8Bytes struct {
	Utf8Bytes []byte `protobuf:"bytes,1,opt,name=utf8_bytes,json=utf8Bytes,proto3,oneof"` // Raw UTF-8 encoded text
}

type DataChunk_Embedding struct {
	Embedding *EmbeddingVector `protobuf:"bytes,2,opt,name=embedding,proto3,oneof"` // Float vector embedding
}

type DataChunk_JsonData struct {
	JsonData string `protobuf:"bytes,3,opt,name=json_data,json=jsonData,proto3,oneof"` // JSON string for SIMD parsing
}

func (*DataChunk_Utf8Bytes) isDataChunk_Data() {}

func (*DataChunk_Embedding) isDataChunk_Data() {}

func (*DataChunk_JsonData) isDataChunk_Data() {}

// Semantic processing requests
type SemanticRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Client session identifier
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`                  // "embed_text", "cluster_vectors", "semantic_search", "rank_results"
	TextChunks    []*TextChunk           `protobuf:"bytes,3,rep,name=text_chunks,json=textChunks,proto3" json:"text_chunks,omitempty"`
	Embeddings    []*EmbeddingVector     `protobuf:"bytes,4,rep,name=embeddings,proto3" json:"embeddings,omitempty"`
	Options       *ProcessingOptions     `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticRequest) Reset() {
	*x = SemanticRequest{}
	mi := &file_gpu_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticRequest) ProtoMessage() {}

func (x *SemanticRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticRequest.ProtoReflect.Descriptor instead.
func (*SemanticRequest) Descriptor() ([]byte, []int) {
	return file_gpu_service_proto_rawDescGZIP(), []int{3}
}

func (x *SemanticRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SemanticRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *SemanticRequest) GetTextChunks() []*TextChunk {
	if x != nil {
		return x.TextChunks
	}
	return nil
}

func (x *SemanticRequest) GetEmbeddings() []*EmbeddingVector {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

func (x *SemanticRequest) GetOptions() *ProcessingOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ProcessingOptions struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	UseGpuAcceleration          bool                   `protobuf:"varint,1,opt,name=use_gpu_acceleration,json=useGpuAcceleration,proto3" json:"use_gpu_acceleration,omitempty"`                            // Enable WebGPU/CUDA
	EnableCaching               bool                   `protobuf:"varint,2,opt,name=enable_caching,json=enableCaching,proto3" json:"enable_caching,omitempty"`                                             // Use shader/result caching
	MaxConcurrency              int32                  `protobuf:"varint,3,opt,name=max_concurrency,json=maxConcurrency,proto3" json:"max_concurrency,omitempty"`                                          // Parallel processing limit
	ClusteringAlgorithm         string                 `protobuf:"bytes,4,opt,name=clustering_algorithm,json=clusteringAlgorithm,proto3" json:"clustering_algorithm,omitempty"`                            // "kmeans", "som", "dbscan"
	SimilarityThreshold         float32                `protobuf:"fixed32,5,opt,name=similarity_threshold,json=similarityThreshold,proto3" json:"similarity_threshold,omitempty"`                          // For clustering/search
	EnableReinforcementLearning bool                   `protobuf:"varint,6,opt,name=enable_reinforcement_learning,json=enableReinforcementLearning,proto3" json:"enable_reinforcement_learning,omitempty"` // Learning system
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ProcessingOptions) Reset() {
	*x = ProcessingOptions{}
	mi := &file_gpu_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingOptions) ProtoMessage() {}

func (x *ProcessingOptions) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingOptions.ProtoReflect.Descriptor instead.
func (*ProcessingOptions) Descriptor() ([]byte, []int) {
	return file_gpu_service_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessingOptions) GetUseGpuAcceleration() bool {
	if x != nil {
		return x.UseGpuAcceleration
	}
	return false
}

func (x *ProcessingOptions) GetEnableCaching() bool {
	if x != nil {
		return x.EnableCaching
	}
	return false
}

func (x *ProcessingOptions) GetMaxConcurrency() int32 {
	if x != nil {
		return x.MaxConcurrency
	}
	return 0
}

func (x *ProcessingOptions) GetClusteringAlgorithm() string {
	if x != nil {
		return x.ClusteringAlgorithm
	}
	return ""
}

func (x *ProcessingOptions) GetSimilarityThreshold() float32 {
	if x != nil {
		return x.SimilarityThreshold
	}
	return 0
}

func (x *ProcessingOptions) GetEnableReinforcementLearning() bool {
	if x != nil {
		return x.EnableReinforcementLearning
	}
	return false
}

// GPU processing results
type ProcessingResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Operation        string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Status           ProcessingStatus       `protobuf:"varint,3,opt,name=status,proto3,enum=gpu_rag_system.ProcessingStatus" json:"status,omitempty"`
	ResultEmbeddings []*EmbeddingVector     `protobuf:"bytes,4,rep,name=result_embeddings,json=resultEmbeddings,proto3" json:"result_embeddings,omitempty"`
	Clusters         []*ClusterInfo         `protobuf:"bytes,5,rep,name=clusters,proto3" json:"clusters,omitempty"`
	SearchResults    []*SearchResult        `protobuf:"bytes,6,rep,name=search_results,json=searchResults,proto3" json:"search_results,omitempty"`
	Performance      *PerformanceMetrics    `protobuf:"bytes,7,opt,name=performance,proto3" json:"performance,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProcessingResult) Reset() {
	*x = ProcessingResult{}
	mi := &file_gpu_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingResult) ProtoMessage() {}

func (x *ProcessingResult) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingResult.ProtoReflect.Descriptor instead.
func (*ProcessingResult) Descriptor() ([]byte, []int) {
	return file_gpu_service_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessingResult) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProcessingResult) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ProcessingResult) GetStatus() ProcessingStatus {
	if x != nil {
		return x.Status
	}
	return ProcessingStatus_QUEUED
}

func (x *ProcessingResult) GetResultEmbeddings() []*EmbeddingVector {
	if x != nil {
		return x.ResultEmbeddings
	}
	return nil
}

func (x *ProcessingResult) GetClusters() []*ClusterInfo {
	if x != nil {
		return x.Clusters
	}
	return nil
}

func (x *ProcessingResult) GetSearchResults() []*SearchResult {
	if x != nil {
		return x.SearchResults
	}
	return nil
}

func (x *ProcessingResult) GetPerformance() *PerformanceMetrics {
	if x != nil {
		return x.Performance
	}
	return nil
}

func (x *ProcessingResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ClusterInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     int32                  `protobuf:"varint,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Centroid      *EmbeddingVector       `protobuf:"bytes,2,opt,name=centroid,proto3" json:"centroid,omitempty"`
	MemberIndices []int32                `protobuf:"varint,3,rep,packed,name=member_indices,json=memberIndices,proto3" json:"member_indices,omitempty"`
	Inertia       float32                `protobuf:"fixed32,4,opt,name=inertia,proto3" json:"inertia,omitempty"` // Clustering quality metric
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterInfo) Reset() {
	*x = ClusterInfo{}
	mi := &file_gpu_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterInfo) ProtoMessage() {}

func (x *ClusterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterInfo.ProtoReflect.Descriptor instead.
func (*ClusterInfo) Descriptor() ([]byte, []int) {
	return file_gpu_service_proto_rawDescGZIP(), []int{6}
}

func (x *ClusterInfo) GetClusterId() int32 {
	if x != nil {
		return x.ClusterId
	}
	return 0
}

func (x *ClusterInfo) GetCentroid() *EmbeddingVector {
	if x != nil {
		return x.Centroid
	}
	return nil
}

func (x *ClusterInfo) GetMemberIndices() []int32 {
	if x != nil {
		return x.MemberIndices
	}
	return nil
}

func (x *ClusterInfo) GetInertia() float32 {
	if x != nil {
		return x.Inertia
	}
	return 0
}

type SearchResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DocumentId      string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	SimilarityScore float32                `protobuf:"fixed32,2,opt,name=similarity_score,json=similarityScore,proto3" json:"similarity_score,omitempty"`
	Embedding       *EmbeddingVector       `protobuf:"bytes,3,opt,name=embedding,proto3" json:"embedding,omitempty"`
	Snippet         string                 `protobuf:"bytes,4,opt,name=snippet,proto3" json:"snippet,omitempty"` // Text preview
	Metadata        map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_gpu_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_gpu_service_proto_rawDescGZIP(), []int{7}
}

func (x *SearchResult) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *SearchResult) GetSimilarityScore() float32 {
	if x != nil {
		return x.SimilarityScore
	}
	return 0
}

func (x *SearchResult) GetEmbedding() *EmbeddingVector {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *SearchResult) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *SearchResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PerformanceMetrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProcessingTimeMs int64                  `protobuf:"varint,1,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	GpuComputeTimeMs int64                  `protobuf:"varint,2,opt,name=gpu_compute_time_ms,json=gpuComputeTimeMs,proto3" json:"gpu_compute_time_ms,omitempty"`
	CacheHits        int32                  `protobuf:"varint,3,opt,name=cache_hits,json=cacheHits,proto3" json:"cache_hits,omitempty"`
	CacheMisses      int32                  `protobuf:"varint,4,opt,name=cache_misses,json=cacheMisses,proto3" json:"cache_misses,omitempty"`
	GpuUtilization   float32                `protobuf:"fixed32,5,opt,name=gpu_utilization,json=gpuUtilization,proto3" json:"gpu_utilization,omitempty"` // 0.0 to 1.0
	MemoryUsedBytes  int64                  `protobuf:"varint,6,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PerformanceMetrics) Reset() {
	*x = PerformanceMetrics{}
	mi := &file_gpu_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformanceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformanceMetrics) ProtoMessage() {}

func (x *PerformanceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformanceMetrics.ProtoReflect.Descriptor instead.
func (*PerformanceMetrics) Descriptor() ([]byte, []int) {
	return file_gpu_service_proto_rawDescGZIP(), []int{8}
}

func (x *PerformanceMetrics) GetProcessingTimeMs() int64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

func (x *PerformanceMetrics) GetGpuComputeTimeMs() int64 {
	if x != nil {
		return x.GpuComputeTimeMs
	}
	return 0
}

func (x *PerformanceMetrics) GetCacheHits() int32 {
	if x != nil {
		return x.CacheHits
	}
	return 0
}

func (x *PerformanceMetrics) GetCacheMisses() int32 {
	if x != nil {
		return x.CacheMisses
	}
	return 0
}

func (x *PerformanceMetrics) GetGpuUtilization() float32 {
	if x != nil {
		return x.GpuUtilization
	}
	return 0
}

func (x *PerformanceMetrics) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

// Enhanced RAG pipeline requests
type RAGRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`                 // User query text
	CaseId        string                 `protobuf:"bytes,2,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"` // Optional case context
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // For personalization
	Options       *RAGOptions            `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAGRequest) Reset() {
	*x = RAGRequest{}
	mi := &file_gpu_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGRequest) ProtoMessage() {}

func (x *RAGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGRequest.ProtoReflect.Descriptor instead.
func (*RAGRequest) Descriptor() ([]byte, []int) {
	return file_gpu_service_proto_rawDescGZIP(), []int{9}
}

func (x *RAGRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RAGRequest) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *RAGRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RAGRequest) GetOptions() *RAGOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type RAGOptions struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TopK               int32                  `protobuf:"varint,1,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`                                             // Number of results
	EnableHybridSearch bool                   `protobuf:"varint,2,opt,name=enable_hybrid_search,json=enableHybridSearch,proto3" json:"enable_hybrid_search,omitempty"` // Vector + text search
	EnableReranking    bool                   `protobuf:"varint,3,opt,name=enable_reranking,json=enableReranking,proto3" json:"enable_reranking,omitempty"`            // Advanced result ranking
	EnableCompression  bool                   `protobuf:"varint,4,opt,name=enable_compression,json=enableCompression,proto3" json:"enable_compression,omitempty"`      // Context compression
	DiversityThreshold float32                `protobuf:"fixed32,5,opt,name=diversity_threshold,json=diversityThreshold,proto3" json:"diversity_threshold,omitempty"`  // Result diversity
	Filters            []string               `protobuf:"bytes,6,rep,name=filters,proto3" json:"filters,omitempty"`                                                    // Metadata filters
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RAGOptions) Reset() {
	*x = RAGOptions{}
	mi := &file_gpu_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGOptions) ProtoMessage() {}

func (x *RAGOptions) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGOptions.ProtoReflect.Descriptor instead.
func (*RAGOptions) Descriptor() ([]byte, []int) {
	return file_gpu_service_proto_rawDescGZIP(), []int{10}
}

func (x *RAGOptions) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *RAGOptions) GetEnableHybridSearch() bool {
	if x != nil {
		return x.EnableHybridSearch
	}
	return false
}

func (x *RAGOptions) GetEnableReranking() bool {
	if x != nil {
		return x.EnableReranking
	}
	return false
}

func (x *RAGOptions) GetEnableCompression() bool {
	if x != nil {
		return x.EnableCompression
	}
	return false
}

func (x *RAGOptions) GetDiversityThreshold() float32 {
	if x != nil {
		return x.DiversityThreshold
	}
	return 0
}

func (x *RAGOptions) GetFilters() []string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type RAGResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`   // Generated response
	Sources       []*SearchResult        `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"` // Source documents
	Context       string                 `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"` // Used context
	Performance   *PerformanceMetrics    `protobuf:"bytes,5,opt,name=performance,proto3" json:"performance,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAGResponse) Reset() {
	*x = RAGResponse{}
	mi := &file_gpu_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGResponse) ProtoMessage() {}

func (x *RAGResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGResponse.ProtoReflect.Descriptor instead.
func (*RAGResponse) Descriptor() ([]byte, []int) {
	return file_gpu_service_proto_rawDescGZIP(), []int{11}
}

func (x *RAGResponse) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RAGResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *RAGResponse) GetSources() []*SearchResult {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *RAGResponse) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *RAGResponse) GetPerformance() *PerformanceMetrics {
	if x != nil {
		return x.Performance
	}
	return nil
}

func (x *RAGResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Recommendation system
type RecommendationRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Context            map[string]string      `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Current context/preferences
	MaxRecommendations int32                  `protobuf:"varint,3,opt,name=max_recommendations,json=maxRecommendations,proto3" json:"max_recommendations,omitempty"`
	Type               RecommendationType     `protobuf:"varint,4,opt,name=type,proto3,enum=gpu_rag_system.RecommendationType" json:"type,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RecommendationRequest) Reset() {
	*x = RecommendationRequest{}
	mi := &file_gpu_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationRequest) ProtoMessage() {}

func (x *RecommendationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationRequest.ProtoReflect.Descriptor instead.
func (*RecommendationRequest) Descriptor() ([]byte, []int) {
	return file_gpu_service_proto_rawDescGZIP(), []int{12}
}

func (x *RecommendationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecommendationRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *RecommendationRequest) GetMaxRecommendations() int32 {
	if x != nil {
		return x.MaxRecommendations
	}
	return 0
}

func (x *RecommendationRequest) GetType() RecommendationType {
	if x != nil {
		return x.Type
	}
	return RecommendationType_DOCUMENTS
}

type RecommendationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Recommendations []*RecommendationItem  `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	ConfidenceScore float32                `protobuf:"fixed32,2,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	AlgorithmUsed   string                 `protobuf:"bytes,3,opt,name=algorithm_used,json=algorithmUsed,proto3" json:"algorithm_used,omitempty"` // "collaborative", "content", "hybrid"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecommendationResponse) Reset() {
	*x = RecommendationResponse{}
	mi := &file_gpu_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationResponse) ProtoMessage() {}

func (x *RecommendationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationResponse.ProtoReflect.Descriptor instead.
func (*RecommendationResponse) Descriptor() ([]byte, []int) {
	return file_gpu_service_proto_rawDescGZIP(), []int{13}
}

func (x *RecommendationResponse) GetRecommendations() []*RecommendationItem {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

func (x *RecommendationResponse) GetConfidenceScore() float32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *RecommendationResponse) GetAlgorithmUsed() string {
	if x != nil {
		return x.AlgorithmUsed
	}
	return ""
}

type RecommendationItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ItemId         string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	RelevanceScore float32                `protobuf:"fixed32,4,opt,name=relevance_score,json=relevanceScore,proto3" json:"relevance_score,omitempty"`
	Category       string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecommendationItem) Reset() {
	*x = RecommendationItem{}
	mi := &file_gpu_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationItem) ProtoMessage() {}

func (x *RecommendationItem) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationItem.ProtoReflect.Descriptor instead.
func (*RecommendationItem) Descriptor() ([]byte, []int) {
	return file_gpu_service_proto_rawDescGZIP(), []int{14}
}

func (x *RecommendationItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *RecommendationItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RecommendationItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RecommendationItem) GetRelevanceScore() float32 {
	if x != nil {
		return x.RelevanceScore
	}
	return 0
}

func (x *RecommendationItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *RecommendationItem) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_gpu_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_gpu_service_proto_rawDescGZIP(), []int{15}
}

func (x *HealthCheckRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsHealthy     bool                   `protobuf:"varint,1,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	ServiceStatus map[string]string      `protobuf:"bytes,3,rep,name=service_status,json=serviceStatus,proto3" json:"service_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // PostgreSQL, Redis, Neo4j, etc.
	Resources     *SystemResources       `protobuf:"bytes,4,opt,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_gpu_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_gpu_service_proto_rawDescGZIP(), []int{16}
}

func (x *HealthCheckResponse) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *HealthCheckResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *HealthCheckResponse) GetServiceStatus() map[string]string {
	if x != nil {
		return x.ServiceStatus
	}
	return nil
}

func (x *HealthCheckResponse) GetResources() *SystemResources {
	if x != nil {
		return x.Resources
	}
	return nil
}

type SystemResources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage      float32                `protobuf:"fixed32,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`          // 0.0 to 1.0
	MemoryUsage   float32                `protobuf:"fixed32,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"` // 0.0 to 1.0
	GpuUsage      float32                `protobuf:"fixed32,3,opt,name=gpu_usage,json=gpuUsage,proto3" json:"gpu_usage,omitempty"`          // 0.0 to 1.0
	DiskFreeBytes int64                  `protobuf:"varint,4,opt,name=disk_free_bytes,json=diskFreeBytes,proto3" json:"disk_free_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemResources) Reset() {
	*x = SystemResources{}
	mi := &file_gpu_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemResources) ProtoMessage() {}

func (x *SystemResources) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemResources.ProtoReflect.Descriptor instead.
func (*SystemResources) Descriptor() ([]byte, []int) {
	return file_gpu_service_proto_rawDescGZIP(), []int{17}
}

func (x *SystemResources) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *SystemResources) GetMemoryUsage() float32 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *SystemResources) GetGpuUsage() float32 {
	if x != nil {
		return x.GpuUsage
	}
	return 0
}

func (x *SystemResources) GetDiskFreeBytes() int64 {
	if x != nil {
		return x.DiskFreeBytes
	}
	return 0
}

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     int64                  `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // Unix timestamp
	EndTime       int64                  `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	MetricNames   []string               `protobuf:"bytes,3,rep,name=metric_names,json=metricNames,proto3" json:"metric_names,omitempty"` // Specific metrics to fetch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_gpu_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_gpu_service_proto_rawDescGZIP(), []int{18}
}

func (x *MetricsRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *MetricsRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *MetricsRequest) GetMetricNames() []string {
	if x != nil {
		return x.MetricNames
	}
	return nil
}

type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_gpu_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_gpu_service_proto_rawDescGZIP(), []int{19}
}

func (x *MetricsResponse) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "counter", "gauge", "histogram"
	DataPoints    []*DataPoint           `protobuf:"bytes,3,rep,name=data_points,json=dataPoints,proto3" json:"data_points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_gpu_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_gpu_service_proto_rawDescGZIP(), []int{20}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Metric) GetDataPoints() []*DataPoint {
	if x != nil {
		return x.DataPoints
	}
	return nil
}

type DataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPoint) Reset() {
	*x = DataPoint{}
	mi := &file_gpu_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPoint) ProtoMessage() {}

func (x *DataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPoint.ProtoReflect.Descriptor instead.
func (*DataPoint) Descriptor() ([]byte, []int) {
	return file_gpu_service_proto_rawDescGZIP(), []int{21}
}

func (x *DataPoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DataPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *DataPoint) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_gpu_service_proto protoreflect.FileDescriptor

const file_gpu_service_proto_rawDesc = "" +
	"\n" +
	"\x11gpu_service.proto\x12\x0egpu_rag_system\"h\n" +
	"\x0fEmbeddingVector\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x03 \x01(\x05R\n" +
	"dimensions\"\x82\x02\n" +
	"\tTextChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\x12\x1f\n" +
	"\vdocument_id\x18\x03 \x01(\tR\n" +
	"documentId\x12\x17\n" +
	"\acase_id\x18\x04 \x01(\tR\x06caseId\x12C\n" +
	"\bmetadata\x18\x05 \x03(\v2'.gpu_rag_system.TextChunk.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf7\x01\n" +
	"\tDataChunk\x12\x1f\n" +
	"\n" +
	"utf8_bytes\x18\x01 \x01(\fH\x00R\tutf8Bytes\x12?\n" +
	"\tembedding\x18\x02 \x01(\v2\x1f.gpu_rag_system.EmbeddingVectorH\x00R\tembedding\x12\x1d\n" +
	"\tjson_data\x18\x03 \x01(\tH\x00R\bjsonData\x12\x1f\n" +
	"\vsequence_id\x18\x04 \x01(\x05R\n" +
	"sequenceId\x12\x19\n" +
	"\bis_final\x18\x05 \x01(\bR\aisFinal\x12%\n" +
	"\x0eoperation_type\x18\x06 \x01(\tR\roperationTypeB\x06\n" +
	"\x04data\"\x88\x02\n" +
	"\x0fSemanticRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12:\n" +
	"\vtext_chunks\x18\x03 \x03(\v2\x19.gpu_rag_system.TextChunkR\n" +
	"textChunks\x12?\n" +
	"\n" +
	"embeddings\x18\x04 \x03(\v2\x1f.gpu_rag_system.EmbeddingVectorR\n" +
	"embeddings\x12;\n" +
	"\aoptions\x18\x05 \x01(\v2!.gpu_rag_system.ProcessingOptionsR\aoptions\"\xbf\x02\n" +
	"\x11ProcessingOptions\x120\n" +
	"\x14use_gpu_acceleration\x18\x01 \x01(\bR\x12useGpuAcceleration\x12%\n" +
	"\x0eenable_caching\x18\x02 \x01(\bR\renableCaching\x12'\n" +
	"\x0fmax_concurrency\x18\x03 \x01(\x05R\x0emaxConcurrency\x121\n" +
	"\x14clustering_algorithm\x18\x04 \x01(\tR\x13clusteringAlgorithm\x121\n" +
	"\x14similarity_threshold\x18\x05 \x01(\x02R\x13similarityThreshold\x12B\n" +
	"\x1denable_reinforcement_learning\x18\x06 \x01(\bR\x1benableReinforcementLearning\"\xc0\x03\n" +
	"\x10ProcessingResult\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x128\n" +
	"\x06status\x18\x03 \x01(\x0e2 .gpu_rag_system.ProcessingStatusR\x06status\x12L\n" +
	"\x11result_embeddings\x18\x04 \x03(\v2\x1f.gpu_rag_system.EmbeddingVectorR\x10resultEmbeddings\x127\n" +
	"\bclusters\x18\x05 \x03(\v2\x1b.gpu_rag_system.ClusterInfoR\bclusters\x12C\n" +
	"\x0esearch_results\x18\x06 \x03(\v2\x1c.gpu_rag_system.SearchResultR\rsearchResults\x12D\n" +
	"\vperformance\x18\a \x01(\v2\".gpu_rag_system.PerformanceMetricsR\vperformance\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\"\xaa\x01\n" +
	"\vClusterInfo\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\x05R\tclusterId\x12;\n" +
	"\bcentroid\x18\x02 \x01(\v2\x1f.gpu_rag_system.EmbeddingVectorR\bcentroid\x12%\n" +
	"\x0emember_indices\x18\x03 \x03(\x05R\rmemberIndices\x12\x18\n" +
	"\ainertia\x18\x04 \x01(\x02R\ainertia\"\xb8\x02\n" +
	"\fSearchResult\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12)\n" +
	"\x10similarity_score\x18\x02 \x01(\x02R\x0fsimilarityScore\x12=\n" +
	"\tembedding\x18\x03 \x01(\v2\x1f.gpu_rag_system.EmbeddingVectorR\tembedding\x12\x18\n" +
	"\asnippet\x18\x04 \x01(\tR\asnippet\x12F\n" +
	"\bmetadata\x18\x05 \x03(\v2*.gpu_rag_system.SearchResult.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x02\n" +
	"\x12PerformanceMetrics\x12,\n" +
	"\x12processing_time_ms\x18\x01 \x01(\x03R\x10processingTimeMs\x12-\n" +
	"\x13gpu_compute_time_ms\x18\x02 \x01(\x03R\x10gpuComputeTimeMs\x12\x1d\n" +
	"\n" +
	"cache_hits\x18\x03 \x01(\x05R\tcacheHits\x12!\n" +
	"\fcache_misses\x18\x04 \x01(\x05R\vcacheMisses\x12'\n" +
	"\x0fgpu_utilization\x18\x05 \x01(\x02R\x0egpuUtilization\x12*\n" +
	"\x11memory_used_bytes\x18\x06 \x01(\x03R\x0fmemoryUsedBytes\"\x8a\x01\n" +
	"\n" +
	"RAGRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x17\n" +
	"\acase_id\x18\x02 \x01(\tR\x06caseId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x124\n" +
	"\aoptions\x18\x04 \x01(\v2\x1a.gpu_rag_system.RAGOptionsR\aoptions\"\xf8\x01\n" +
	"\n" +
	"RAGOptions\x12\x13\n" +
	"\x05top_k\x18\x01 \x01(\x05R\x04topK\x120\n" +
	"\x14enable_hybrid_search\x18\x02 \x01(\bR\x12enableHybridSearch\x12)\n" +
	"\x10enable_reranking\x18\x03 \x01(\bR\x0fenableReranking\x12-\n" +
	"\x12enable_compression\x18\x04 \x01(\bR\x11enableCompression\x12/\n" +
	"\x13diversity_threshold\x18\x05 \x01(\x02R\x12diversityThreshold\x12\x18\n" +
	"\afilters\x18\x06 \x03(\tR\afilters\"\xd7\x02\n" +
	"\vRAGResponse\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\x126\n" +
	"\asources\x18\x03 \x03(\v2\x1c.gpu_rag_system.SearchResultR\asources\x12\x18\n" +
	"\acontext\x18\x04 \x01(\tR\acontext\x12D\n" +
	"\vperformance\x18\x05 \x01(\v2\".gpu_rag_system.PerformanceMetricsR\vperformance\x12E\n" +
	"\bmetadata\x18\x06 \x03(\v2).gpu_rag_system.RAGResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa3\x02\n" +
	"\x15RecommendationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12L\n" +
	"\acontext\x18\x02 \x03(\v22.gpu_rag_system.RecommendationRequest.ContextEntryR\acontext\x12/\n" +
	"\x13max_recommendations\x18\x03 \x01(\x05R\x12maxRecommendations\x126\n" +
	"\x04type\x18\x04 \x01(\x0e2\".gpu_rag_system.RecommendationTypeR\x04type\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb8\x01\n" +
	"\x16RecommendationResponse\x12L\n" +
	"\x0frecommendations\x18\x01 \x03(\v2\".gpu_rag_system.RecommendationItemR\x0frecommendations\x12)\n" +
	"\x10confidence_score\x18\x02 \x01(\x02R\x0fconfidenceScore\x12%\n" +
	"\x0ealgorithm_used\x18\x03 \x01(\tR\ralgorithmUsed\"\xb5\x02\n" +
	"\x12RecommendationItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12'\n" +
	"\x0frelevance_score\x18\x04 \x01(\x02R\x0erelevanceScore\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12L\n" +
	"\bmetadata\x18\x06 \x03(\v20.gpu_rag_system.RecommendationItem.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"7\n" +
	"\x12HealthCheckRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"\xbb\x02\n" +
	"\x13HealthCheckResponse\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\x01 \x01(\bR\tisHealthy\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\x12]\n" +
	"\x0eservice_status\x18\x03 \x03(\v26.gpu_rag_system.HealthCheckResponse.ServiceStatusEntryR\rserviceStatus\x12=\n" +
	"\tresources\x18\x04 \x01(\v2\x1f.gpu_rag_system.SystemResourcesR\tresources\x1a@\n" +
	"\x12ServiceStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x01\n" +
	"\x0fSystemResources\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x02R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x02R\vmemoryUsage\x12\x1b\n" +
	"\tgpu_usage\x18\x03 \x01(\x02R\bgpuUsage\x12&\n" +
	"\x0fdisk_free_bytes\x18\x04 \x01(\x03R\rdiskFreeBytes\"m\n" +
	"\x0eMetricsRequest\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\x03R\aendTime\x12!\n" +
	"\fmetric_names\x18\x03 \x03(\tR\vmetricNames\"C\n" +
	"\x0fMetricsResponse\x120\n" +
	"\ametrics\x18\x01 \x03(\v2\x16.gpu_rag_system.MetricR\ametrics\"l\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12:\n" +
	"\vdata_points\x18\x03 \x03(\v2\x19.gpu_rag_system.DataPointR\n" +
	"dataPoints\"\xb9\x01\n" +
	"\tDataPoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12=\n" +
	"\x06labels\x18\x03 \x03(\v2%.gpu_rag_system.DataPoint.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*X\n" +
	"\x10ProcessingStatus\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x00\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x01\x12\r\n" +
	"\tCOMPLETED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\x12\r\n" +
	"\tCANCELLED\x10\x04*W\n" +
	"\x12RecommendationType\x12\r\n" +
	"\tDOCUMENTS\x10\x00\x12\t\n" +
	"\x05CASES\x10\x01\x12\x12\n" +
	"\x0eLEGAL_CONCEPTS\x10\x02\x12\x13\n" +
	"\x0fSIMILAR_QUERIES\x10\x032\xd7\x04\n" +
	"\x14GPUProcessingService\x12P\n" +
	"\rProcessStream\x12\x19.gpu_rag_system.DataChunk\x1a .gpu_rag_system.ProcessingResult(\x010\x01\x12T\n" +
	"\x0fProcessSemantic\x12\x1f.gpu_rag_system.SemanticRequest\x1a .gpu_rag_system.ProcessingResult\x12C\n" +
	"\bQueryRAG\x12\x1a.gpu_rag_system.RAGRequest\x1a\x1b.gpu_rag_system.RAGResponse\x12F\n" +
	"\tStreamRAG\x12\x1a.gpu_rag_system.RAGRequest\x1a\x1b.gpu_rag_system.RAGResponse0\x01\x12c\n" +
	"\x12GetRecommendations\x12%.gpu_rag_system.RecommendationRequest\x1a&.gpu_rag_system.RecommendationResponse\x12V\n" +
	"\vHealthCheck\x12\".gpu_rag_system.HealthCheckRequest\x1a#.gpu_rag_system.HealthCheckResponse\x12M\n" +
	"\n" +
	"GetMetrics\x12\x1e.gpu_rag_system.MetricsRequest\x1a\x1f.gpu_rag_system.MetricsResponseB0Z.legal-ai-production/proto/gpu;gpub\x06proto3"

var (
	file_gpu_service_proto_rawDescOnce sync.Once
	file_gpu_service_proto_rawDescData []byte
)

func file_gpu_service_proto_rawDescGZIP() []byte {
	file_gpu_service_proto_rawDescOnce.Do(func() {
		file_gpu_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gpu_service_proto_rawDesc), len(file_gpu_service_proto_rawDesc)))
	})
	return file_gpu_service_proto_rawDescData
}

var file_gpu_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gpu_service_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_gpu_service_proto_goTypes = []any{
	(ProcessingStatus)(0),          // 0: gpu_rag_system.ProcessingStatus
	(RecommendationType)(0),        // 1: gpu_rag_system.RecommendationType
	(*EmbeddingVector)(nil),        // 2: gpu_rag_system.EmbeddingVector
	(*TextChunk)(nil),              // 3: gpu_rag_system.TextChunk
	(*DataChunk)(nil),              // 4: gpu_rag_system.DataChunk
	(*SemanticRequest)(nil),        // 5: gpu_rag_system.SemanticRequest
	(*ProcessingOptions)(nil),      // 6: gpu_rag_system.ProcessingOptions
	(*ProcessingResult)(nil),       // 7: gpu_rag_system.ProcessingResult
	(*ClusterInfo)(nil),            // 8: gpu_rag_system.ClusterInfo
	(*SearchResult)(nil),           // 9: gpu_rag_system.SearchResult
	(*PerformanceMetrics)(nil),     // 10: gpu_rag_system.PerformanceMetrics
	(*RAGRequest)(nil),             // 11: gpu_rag_system.RAGRequest
	(*RAGOptions)(nil),             // 12: gpu_rag_system.RAGOptions
	(*RAGResponse)(nil),            // 13: gpu_rag_system.RAGResponse
	(*RecommendationRequest)(nil),  // 14: gpu_rag_system.RecommendationRequest
	(*RecommendationResponse)(nil), // 15: gpu_rag_system.RecommendationResponse
	(*RecommendationItem)(nil),     // 16: gpu_rag_system.RecommendationItem
	(*HealthCheckRequest)(nil),     // 17: gpu_rag_system.HealthCheckRequest
	(*HealthCheckResponse)(nil),    // 18: gpu_rag_system.HealthCheckResponse
	(*SystemResources)(nil),        // 19: gpu_rag_system.SystemResources
	(*MetricsRequest)(nil),         // 20: gpu_rag_system.MetricsRequest
	(*MetricsResponse)(nil),        // 21: gpu_rag_system.MetricsResponse
	(*Metric)(nil),                 // 22: gpu_rag_system.Metric
	(*DataPoint)(nil),              // 23: gpu_rag_system.DataPoint
	nil,                            // 24: gpu_rag_system.TextChunk.MetadataEntry
	nil,                            // 25: gpu_rag_system.SearchResult.MetadataEntry
	nil,                            // 26: gpu_rag_system.RAGResponse.MetadataEntry
	nil,                            // 27: gpu_rag_system.RecommendationRequest.ContextEntry
	nil,                            // 28: gpu_rag_system.RecommendationItem.MetadataEntry
	nil,                            // 29: gpu_rag_system.HealthCheckResponse.ServiceStatusEntry
	nil,                            // 30: gpu_rag_system.DataPoint.LabelsEntry
}
var file_gpu_service_proto_depIdxs = []int32{
	24, // 0: gpu_rag_system.TextChunk.metadata:type_name -> gpu_rag_system.TextChunk.MetadataEntry
	2,  // 1: gpu_rag_system.DataChunk.embedding:type_name -> gpu_rag_system.EmbeddingVector
	3,  // 2: gpu_rag_system.SemanticRequest.text_chunks:type_name -> gpu_rag_system.TextChunk
	2,  // 3: gpu_rag_system.SemanticRequest.embeddings:type_name -> gpu_rag_system.EmbeddingVector
	6,  // 4: gpu_rag_system.SemanticRequest.options:type_name -> gpu_rag_system.ProcessingOptions
	0,  // 5: gpu_rag_system.ProcessingResult.status:type_name -> gpu_rag_system.ProcessingStatus
	2,  // 6: gpu_rag_system.ProcessingResult.result_embeddings:type_name -> gpu_rag_system.EmbeddingVector
	8,  // 7: gpu_rag_system.ProcessingResult.clusters:type_name -> gpu_rag_system.ClusterInfo
	9,  // 8: gpu_rag_system.ProcessingResult.search_results:type_name -> gpu_rag_system.SearchResult
	10, // 9: gpu_rag_system.ProcessingResult.performance:type_name -> gpu_rag_system.PerformanceMetrics
	2,  // 10: gpu_rag_system.ClusterInfo.centroid:type_name -> gpu_rag_system.EmbeddingVector
	2,  // 11: gpu_rag_system.SearchResult.embedding:type_name -> gpu_rag_system.EmbeddingVector
	25, // 12: gpu_rag_system.SearchResult.metadata:type_name -> gpu_rag_system.SearchResult.MetadataEntry
	12, // 13: gpu_rag_system.RAGRequest.options:type_name -> gpu_rag_system.RAGOptions
	9,  // 14: gpu_rag_system.RAGResponse.sources:type_name -> gpu_rag_system.SearchResult
	10, // 15: gpu_rag_system.RAGResponse.performance:type_name -> gpu_rag_system.PerformanceMetrics
	26, // 16: gpu_rag_system.RAGResponse.metadata:type_name -> gpu_rag_system.RAGResponse.MetadataEntry
	27, // 17: gpu_rag_system.RecommendationRequest.context:type_name -> gpu_rag_system.RecommendationRequest.ContextEntry
	1,  // 18: gpu_rag_system.RecommendationRequest.type:type_name -> gpu_rag_system.RecommendationType
	16, // 19: gpu_rag_system.RecommendationResponse.recommendations:type_name -> gpu_rag_system.RecommendationItem
	28, // 20: gpu_rag_system.RecommendationItem.metadata:type_name -> gpu_rag_system.RecommendationItem.MetadataEntry
	29, // 21: gpu_rag_system.HealthCheckResponse.service_status:type_name -> gpu_rag_system.HealthCheckResponse.ServiceStatusEntry
	19, // 22: gpu_rag_system.HealthCheckResponse.resources:type_name -> gpu_rag_system.SystemResources
	22, // 23: gpu_rag_system.MetricsResponse.metrics:type_name -> gpu_rag_system.Metric
	23, // 24: gpu_rag_system.Metric.data_points:type_name -> gpu_rag_system.DataPoint
	30, // 25: gpu_rag_system.DataPoint.labels:type_name -> gpu_rag_system.DataPoint.LabelsEntry
	4,  // 26: gpu_rag_system.GPUProcessingService.ProcessStream:input_type -> gpu_rag_system.DataChunk
	5,  // 27: gpu_rag_system.GPUProcessingService.ProcessSemantic:input_type -> gpu_rag_system.SemanticRequest
	11, // 28: gpu_rag_system.GPUProcessingService.QueryRAG:input_type -> gpu_rag_system.RAGRequest
	11, // 29: gpu_rag_system.GPUProcessingService.StreamRAG:input_type -> gpu_rag_system.RAGRequest
	14, // 30: gpu_rag_system.GPUProcessingService.GetRecommendations:input_type -> gpu_rag_system.RecommendationRequest
	17, // 31: gpu_rag_system.GPUProcessingService.HealthCheck:input_type -> gpu_rag_system.HealthCheckRequest
	20, // 32: gpu_rag_system.GPUProcessingService.GetMetrics:input_type -> gpu_rag_system.MetricsRequest
	7,  // 33: gpu_rag_system.GPUProcessingService.ProcessStream:output_type -> gpu_rag_system.ProcessingResult
	7,  // 34: gpu_rag_system.GPUProcessingService.ProcessSemantic:output_type -> gpu_rag_system.ProcessingResult
	13, // 35: gpu_rag_system.GPUProcessingService.QueryRAG:output_type -> gpu_rag_system.RAGResponse
	13, // 36: gpu_rag_system.GPUProcessingService.StreamRAG:output_type -> gpu_rag_system.RAGResponse
	15, // 37: gpu_rag_system.GPUProcessingService.GetRecommendations:output_type -> gpu_rag_system.RecommendationResponse
	18, // 38: gpu_rag_system.GPUProcessingService.HealthCheck:output_type -> gpu_rag_system.HealthCheckResponse
	21, // 39: gpu_rag_system.GPUProcessingService.GetMetrics:output_type -> gpu_rag_system.MetricsResponse
	33, // [33:40] is the sub-list for method output_type
	26, // [26:33] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_gpu_service_proto_init() }
func file_gpu_service_proto_init() {
	if File_gpu_service_proto != nil {
		return
	}
	file_gpu_service_proto_msgTypes[2].OneofWrappers = []any{
		(*DataChunk_Utf8Bytes)(nil),
		(*DataChunk_Embedding)(nil),
		(*DataChunk_JsonData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gpu_service_proto_rawDesc), len(file_gpu_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gpu_service_proto_goTypes,
		DependencyIndexes: file_gpu_service_proto_depIdxs,
		EnumInfos:         file_gpu_service_proto_enumTypes,
		MessageInfos:      file_gpu_service_proto_msgTypes,
	}.Build()
	File_gpu_service_proto = out.File
	file_gpu_service_proto_goTypes = nil
	file_gpu_service_proto_depIdxs = nil
}
