name: "yolo_seal"
platform: "tensorrt_plan"
max_batch_size: 16
input [
  {
    name: "input"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 640, 640 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 1, 25200, 6 ]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 0 ]
  }
]
dynamic_batching {
  preferred_batch_size: [ 8, 16 ]
  max_queue_delay_microseconds: 50
}
optimization {
  execution_accelerators {
    gpu_execution_accelerator : [
      {
        name: "tensorrt"
        parameters { key: "precision_mode" value: "INT8" }
      }
    ]
  }
}