# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import chr97_agent_pb2 as chr97__agent__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in chr97_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Chr97AgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCartridge = channel.unary_unary(
                '/chr97.Chr97Agent/GetCartridge',
                request_serializer=chr97__agent__pb2.GetCartridgeRequest.SerializeToString,
                response_deserializer=chr97__agent__pb2.GetCartridgeResponse.FromString,
                _registered_method=True)
        self.QueryTags = channel.unary_unary(
                '/chr97.Chr97Agent/QueryTags',
                request_serializer=chr97__agent__pb2.TagQueryRequest.SerializeToString,
                response_deserializer=chr97__agent__pb2.TagQueryResponse.FromString,
                _registered_method=True)
        self.GetTimeline = channel.unary_unary(
                '/chr97.Chr97Agent/GetTimeline',
                request_serializer=chr97__agent__pb2.TimelineRequest.SerializeToString,
                response_deserializer=chr97__agent__pb2.TimelineResponse.FromString,
                _registered_method=True)


class Chr97AgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCartridge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryTags(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Chr97AgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCartridge': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCartridge,
                    request_deserializer=chr97__agent__pb2.GetCartridgeRequest.FromString,
                    response_serializer=chr97__agent__pb2.GetCartridgeResponse.SerializeToString,
            ),
            'QueryTags': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryTags,
                    request_deserializer=chr97__agent__pb2.TagQueryRequest.FromString,
                    response_serializer=chr97__agent__pb2.TagQueryResponse.SerializeToString,
            ),
            'GetTimeline': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimeline,
                    request_deserializer=chr97__agent__pb2.TimelineRequest.FromString,
                    response_serializer=chr97__agent__pb2.TimelineResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chr97.Chr97Agent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chr97.Chr97Agent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Chr97Agent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCartridge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chr97.Chr97Agent/GetCartridge',
            chr97__agent__pb2.GetCartridgeRequest.SerializeToString,
            chr97__agent__pb2.GetCartridgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chr97.Chr97Agent/QueryTags',
            chr97__agent__pb2.TagQueryRequest.SerializeToString,
            chr97__agent__pb2.TagQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTimeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chr97.Chr97Agent/GetTimeline',
            chr97__agent__pb2.TimelineRequest.SerializeToString,
            chr97__agent__pb2.TimelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
