/**
 * Glossary Batch 14 — International Law Terms
 * Covers erga omnes, universality principle, and related public
 * international law doctrines. Jus cogens and VCLT already exist
 * in earlier batches — this batch adds complementary terms.
 *
 * ~18 terms
 */
const terms = [

  // ─── OBLIGATIONS & NORMS ─────────────────────────────────────────────────

  ['Erga Omnes Obligations', 'Obligations owed by a state to the international community as a whole, as opposed to obligations owed only to specific states under treaties or bilateral agreements. The concept was recognized by the ICJ in the Barcelona Traction case (1970), which identified erga omnes obligations as including the prohibition of genocide, the prohibition of slavery and racial discrimination, the prohibition of aggression, and the right to self-determination. Because erga omnes obligations are owed to all states, any state has legal standing (locus standi) to invoke the responsibility of a state that breaches them, even without showing individual injury. The ILC Articles on State Responsibility (2001) Art. 48 codify this by allowing "any State other than an injured State" to invoke responsibility for breaches of obligations owed to the international community. Erga omnes obligations overlap significantly with jus cogens norms but are conceptually distinct: jus cogens defines the hierarchical status of the norm (non-derogable), while erga omnes defines the scope of the obligation (owed to all). Example: South Africa\'s apartheid regime violated erga omnes obligations against racial discrimination — any state could invoke South Africa\'s responsibility, not just states individually harmed.', 'international_law', 'International', ['Jus Cogens', 'State Responsibility', 'Standing (International)', 'Self-Determination'], ['Barcelona Traction, Light and Power Co. (Belgium v. Spain), ICJ 1970', 'ILC Articles on State Responsibility (2001) Art. 48']],

  ['Universality Principle', 'The principle of jurisdiction in international law that permits any state to prosecute certain crimes of universal concern regardless of where the crime occurred, the nationality of the perpetrator, or the nationality of the victim. Crimes subject to universal jurisdiction include piracy (the historical basis), genocide, crimes against humanity, war crimes, torture, slavery, and certain terrorism offenses. The universality principle is based on the theory that some crimes are so grave that they affect the interests of all states and all of humanity, making every state a custodian of international justice. Universal jurisdiction may be exercised in absentia (without the accused being present) in some legal systems, though this is controversial. The principle is codified in various treaties: the Geneva Conventions (grave breaches), the Convention Against Torture (Art. 5), and the Genocide Convention. Example: Spain\'s National Court issued an international arrest warrant for Chilean dictator Augusto Pinochet in 1998, asserting universal jurisdiction over crimes against humanity and torture committed in Chile — crimes with no direct connection to Spain.', 'international_law', 'International', ['Erga Omnes Obligations', 'Jus Cogens', 'Extradition', 'International Criminal Court'], ['R v. Bow Street Metropolitan Stipendiary Magistrate, ex parte Pinochet (No. 3) [2000]', 'Geneva Conventions Common Art. 49/50/129/146']],

  ['Comity of Nations', 'The principle that courts of one jurisdiction will give effect to the laws, judicial decisions, and official acts of another jurisdiction, not as a matter of binding obligation but out of mutual respect and reciprocity. Comity is not a rule of law but a practice of courtesy and good will between sovereign nations. In U.S. law, comity applies in several contexts: (1) recognition and enforcement of foreign judgments (Hilton v. Guyot), (2) deference to pending foreign proceedings (international lis pendens), (3) application of foreign law in choice-of-law determinations, and (4) interpretation of statutes to avoid unreasonable interference with other nations\' sovereign authority (prescriptive comity). The Supreme Court in Société Nationale distinguished between "adjudicative comity" (deference to foreign courts) and "prescriptive comity" (limiting the reach of domestic law). Example: A U.S. court may recognize and enforce a French monetary judgment against a U.S. defendant, not because international law requires it, but as a matter of comity — provided the French court had jurisdiction, due process was observed, and the judgment is not repugnant to U.S. public policy.', 'international_law', 'International/Federal', ['Sovereign Immunity', 'Act of State Doctrine', 'Forum Non Conveniens', 'Choice of Law'], ['Hilton v. Guyot, 159 U.S. 113 (1895)', 'Société Nationale Industrielle Aérospatiale v. U.S. Dist. Court, 482 U.S. 522 (1987)']],

  ['State Responsibility', 'The international law framework governing when a state is legally responsible for internationally wrongful acts and the consequences of such responsibility. The ILC Articles on State Responsibility (2001) provide that an internationally wrongful act occurs when conduct (1) is attributable to the state under international law and (2) constitutes a breach of an international obligation of the state. Attribution extends beyond government officials to include organs of the state, entities exercising governmental authority, persons acting under state direction or control, and private actors whose conduct the state subsequently acknowledges and adopts. Consequences of state responsibility include: cessation of the wrongful act, non-repetition assurances, and reparation (restitution, compensation, or satisfaction). Circumstances precluding wrongfulness include consent, self-defense, countermeasures, force majeure, distress, and necessity. Example: If a state\'s military forces unlawfully attack a foreign embassy, the state bears international responsibility for the conduct of its military organs and must provide reparation — even if the soldiers acted contrary to orders.', 'international_law', 'International', ['Erga Omnes Obligations', 'Jus Cogens', 'Countermeasures', 'International Court of Justice'], ['ILC Articles on State Responsibility (2001)', 'Corfu Channel Case (UK v. Albania), ICJ 1949']],

  ['Self-Determination of Peoples', 'The principle that peoples have the right to freely determine their political status and freely pursue their economic, social, and cultural development. Enshrined in UN Charter Art. 1(2) and Art. 55, the International Covenant on Civil and Political Rights (Art. 1), and the International Covenant on Economic, Social and Cultural Rights (Art. 1). Self-determination was initially applied in the decolonization context (the right of colonized peoples to independence), but has evolved to encompass "internal self-determination" — the right of peoples within existing states to participate in governance without discrimination. The tension between self-determination and territorial integrity (uti possidetis juris) is a central challenge in international law, as seen in cases involving Kosovo, Crimea, Catalonia, and Kurdistan. The ICJ\'s Kosovo Advisory Opinion (2010) held that declarations of independence do not per se violate international law but did not affirm a general right to secession outside the colonial context. Example: East Timor exercised the right of self-determination through a UN-supervised referendum in 1999, voting for independence from Indonesia after decades of occupation.', 'international_law', 'International', ['Erga Omnes Obligations', 'Uti Possidetis Juris', 'Sovereignty', 'United Nations Charter'], ['UN Charter Art. 1(2)', 'Accordance with International Law of the Unilateral Declaration of Independence in Respect of Kosovo, ICJ Advisory Opinion (2010)']],

  // ─── JURISDICTION & SOVEREIGNTY ──────────────────────────────────────────

  ['Sovereign Immunity (International)', 'The principle that a sovereign state cannot be sued in the courts of another state without its consent. Under customary international law and the UN Convention on Jurisdictional Immunities (2004, not yet in force), state immunity is the default rule, subject to exceptions for commercial activities (restrictive theory of immunity). The U.S. codified the restrictive theory in the Foreign Sovereign Immunities Act (FSIA, 1976, 28 U.S.C. §§1602-1611), which provides that foreign states are immune from jurisdiction except for: (1) commercial activity carried on in or having direct effect in the U.S. (§1605(a)(2)), (2) rights in immovable property in the U.S. (§1605(a)(4)), (3) tortious acts in the U.S. (§1605(a)(5)), (4) waiver (§1605(a)(1)), and (5) state-sponsored terrorism (§1605A). Sovereign immunity extends to the state itself, its political subdivisions, agencies, and instrumentalities. Example: Argentina issued bonds in the U.S. and subsequently defaulted. Under the FSIA commercial activity exception, U.S. courts had jurisdiction because the bond issuance was a commercial activity with a direct effect in the United States (Republic of Argentina v. NML Capital).', 'international_law', 'International/Federal', ['Act of State Doctrine', 'Comity of Nations', 'FSIA', 'Head of State Immunity'], ['Foreign Sovereign Immunities Act, 28 U.S.C. §§1602-1611', 'Republic of Argentina v. NML Capital, Ltd., 573 U.S. 134 (2014)']],

  ['Act of State Doctrine', 'A judicial abstention doctrine providing that U.S. courts will not sit in judgment on the validity of official acts of a recognized foreign sovereign government performed within its own territory. The doctrine is grounded in separation of powers and international comity rather than foreign sovereign immunity. Under Banco Nacional de Cuba v. Sabbatino (1964), the doctrine applies even if the foreign government\'s act violates international law. The doctrine does not apply when: (1) the act was purely commercial (commercial activity exception), (2) a treaty or statute directs the court to apply international legal standards (Hickenlooper Amendment), or (3) the foreign government is no longer recognized. The act of state doctrine differs from sovereign immunity in that it bars inquiry into the validity of the foreign act itself, while sovereign immunity bars jurisdiction over the foreign state as a party. Example: Cuba nationalized (expropriated) a U.S. company\'s sugar operations without compensation. Under the act of state doctrine, U.S. courts cannot rule that Cuba\'s nationalization decree was invalid, even if the expropriation violated international law.', 'international_law', 'Federal', ['Sovereign Immunity', 'Comity of Nations', 'Expropriation', 'Political Question Doctrine'], ['Banco Nacional de Cuba v. Sabbatino, 376 U.S. 398 (1964)', 'W.S. Kirkpatrick & Co. v. Environmental Tectonics Corp., 493 U.S. 400 (1990)']],

  ['Diplomatic Immunity', 'The principle under international law that diplomatic agents are immune from the jurisdiction of the receiving state, ensuring the efficient functioning of diplomatic missions. Codified in the Vienna Convention on Diplomatic Relations (1961), diplomatic immunity provides three levels of protection: (1) diplomatic agents (ambassadors, counselors) enjoy full immunity from criminal jurisdiction and immunity from civil/administrative jurisdiction except for private immovable property, succession, and commercial activity (Art. 31), (2) administrative and technical staff have full criminal immunity but civil immunity only for acts performed in the course of duties (Art. 37(2)), and (3) service staff have immunity only for acts performed in the course of duties (Art. 37(3)). The premises of the diplomatic mission are inviolable — the receiving state cannot enter without consent (Art. 22). The sending state may waive immunity (Art. 32). Diplomatic immunity is distinct from consular immunity under the Vienna Convention on Consular Relations (1963), which provides narrower protections. Example: A foreign ambassador in Washington D.C. is involved in a drunk driving accident causing injury. Under the Vienna Convention, the ambassador has full criminal immunity and cannot be arrested, detained, or prosecuted. The U.S. may request a waiver of immunity from the sending state or declare the ambassador persona non grata.', 'international_law', 'International', ['Sovereign Immunity', 'Consular Immunity', 'Vienna Convention on Diplomatic Relations', 'Persona Non Grata'], ['Vienna Convention on Diplomatic Relations (1961) Art. 31', 'United States Diplomatic and Consular Staff in Tehran (ICJ 1980)']],

  // ─── TREATIES & SOURCES ──────────────────────────────────────────────────

  ['Customary International Law', 'One of the primary sources of international law under ICJ Statute Art. 38(1)(b), consisting of general practices accepted as law. Customary international law is formed by two elements: (1) state practice — widespread, representative, and consistent conduct by states (including physical acts, legislation, diplomatic correspondence, and votes in international organizations), and (2) opinio juris — the belief that such practice is carried out as a legal obligation rather than mere habit, courtesy, or political expediency. Customary international law binds all states except persistent objectors — states that have consistently and openly objected to a practice during its formation. Some customary norms have achieved jus cogens status and bind all states regardless of consent. The ILC\'s conclusions on the identification of customary international law (2018) provide guidance on evidence and methodology. Example: The prohibition on torture is a rule of customary international law. Virtually all states condemn torture in their domestic law and international statements (state practice), and do so because they consider it a legal obligation (opinio juris) — not merely because it is politically convenient.', 'international_law', 'International', ['Jus Cogens', 'Treaty', 'General Principles of Law', 'ICJ Statute'], ['ICJ Statute Art. 38(1)(b)', 'North Sea Continental Shelf Cases (Germany v. Denmark; Germany v. Netherlands), ICJ 1969']],

  ['Treaty Reservation', 'A unilateral statement made by a state when signing, ratifying, accepting, approving, or acceding to a treaty, whereby it purports to exclude or modify the legal effect of certain provisions in their application to that state. Under the Vienna Convention on the Law of Treaties (VCLT) Art. 19, a reservation is prohibited if: (a) the treaty prohibits reservations, (b) the treaty allows only specified reservations and the reservation is not among them, or (c) the reservation is incompatible with the object and purpose of the treaty. The ICJ\'s advisory opinion on the Genocide Convention (1951) established the "object and purpose" test, departing from the earlier unanimity rule (which required all parties to consent to any reservation). Under VCLT Art. 20-21, other states may accept or object to a reservation — an objection does not prevent treaty relations unless the objecting state expresses that intention. Example: When ratifying the ICCPR, the United States entered reservations to Articles 6-7, declaring that the prohibition on cruel, inhuman, or degrading treatment is understood as equivalent to the Eighth Amendment prohibition on cruel and unusual punishment, and that the treaty does not restrict the imposition of capital punishment for crimes committed by persons under 18.', 'international_law', 'International', ['Jus Cogens', 'Vienna Convention on the Law of Treaties', 'Treaty Ratification', 'Pacta Sunt Servanda'], ['VCLT Art. 19-23', 'Reservations to the Convention on Genocide, ICJ Advisory Opinion (1951)']],

  ['Pacta Sunt Servanda', 'The fundamental principle of treaty law providing that every treaty in force is binding upon the parties and must be performed by them in good faith (VCLT Art. 26). Widely recognized as a peremptory norm of international law, it is the cornerstone of the international legal order — without it, treaties would have no binding force. The principle applies only to treaties in force and is subject to recognized exceptions: (1) fundamental change of circumstances (rebus sic stantibus, VCLT Art. 62), (2) material breach by another party (VCLT Art. 60), (3) supervening impossibility of performance (VCLT Art. 61), and (4) conflict with a new jus cogens norm (VCLT Art. 64). A state may not invoke provisions of its internal law as justification for failure to perform a treaty (VCLT Art. 27). Example: State A enters a bilateral trade treaty with State B. Even if A\'s government changes, the treaty remains binding under pacta sunt servanda — the new government cannot unilaterally disregard its obligations by claiming the prior government lacked domestic authority to enter the treaty.', 'international_law', 'International', ['Jus Cogens', 'Rebus Sic Stantibus', 'Vienna Convention on the Law of Treaties', 'Good Faith'], ['VCLT Art. 26', 'Nuclear Tests Case (Australia v. France), ICJ 1974']],

  // ─── INTERNATIONAL DISPUTE RESOLUTION ────────────────────────────────────

  ['International Court of Justice (ICJ)', 'The principal judicial organ of the United Nations, established by the UN Charter (Art. 92-96) and governed by the ICJ Statute. The ICJ has two types of jurisdiction: (1) contentious jurisdiction — binding dispute resolution between states that have consented to jurisdiction (through special agreement, treaty clause, or optional clause declaration under Art. 36(2)), and (2) advisory jurisdiction — non-binding legal opinions requested by UN organs and authorized agencies (Art. 65). Only states may be parties in contentious cases — individuals, corporations, and international organizations cannot appear. ICJ judgments are binding on the parties (Art. 59) and enforceable through the UN Security Council (Art. 94(2)), though enforcement is rare. The ICJ sits at The Hague and consists of 15 judges elected for 9-year terms. Example: In the Nicaragua case (1986), the ICJ held that U.S. support for Contra rebels and mining of Nicaraguan harbors violated customary international law prohibitions on the use of force and non-intervention. The U.S. refused to comply, and the Security Council could not enforce the judgment due to the U.S. veto.', 'international_law', 'International', ['Customary International Law', 'State Responsibility', 'UN Charter', 'Advisory Opinion'], ['ICJ Statute Art. 36, 59, 65', 'Military and Paramilitary Activities in and against Nicaragua (Nicaragua v. United States), ICJ 1986']],

  ['Forum Non Conveniens (International)', 'A common law doctrine allowing a court to dismiss a case when another forum (typically a foreign court) is substantially more appropriate for the resolution of the dispute. In international litigation, forum non conveniens analysis considers: (1) the availability of an adequate alternative forum (the defendant is subject to jurisdiction there and the forum provides a remedy), (2) private interest factors (access to evidence, compellability of witnesses, cost of litigation, enforceability of judgment), and (3) public interest factors (local interest in the controversy, burden on local courts, familiarity with governing law). Under Gulf Oil Corp. v. Gilbert and Piper Aircraft Co. v. Reyno, the doctrine applies even when the alternative forum would apply less favorable substantive law. In the EU, the Brussels Regulation (Recast) generally displaces forum non conveniens between EU member states, though it remains available in common law jurisdictions for disputes involving non-EU parties. Example: A Scottish pilot is killed in a crash of a U.S.-manufactured aircraft in Scotland. The victim\'s family sues the manufacturer in a U.S. court. The U.S. court may dismiss on forum non conveniens grounds in favor of Scottish courts, even though Scottish law may provide lower damages.', 'international_law', 'International/Federal', ['Comity of Nations', 'Personal Jurisdiction', 'Choice of Law', 'Brussels Regulation'], ['Gulf Oil Corp. v. Gilbert, 330 U.S. 501 (1947)', 'Piper Aircraft Co. v. Reyno, 454 U.S. 235 (1981)']],

  // ─── INTERNATIONAL HUMANITARIAN LAW ──────────────────────────────────────

  ['Grave Breaches (Geneva Conventions)', 'Specific serious violations of the four Geneva Conventions of 1949 that trigger mandatory universal jurisdiction — each state party must search for persons alleged to have committed grave breaches and bring them before its own courts or extradite them to another state party (aut dedere aut judicare). Grave breaches include: willful killing, torture or inhuman treatment, willfully causing great suffering or serious injury, extensive destruction of property not justified by military necessity, compelling a prisoner of war to serve in hostile forces, willfully depriving a protected person of fair trial rights, unlawful deportation or transfer, and unlawful confinement. Additional Protocol I (1977) expanded grave breaches to include attacks on civilian populations, perfidious use of protected emblems, and transfer of populations into occupied territory. The ICTY and ICTR applied grave breach provisions extensively. Example: During an armed conflict, military forces execute 20 captured enemy combatants. This constitutes a grave breach (willful killing of prisoners of war) under the Third Geneva Convention, triggering an obligation on all state parties to prosecute or extradite the perpetrators.', 'international_law', 'International', ['Universality Principle', 'War Crimes', 'International Criminal Court', 'Geneva Conventions'], ['Geneva Convention III Art. 130', 'Additional Protocol I Art. 85']],

  ['Principle of Non-Refoulement', 'The principle prohibiting states from returning (refouling) a person to a territory where they would face a real risk of persecution, torture, cruel or inhuman treatment, or other serious harm. Originally codified in the 1951 Refugee Convention Art. 33(1), which prohibits return to territories where life or freedom would be threatened on account of race, religion, nationality, membership of a particular social group, or political opinion. The principle has expanded beyond refugee law: the Convention Against Torture Art. 3 provides an absolute prohibition on return to torture (no exceptions), and the ECHR Art. 3 prohibits return to face inhuman or degrading treatment. Unlike the Refugee Convention exception (Art. 33(2) — national security or danger to the community), the CAT prohibition on return to torture is non-derogable. Non-refoulement has arguably achieved the status of customary international law and possibly jus cogens. Example: An asylum seeker from State A, where they face political persecution, arrives in State B. Even if State B determines the person does not qualify for refugee status, it cannot return them to State A if there is a substantial risk of torture — the CAT non-refoulement obligation is absolute.', 'international_law', 'International', ['Jus Cogens', 'Customary International Law', 'Refugee Convention', 'Convention Against Torture'], ['1951 Refugee Convention Art. 33', 'Convention Against Torture Art. 3', 'Chahal v. United Kingdom, ECHR (1996)']],

  ['Responsibility to Protect (R2P)', 'A political commitment endorsed by the UN General Assembly at the 2005 World Summit providing that: (1) each state has the responsibility to protect its populations from genocide, war crimes, ethnic cleansing, and crimes against humanity; (2) the international community should assist states in fulfilling this responsibility; and (3) when a state manifestly fails to protect its population, the international community should take collective action through the Security Council, including, if necessary, the use of force as a last resort. R2P is not a binding legal norm but a political framework that reframes sovereignty as responsibility rather than an absolute right. R2P was invoked in the 2011 Libya intervention (UNSC Resolution 1973) but has been controversial — critics argue the Libya intervention exceeded its mandate (regime change) and undermined future R2P invocations. Russia and China have resisted R2P applications in Syria and elsewhere. Example: In 2011, the Security Council authorized military intervention in Libya under R2P after the Gaddafi regime threatened mass atrocities against civilians in Benghazi. The intervention, led by NATO, succeeded in protecting civilians but ultimately contributed to regime change — generating lasting controversy about the scope of R2P.', 'international_law', 'International', ['Sovereign Immunity', 'Self-Determination', 'UN Security Council', 'Humanitarian Intervention'], ['2005 World Summit Outcome Document ¶¶138-139', 'UNSC Resolution 1973 (2011)']],

];

module.exports = { terms };
