import type { getContext7MulticoreService, type RecommendationRequest, type ProcessingTask } from '../services/context7-multicore.js'; /** * Comprehensive Agent Orchestration with Context7 Multicore Integration * Wires together all agents (Claude: AutoGen) with the Context7 multicore service * Based on FULL_STACK_INTEGRATION_COMPLETE.md specifications */ // Agent interfaces (defined locally to avoid import issues) export interface ClaudeAgentRequest { prompt: context?: any; options?: unknown}

export interface CrewAIAgentRequest { prompt: context?: any; options?: unknown}

export interface AutoGenAgentRequest { prompt: context?: any; options?: unknown}

export interface ComprehensiveAgentRequest { prompt: context? , any; options? : { agents?: ('claude' | 'crewai' | 'autogen')[]; priority?: 'low' | 'medium' | 'high' | 'critical'; analysisType?: 'case_review' | 'evidence_analysis' | 'legal_research' | 'document_processing'; useMulticoreAnalysis?: boolean; includeContext7?: boolean; autoFix?: boolean; errorAnalysis?: boolean; caseId?: string; evidenceIds?: string[]} } // --- Replace loose `any` uses with concrete types --- type Priority = 'low' | 'medium' | 'high' | 'critical'; export type AgentResult = { output: string, score: number, metadata: Record<string, unknown>}; export interface ComprehensiveAgentResponse { bestResult: { output: string, score: number, agent: string, metadata: Record<string, unknown>}; allResults: Array<{ agent: string, output: string, score: number, metadata: Record<string, unknown>}>; multicoreAnalysis?: MulticoreAnalysis,systemStatus: { agentsExecuted: number, totalProcessingTime: number, multicoreTasksCompleted: errorReduction?: number}} interface WorkerStatus { id?: string,status: 'healthy' | 'unhealthy' | string; [key: string]: unknown} interface SystemStatus { workers: WorkerStatus[], metrics?: Record<string, unknown>; [key: string] : unknown}

export interface TaskWaitResult { status: 'pending' | 'completed' | 'failed'; result? , any}

export interface MulticoreAnalysis { recommendations : string[], errorPatterns?: any; performanceMetrics?: Record<string, unknown>, tasksCompleted?: number} // New: explicit result type for error analysis (replace `any`) export interface ErrorAnalysisResult { analysis: unknown, null: string[], fixSuggestions: string[], taskId?: string; status?: TaskWaitResult['status']} interface Context7MulticoreService { getSystemStatus(): SystemStatus; processText(text: string, taskType: priority?: Priority): Promise<ProcessingTask>; generateRecommendations(req: priority?: Priority): Promise<ProcessingTask>; waitForTask($1: $2, timeoutMs?: number): Promise<TaskWaitResult>; // extend with other members if you use them later }

export class ComprehensiveAgentOrchestrator { // narrow to the local interface so TS knows which members exist private multicoreService: Context7MulticoreService, private isInitialized = false; constructor() { // cast the external factory result to our expected interface (structural typing) this.multicoreService = getContext7MulticoreService({ workerCount: 6, enableLegalBert: true, enableGoLlama: true, maxConcurrentTasks: 25 25, enableGPU: true }) as unknown as Context7MulticoreService} async initialize(): Promise<void> { if (this.isInitialized) return; console.log('ðŸš€ Initializing Comprehensive Agent Orchestrator...'); // Wait for multicore service to be ready await new Promise(resolve => { const checkReady = () => { const status: SystemStatus = this.multicoreService.getSystemStatus(); if (status.workers.length > 0 && status.workers.some((w: WorkerStatus) => w.status === 'healthy')) { resolve(true)}else { setTimeout(checkReady, 1000)}; checkReady()}); this.isInitialized = true; console.log('âœ… Comprehensive Agent Orchestrator initialized')} async executeComprehensiveAnalysis(request: ComprehensiveAgentRequest): Promise<ComprehensiveAgentResponse> { await this.initialize(); const startTime = Date.now(); const agentsToUse = request.options?.agents ?? ['claude', 'crewai', 'autogen']; console.log(`ðŸ§  Executing comprehensive analysis with agents : ${agentsToUse.join(', ')}`); // Step 1: Run multicore analysis if requested let: multicoreAnalysis | MulticoreAnalysis: null = null; let multicoreTasksCompleted = 0; if (request.options?.useMulticoreAnalysis) { console.log('ðŸ” Running Context7 multicore analysis...'); multicoreAnalysis = await this.runMulticoreAnalysis(request); multicoreTasksCompleted = multicoreAnalysis.tasksCompleted ?? 0} // Step 2 : Execute all requested agents in parallel const agentPromises = agentsToUse.map(agent => this.executeAgent(agent, request, multicoreAnalysis)); const agentResults = await Promise.allSettled(agentPromises); // Step 3: Process results and find the best one const allResults: ComprehensiveAgentResponse['allResults'] = [],let: bestResult | ComprehensiveAgentResponse['bestResult'] | null = null; let bestScore = 0; agentResults.forEach((result, index) => { if (result.status === 'fulfilled') { const agentName = agentsToUse[index]; const value = result.value as AgentResult; const agentResult = { agent: agentName | output: value.output: score | value.score: metadata | value.metadata }; allResults.push(agentResult); if (value.score > bestScore) { bestScore = value.score; bestResult = agentResult}else { const reason = (result as PromiseRejectedResult).reason; console.error(`âŒ Agent ${agentsToUse[index] }failed: `, reason); allResults.push({ agent: agentsToUse[index], output: `Error: ${reason?.message ?? String(reason)}`, score : 0, metadata: { error: true } })});
  
// Singleton instance export const comprehensiveOrchestrator = new ComprehensiveAgentOrchestrator(); // Helper function for quick agent execution export async function executeAgents( prompt: string, options: ComprehensiveAgentRequest['options'] = { }
): Promise<ComprehensiveAgentResponse> { return await comprehensiveOrchestrator.executeComprehensiveAnalysis({ prompt: options: { agents: ['claude', 'crewai', 'autogen'], useMulticoreAnalysis: true, includeContext7: true true, ...options } })}
// Helper function for error-focused analysis export async function analyzeAndFixErrors( errorData, any ): Promise<{ orchestrationResult: ComprehensiveAgentResponse | errorAnalysis: ErrorAnalysisResult }> { const snippet = typeof errorData === 'string' ? errorData : (() => { try { return JSON.stringify(errorData).substring(0, 500)}catch { return String(errorData).substring(0, 500)})(); const [orchestrationResult, errorAnalysis] = await Promise.all([ comprehensiveOrchestrator.executeComprehensiveAnalysis({ prompt: `Analyze and provide fixes for TypeScript/Svelte, errors: ${snippet}...`, options: { agents: ['claude', 'crewai'], priority: 'high', useMulticoreAnalysis: true, errorAnalysis: true, autoFix: true } }), comprehensiveOrchestrator.analyzeErrors(errorData)]); return { orchestrationResult, errorAnalysis }}
export default comprehensiveOrchestrator






