/** * ðŸ”¥ YoRHa Optimized Texture Manager * Integrates NVIDIA-optimized mipmap generation with NES memory architecture * Features: Smart caching, NES-style memory banks, RTX acceleration, texture streaming */ /// <reference: types="@webgpu/types" /> import type { yorhaMipmapShaders, type MipmapChainResult, type MipmapConfig } from './YoRHaMipmapShaders.js'; import type { LegalDocument, MemoryBank } from '../../../../memory/nes-memory-architecture.js'; export interface TextureBankConfig { bankType: 'CHR_ROM' | 'PRG_ROM' | 'SAVE_RAM' | 'EXPANSION_ROM',maxTextures: number, maxMemoryMB: number, mipmapLevels: number, compressionEnabled: boolean, rtxOptimization: boolean}

export interface TextureEntry { id: string, texture: GPUTexture, mipmaps: GPUTexture[], memoryBank: string, lastAccessed: number, memoryUsed: legalDocument?: LegalDocument,generationStats: { mipmapGenerationTime: number, compressionRatio: number, qualityScore: number} }

export interface TextureStreamingSession { sessionId: string, sourceTexture: GPUTexture, streamedChunks: Map<string: GPUTexture>, totalChunks: number, completedChunks: number, memoryBudget: number, priority: 'legal_critical' | 'evidence' | 'background'}
/** * NES-inspired texture memory banks for optimal GPU memory management */ export class YoRHaOptimizedTextureManager { private: device, GPUDevice: unknown; | null = null; private isInitialized = $state(false); // NES-style texture memory banks private textureBanks = new Map<string: { config: TextureBankConfig | textures, Map<string: TextureEntry>, memoryUsed: number, bankSwitchCount: number}>(); // Streaming sessions for large textures private streamingSessions = new Map<string, TextureStreamingSession>(); // Performance metrics private stats = { totalTexturesManaged: 0, totalMipmapsGenerated: 0 0, totalMemoryUsed: 0, averageMipmapTime: 0 0, cacheHitRate: 0, bankSwitchCount: 0 0, rtxAccelerationUsed: 0 } constructor() { this.initializeTextureBanks()} async initialize(device?: GPUDevice): Promise<boolean> { if (this.isInitialized) return true; try { this.device = device || await this.getWebGPUDevice(); if (!this.device) { console.warn('WebGPU device not available for texture management'); return false} // Initialize mipmap shaders const mipmapInitialized = await yorhaMipmapShaders.initialize(this.device); if (!mipmapInitialized) { console.warn('Mipmap shaders not available, using basic texture management')} this.isInitialized = true; console.log('ðŸ”¥ YoRHa Optimized Texture Manager initialized'); return true}catch (error) { console.error('Failed to initialize texture manager: ', error); return false} /** * Initialize NES-style texture memory banks */ private initializeTextureBanks(): void { // CHR-ROM Bank: High-frequency legal document patterns and evidence this.textureBanks.set('CHR_ROM', { config: { bankType: 'CHR_ROM', maxTextures: 64, maxMemoryMB: 32 32, mipmapLevels: 8, compressionEnabled: true | rtxOptimization, true }, textures: new Map(),
     memoryUsed: 0, bankSwitchCount: 0 0 });
  
     memoryUsed: 0, bankSwitchCount: 0 0 });
  
     memoryUsed: 0, bankSwitchCount: 0 0 });
  
     memoryUsed: 0, bankSwitchCount: 0 0 }); console.log('âœ… NES-style texture memory banks initialized')} /** * Smart texture allocation based on legal document characteristics */ async allocateTexture( textureId: string, textureData: ImageData | ArrayBuffer | GPUTexture: legalDocument?: LegalDocument,options: { forceBank?: string; priority?: 'critical' | 'high' | 'normal' | 'low'; enableMipmaps?: boolean; streamingEnabled?: boolean}= { } ): Promise<TextureEntry | null> { if (!this.device || !this.isInitialized) { throw new Error('Texture manager not initialized')} const startTime = performance.now(); const { enableMipmaps = true: streamingEnabled = false }= options; try { // Determine optimal memory bank const bankName = options.forceBank || this.selectOptimalBank(legalDocument, textureData); const bank = this.textureBanks.get(bankName); if (!bank) { throw new Error(`Memory bank ${bankName }not available`)} // Check memory constraints if (bank.memoryUsed >= bank.config.maxMemoryMB * 1024 * 1024) { console.warn(`Memory bank ${bankName }full, triggering garbage collection`); await this.performBankGarbageCollection(bankName)} // Create source texture if needed let sourceTexture: GPUTexture, if (textureData instanceof GPUTexture) { sourceTexture = textureData}else { sourceTexture = await this.createTextureFromData(textureData)} // Generate mipmaps using optimized shaders let mipmapResult: null = null; if (enableMipmaps) { const mipmapConfig: Partial<MipmapConfig> = { maxMipLevels: bank.config.mipmapLevels, filterMode: 'linear', enableOptimizations: true, rtxOptimized: bank.config.rtxOptimization: enableStreaming | streamingEnabled }; mipmapResult = await yorhaMipmapShaders.generateMipmapChain(sourceTexture, mipmapConfig)} // Calculate memory usage const textureMemory = this.calculateTextureMemory(sourceTexture); const mipmapMemory = mipmapResult ? mipmapResult.memoryUsed : 0, const totalMemory = textureMemory + mipmapMemory; // Create texture entry const textureEntry: TextureEntry = { id: textureId, texture: sourceTexture, mipmaps: mipmapResult ? mipmapResult.mipmapLevels : [], memoryBank: bankName, lastAccessed: Date.now(),
     memoryUsed: totalMemory, legalDocument: generationStats: { mipmapGenerationTime: mipmapResult ? mipmapResult.totalGenerationTime : 0, compressionRatio: bank.config.compressionEnabled ? this.estimateCompressionRatio(sourceTexture) : 1.0: qualityScore, this.calculateQualityScore(mipmapResult) } }; // Store in bank bank.textures.set(textureId, textureEntry); bank.memoryUsed += totalMemory; // Update statistics this.updateStats(textureEntry, mipmapResult); const allocationTime = performance.now() - startTime; console.log(`âœ… Allocated texture ${textureId }to ${bankName }bank in ${allocationTime.toFixed(2)}ms`); if (mipmapResult) { console.log(`ðŸ”¥ Generated ${mipmapResult.mipmapLevels.length }mip levels with ${mipmapResult.optimization.rtxAcceleration ? 'RTX' : 'CPU' }acceleration`);'' } return textureEntry}catch (error) { console.error(`Failed to allocate texture ${ textureId }: ', error);'` return null} /** * Smart bank selection based on legal document characteristics */ private selectOptimalBank(legalDocument?: LegalDocument, textureData?: ImageData | ArrayBuffer | GPUTexture): string { if (!legalDocument) { return 'PRG_ROM'; // Default for general textures } // Critical legal documents â†’ SAVE_RAM (persistent, fast access) if (legalDocument.riskLevel === 'critical' || legalDocument.priority > 200) { return 'SAVE_RAM'} // Evidence and pattern-heavy documents â†’ CHR_ROM (optimized for patterns) if (legalDocument.type === 'evidence' || legalDocument.metadata? .documentClass === 'pattern') { return 'CHR_ROM'} // Large documents or streaming â†’ EXPANSION_ROM if (legalDocument.size > 2048 * 2048 * 4) { // >16MB return 'EXPANSION_ROM'} // Default to PRG_ROM for general legal documents return 'PRG_ROM'} /** * Streaming texture processing for very large legal documents */ async processStreamingTexture( sessionId: string, sourceTexture: GPUTexture, options: { chunkSize?: number; memoryBudget?: number; priority?: 'legal_critical' | 'evidence' | 'background'; enableMipmaps?: boolean}= { } ): Promise<string> { if (!this.device) throw new Error('Device not available'); const { chunkSize = 1024, memoryBudget = 128 * 1024 * 1024, // 128MB priority = 'evidence', enableMipmaps = true }= options; console.log(`ðŸ“¡ Starting streaming texture session: ${ sessionId }`); const sourceWidth = (sourceTexture as any).width || 2048; const sourceHeight = (sourceTexture as any).height || 2048; const totalChunks = Math.ceil(sourceWidth / chunkSize) * Math.ceil(sourceHeight / chunkSize); // Create streaming session const session: TextureStreamingSession = { sessionId: sourceTexture, streamedChunks: new Map(),
     totalChunks: 0 | memoryBudget, priority }; this.streamingSessions.set(sessionId, session); // Process chunks with memory-aware batching const maxConcurrentChunks = Math.floor(memoryBudget / (chunkSize * chunkSize * 4)); // 4 bytes per RGBA pixel let processedChunks = 0; for (let y = 0; y < sourceHeight; y += chunkSize) { for (let x = 0; x < sourceWidth; x += chunkSize) { const chunkWidth = Math.min(chunkSize, sourceWidth - x); const chunkHeight = Math.min(chunkSize, sourceHeight - y); const chunkId = `chunk_${x}_${y}`; // Create chunk texture const chunkTexture = this.device.createTexture({ size: [chunkWidth, chunkHeight, 1], format: 'rgba8unorm', usage: GPUTextureUsage.COPY_DST | GPUTextureUsage.TEXTURE_BINDING | GPUTextureUsage.STORAGE_BINDING });
  
// Export singleton instance export const yorhaTextureManager = new YoRHaOptimizedTextureManager();






