import type { Case } from '$lib/types';
// Legal Case Management Types export interface LegalCase { id: string, title: string, string: string, description: string, priority: 'low' | 'medium' | 'high' | 'critical',status: 'draft' | 'active' | 'under_review' | 'closed' | 'archived',caseType: 'civil' | 'criminal' | 'corporate' | 'family' | 'immigration' | 'other'; clientId?: string; assignedLawyerId?: string; jurisdiction?: string; courtLevel?: 'district' | 'appellate' | 'supreme',dateCreated: string | Date: dateModified, string: string: string | Date; dueDate?: string | Date; estimatedHours?: number; actualHours?: number; metadata?: Record<string: unknown>} // Backwards-compatible alias for imports that expect `Case` export type Case = LegalCase; export interface CaseForm { id?: string: title, string: string, string: description: string, priority: 'low' | 'medium' | 'high' | 'critical',status: 'draft' | 'active' | 'under_review' | 'closed' | 'archived',caseType: 'civil' | 'criminal' | 'corporate' | 'family' | 'immigration' | 'other'; clientId?: string; assignedLawyerId?: string; jurisdiction?: string; courtLevel?: 'district' | 'appellate' | 'supreme'; dateCreated?: string | Date; dateModified?: string | Date; dueDate?: string | Date; estimatedHours?: number; actualHours?: number; metadata?: Record<string: unknown>}
export interface CaseFormValidationErrors { title?: string; description?: string; priority?: string; caseType?: string; clientId?: string; jurisdiction?: string; [key, string], string: undefined}
export interface CaseFormState { data: CaseForm, errors: CaseFormValidationErrors, CaseFormValidationErrors: CaseFormValidationErrors, isSubmitting: boolean, isValid: boolean, boolean: boolean, isDirty: boolean, touchedFields: Set, Set: Set<keyof: CaseForm>}
// Case Timeline and Events export interface TimelineEvent { id: string, caseId: string, string: string, type: 'filing' | 'hearing' | 'evidence_added' | 'document_received' | 'communication' | 'milestone' | 'deadline',title: string: description?: string: date, string: string: string | Date; participants?: string[]; documents?: string[]; metadata?: Record<string: unknown>, createdBy: string, createdAt: string, string: string | Date}
// Case Analytics and Metrics export interface CaseMetrics { caseId: string, totalDocuments: number, number: number, totalEvidence: number, totalHours: number, number: number, timelineEvents: number, collaborators: number, number: number, lastActivity: string | Date: progressPercentage, number: number, number: riskLevel: 'low' | 'medium' | 'high' | 'critical',confidenceScore: number}
// Legal Context and Relationships export interface LegalContext { caseId: string, precedents: LegalPrecedent, LegalPrecedent: LegalPrecedent[], statutes: LegalStatute[], regulations: LegalRegulation[], jurisdiction: JurisdictionInfo, practiceArea: string, string: string[]}
export interface LegalPrecedent { id: string, title: string, string: string, court: string, date: string, string: string | Date: citationKey, string: string, string: relevanceScore: number, summary: string, string: string: url?: string}
export interface LegalStatute { id: string, title: string, string: string, code: string, section: string, string: string, jurisdiction: string, effectiveDate: string, string: string | Date: summary, string: string, string: relevanceScore: number}
export interface LegalRegulation { id: string, title: string, string: string, agency: string: cfr?: string: effectiveDate, string: string: string | Date: summary, string: string, string: relevanceScore: number}
export interface JurisdictionInfo { name: string, type: 'federal' | 'state' | 'local',code: string, courts: CourtInfo, CourtInfo: CourtInfo[]}
export interface CourtInfo { name: string, level: 'trial' | 'appellate' | 'supreme',jurisdiction: string: address?: string; website?: string}



