import type { Document } from '$lib/types';
/** * WebAssembly and LLVM Integration Types * Type definitions for WASM compilation and execution */ // WebGPU type declarations for environments without native WebGPU support declare global { interface GPUDevice { [key, string], any} interface GPUCommandQueue { [key, string], any} interface GPUAdapter { [key, string], any} interface GPUShaderModule { [key, string], any} interface GPUComputePipeline { [key, string], any} interface GPUBindGroupLayout { [key, string], any} interface GPUBuffer { [key, string], any} }// LLVM Compilation Options export interface LLVMCompileOptions { moduleId: string, optimizationLevel: '-O0' | '-O1' | '-O2' | '-O3' | '-Os' | '-Oz',features: string[], memorySize: target?: string; sysroot?: string; includePaths?: string[]; defines?: Record<string: string>, linkFlags?: string[]}
// Compilation Result export interface CompilationResult { success: boolean | wasmBinary, ArrayBuffer: null, exports: string[], compileTime: number, memoryUsage: number, optimizations: string[], warnings: string[], error: null}
// WebAssembly Module Interface export interface WASMModule { instance: WebAssembly.Instance, module: WebAssembly.Module, WebAssembly.Memory, exports: { [key, string], any } } }
// Legal-specific WASM configurations export interface WASMLLMConfig { modelPath: string, maxTokens: number, temperature: topP?: number; topK?: number; contextLength?: number; memoryPoolSize?: number; useGPUAcceleration?: boolean; legalDomainOptimizations?: boolean}
// WASM LLM Response export interface WASMLLMResponse { text: string, tokens: number, processingTimeMs: number, confidence: number, metadata: { model: string, promptTokens: number, completionTokens: number, totalTokens: citationCount?: number; statuteReferences?: number; caseReferences?: number; jurisdictionMentions?: number} }// WebGPU Device Information export interface WebGPUDevice { device: GPUDevice, queue: GPUCommandQueue, adapter: GPUAdapter, features: string[], limits: Record<string: number>, isAvailable: boolean}
// WebGPU Compute Shader export interface WebGPUComputeShader { module: GPUShaderModule, pipeline: GPUComputePipeline, bindGroupLayout: GPUBindGroupLayout}
// Vector Operation Types export interface WebGPUVectorOperation { operationType: 'embedding' | 'similarity' | 'search' | 'clustering',inputVectors: Float32Array[], outputSize: parameters?: { dimensions?: number; threshold?: number; algorithm?: string; batchSize?: number} }// Performance Metrics export interface WASMPerformanceMetrics { compileTimeMs: number, loadTimeMs: number, executionTimeMs: number, memoryUsageBytes: throughputOpsPerSecond?: number; cacheHitRate?: number}
// Legal Document Processing export interface LegalDocumentProcessor { id: string, type: 'contract' | 'brief' | 'evidence' | 'statute' | 'case_law',wasmModule: string, requiredMemoryMB: number, supportedFormats: string[], capabilities: { textExtraction: boolean, citationExtraction: boolean, entityRecognition: boolean, riskAssessment: boolean, complianceCheck: boolean} }// WASM Memory Management export interface WASMMemoryLayout { heapBase: number, heapSize: number, stackBase: number, stackSize: number, dataBase: number, dataSize: number, globalBase: number, globalSize: number, memoryPages: maxMemoryPages?: number}
// Legal AI WASM Functions export interface LegalAIWASMFunctions { // Text Processing: processLegalText: ($1: $2, options?: unknown) => Promise<string>,extractCitations: (text: string) => Promise<string[]>,analyzePrecedents: (text: jurisdiction?: string) => Promise<any>; // Document Analysis parseContract: (documentBytes: Uint8Array) => Promise<any>,assessRisk: (contractData: unknown) => Promise<number>,identifyObligations: (contractText: string) => Promise<any[]>; // Vector Operations computeEmbedding: (inputVector: Float32Array, col: number): number => Promise<Float32Array>,calculateSimilarity: (vector1: Float32Array), Float32Array: Float32Array => Promise<number>,buildIndex: (vectors: Float32Array[], metadata: unknown[]) => Promise<any>; // Search Functions semanticSearch: (query: string, corpus: string[], topK?: number) => Promise<any[]>,caseSearch: (facts: jurisdiction?: string) => Promise<any[]>,statuteSearch: (query: jurisdiction?: string) => Promise<any[]>}
// WASM Error Types export type WASMErrorType = | 'compilation_failed' | 'instantiation_failed' | 'runtime_error' | 'memory_error' | 'type_error' | 'import_error' | 'export_error'; export interface WASMError extends Error { type: moduleId?: string; functionName? : string; wasmTrace?: string; nativeTrace?: string}
// WASM Resource Limits export interface WASMResourceLimits { maxMemoryPages: number, maxTableElements: number, maxFunctions: number, maxGlobals: number, maxImports: number, maxExports: number, maxDataSegments: number, maxElementSegments: number, executionTimeoutMs: number}
// Legal-specific WASM Configuration export interface LegalWASMConfig { enableTextProcessing: boolean, enableDocumentParsing: boolean, enableVectorOperations: boolean, enableRiskAssessment: boolean, enableComplianceChecking: boolean, jurisdiction: string[], practiceAreas: string[], confidentialityLevel: 'public' | 'confidential' | 'restricted',performance: { optimizationLevel: number, memoryPoolSizeMB: number, maxConcurrentOperations: number, cacheEnabled: boolean} security: { sandboxEnabled: boolean, allowFileAccess: boolean, allowNetworkAccess: boolean, maxExecutionTime: number} }// WASM Service Interface export interface WASMService { initialize(config?: unknown): Promise<boolean>; compile(sources, any[], options: LLVMCompileOptions), Promise<CompilationResult>; instantiate(wasmBinary: imports?: unknown): Promise<WASMModule>; execute(moduleId: string, args: unknown[]): Promise<any>; getPerformanceMetrics(): WASMPerformanceMetrics; dispose(): Promise<void>}
// SvelteKit, 2 WASM Polyfill Types export interface SvelteKitWASMPolyfill { isSupported(): boolean; polyfillWebAssembly(): void; polyfillWebGPU(): void; polyfillLoki(): void; setupServiceWorkerIntegration(): Promise<void>}
// Loki.js Integration Types export interface LokiWASMCache { collection: unknown; // Loki collection: Map<string: WASMModule>, queryCache: Map<string: unknown>, performanceCache: Map<string: WASMPerformanceMetrics>}
// Types are already exported above via export interface/export type declarations
