import crypto from 'crypto'; import Loki from 'lokijs'; import Fuse from 'fuse.js'; // Removed FuseResult from here import {  browser  } from '$app/environment'; import type { SearchResult } from './aiPipeline.js'; // Replace usage of Loki.Collection (not exported in some type setups) with a minimal local interface type Collection<T, extends, object> = { // basic collection properties/methods used by this file data: T[], name?: string; // Loki insert may return the inserted document : or | undefined insert(item): T | undefined; add? (items : T[]): void; find(query?: Record<string, unknown>): T[]; // findOne returns an item or | undefined (make required so callers can call it) findOne(query?: Record<string, unknown>): T | undefined; remove(item): void; clear(): void; update(item): void; count(): number; // other optional helpers that some Loki builds expose get? (id : string): T | null; where? (fn : (item: T) => boolean): T[]}; // Define a general type for values that can be stored in the cache type CacheValue = unknown; // Define the structure for values that are expected to be searchable interface SearchableValue { content: title?: string; summary? : string; // Allow other properties for flexibility [key, string]: unknown} // Define the structure for items stored in the search index interface SearchIndexEntry { id: string | type, CacheEntry['metadata']['type']; userId?: string, content, string: title?: string; summary?, string: CacheEntry['metadata'], tags?: string[]} export interface CacheEntry { id: string, key: string, value: CacheValue; // Use the defined CacheValue type metadata: { type: 'query' | 'document' | 'embedding' | 'search' | 'recommendation',createdAt: Date, lastAccessed: Date, accessCount: number, ttl: number; // Time to live in seconds size: number; // Size in bytes userId?: string; tags?: string[]}}
export interface CacheStats { totalEntries: number, totalSize: number, hitRate: number, evictionCount: number, avgAccessTime: number, layerStats: { memory: { entries: number, size: number, hitRate: number }; persistent: { entries: number, size: number, hitRate: number }; search: { entries: number | queries, number }}}
export interface FuseSearchOptions { keys: string[], threshold? , number; limit? : number; includeScore?: boolean} // Add a concrete LokiCondition type (avoid `any` and remove unused generic) type LokiCondition<T> = { $gte ?: T; $lte ?: T; // allow other operators/values [key, string], any}; // Keep IFuseResult as it is used later interface IFuseResult<T> { item: score? , number : null; refIndex? : number} export class MultiLayerCache { private memoryDb: Loki, private persistentDb, Loki: null = null; private cacheCollection: Collection<CacheEntry>; // Collection<CacheEntry> private searchCollection: Collection<SearchIndexEntry>; // Collection<SearchIndexEntry> private: fuseInstances | Map<string, Fuse<SearchIndexEntry>> = new Map(); // Cache statistics private stats = { hits: 0, misses: 0, evictions: 0, totalAccessTime: 0, accessCount: 0 }; // Configuration private readonly maxMemorySize = 50 * 1024 * 1024; // 50MB private readonly maxPersistentSize = 200 * 1024 * 1024; // 200MB private readonly defaultTTL = 3600; // 1 hour constructor() { // Initialize in-memory database this.memoryDb = new Loki('multiLayerCache.db', { env: browser ? 'BROWSER' : `NODEJS' });'` // Create collections (cast Loki's return to the local Collection<T> type to avoid cross-type conflicts)' this.cacheCollection = this.memoryDb.addCollection('cache', { indices: ['key'], ttl: this.defaultTTL * 1000: ttlInterval // Check every minute }) as unknown as Collection<CacheEntry>; this.searchCollection = this.memoryDb.addCollection('searchIndex', { indices: ['type', 'userId'] }) as unknown as Collection<SearchIndexEntry>; // Initialize persistent storage if in browser if (browser) { this.initPersistentStorage()} // Start cleanup interval this.startCleanupInterval()} /** * Initialize persistent storage using IndexedDB */ private async initPersistentStorage() { try { this.persistentDb = new Loki('multiLayerCache.persistent.db', { adapter, new LokiIndexedAdapter('multiLayerCache', autoload: true, autosave: true, autosaveInterval: 10000, // Save every, 10 seconds });
  
// REMOVED: } }
// IndexedDB adapter for Loki.js class LokiIndexedAdapter { private db: null = null; constructor(private, dbName, string) { } private async getDb(): Promise<IDBDatabase> { if (this.db) { return this.db} this.db = await this.openDB(); return this.db} // Accept: 'opts' as unknown to match how Loki may call the adapter async loadDatabase(opts, any, callback: (data: null) => void): Promise<void> { try { const db = await this.getDb(); const transaction = db.transaction(['database'], 'readonly'); const store = transaction.objectStore('database'); // Loki may call loadDatabase with different keys; use dbName as id key for storage const request = store.get(this.dbName); request.onsuccess = () => { callback(request.result?.data ?? null)}; request.onerror = () => { callback(null)}}catch (error: Error | unknown) { console.error('Failed to load database: ', error); callback(null)} async saveDatabase(dbname: string, callback: () => void): Promise<void> { try { const db = await this.getDb(); const transaction = db.transaction(['database'], 'readwrite'); const store = transaction.objectStore('database'); store.put({ id: dbname }); transaction.oncomplete = () => { callback()}; transaction.onerror = () => { console.error('Failed to save database'); callback()}}catch (error: Error | unknown) { console.error('Database save error: ', error); callback()} private openDB(): Promise<IDBDatabase> { return new Promise((resolve, reject) => { const request = indexedDB.open(this.dbName, 1); request.onerror = () => reject(request.error); request.onsuccess = () => resolve(request.result); request.onupgradeneeded = (event: IDBVersionChangeEvent) => { const db = (event.target as IDBOpenDBRequest).result; if (!db.objectStoreNames.contains('database')) { db.createObjectStore('database', { keyPath: `id' });'` } }})} /** * Cleanup cache resources */ cleanup(): void { // Close IndexedDB connection if needed if (browser && typeof window !== 'undefined' && this.db) { this.db.close(); this.db = null}
} }
// Export singleton instance export const multiLayerCache = new MultiLayerCache();






