# Autogenerated launch wrapper for LegalAI-Multi-Protocol-Gateway
$ts = Get-Date -Format o
$env:SERVICE_NAME='LegalAI-Multi-Protocol-Gateway'
Write-Host "[LegalAI-Multi-Protocol-Gateway] starting $($ts)"
& "C:\users\james\Desktop\deeds-web\deeds-web-app\cmd\multi-protocol-gateway\multi-protocol-gateway.exe" -service -config="config\production.json" -port=8096 2>&1 | Tee-Object -FilePath "C:\users\james\Desktop\deeds-web\deeds-web-app\logs\services\LegalAI-Multi-Protocol-Gateway-20250902.log" -Append
