# Autogenerated launch wrapper for LegalAI-Health-Server
$ts = Get-Date -Format o
$env:SERVICE_NAME='LegalAI-Health-Server'
Write-Host "[LegalAI-Health-Server] starting $($ts)"
& "C:\users\james\Desktop\deeds-web\deeds-web-app\cmd\health-server\health-server.exe" -service -config="config\production.json" -port=8099 2>&1 | Tee-Object -FilePath "C:\users\james\Desktop\deeds-web\deeds-web-app\logs\services\LegalAI-Health-Server-20250902.log" -Append
