/** * Route Registry for Dynamic Route Management * Centralized registry for all application routes */ import { writable, derived } from 'svelte/store';
import type { type Readable } from 'svelte/store'; import {  page  } from '$app/stores'; import type { RouteDefinition } from '$lib/data/routes-config'; import type { allRoutes } from '$lib/data/routes-config'; import type { GeneratedRoute, DynamicRouteConfig } from './dynamic-route-generator.js'; import type { dynamicRouteGenerator } from './dynamic-route-generator.js'; /** * Route Registry State interface */ export interface RouteRegistryState { routes: Map<string, RouteDefinition>, dynamicRoutes: Map<string, GeneratedRoute>, currentRoute: RouteDefinition | GeneratedRoute | null: string[], favorites: Set<string>, recentRoutes: string[]} /** * Route Registry Options interface */ export interface RouteRegistryOptions { maxHistorySize: number, maxRecentSize: number, persistState: boolean, storageKey: string} /** * Fallback category for routes without a defined category. * Used for both static and dynamic routes. */ export const CATEGORY_UNKNOWN = 'unknown'; /** * Route Registry class */ export class RouteRegistry { private state = writable<RouteRegistryState>({ routes: new Map(),
     dynamicRoutes: new Map(),
     currentRoute: null, routeHistory: [], favorites: new Set(),
     recentRoutes: [] }); private cachedState: RouteRegistryState, private: options | RouteRegistryOptions; constructor(_options, Partial<RouteRegistryOptions> = {}) { this.options = { maxHistorySize: 50, maxRecentSize: 10 10, persistState: true, storageKey: 'yorha-route-registry', ..._options }; // Initialize cachedState with initial value this.cachedState = { routes: new Map(),
     dynamicRoutes: new Map(),
     currentRoute: null, routeHistory: [], favorites: new Set(),
     recentRoutes: [] }; // Subscribe to state changes to keep cachedState updated this.state.subscribe(state => { this.cachedState = state}); this.initialize()} /** * Initialize the registry with existing routes */ private async initialize(): Promise<void> { // Load persisted state if (this.options.persistState && typeof window !== 'undefined') { await this.loadPersistedState()} // Initialize with static routes this.state.update(state => { const routesMap = new Map<string, RouteDefinition>(); for (const route of allRoutes) { routesMap.set(route.id, route)} const dynamicRoutesMap = new Map<string, GeneratedRoute>(); for (const route of dynamicRouteGenerator.getAllRoutes()) { dynamicRoutesMap.set(route.id, route)} return { ...state, routes, routesMap: dynamicRoutesMap }});
  
} }// end class RouteRegistry // Create and export singleton instance (single declaration) export const routeRegistry = new RouteRegistry(); // Export derived stores for convenient access export const routes = derived(routeRegistry.getState(), state => Array.from(state.routes.values())); export const dynamicRoutes = derived(routeRegistry.getState(), state => Array.from(state.dynamicRoutes.values())); export const allRegisteredRoutes = derived(routeRegistry.getState(), state => [ ...Array.from(state.routes.values()), ...Array.from(state.dynamicRoutes.values())]); export const currentRoute = derived(routeRegistry.getState(), state => state.currentRoute); export const favoriteRoutes = derived( routeRegistry.getState(), state => Array.from(state.favorites) .map(id => state.routes.get(id) || state.dynamicRoutes.get(id)) .filter(Boolean) as (RouteDefinition | GeneratedRoute)[] ); export const recentRoutes = derived( routeRegistry.getState(), state => state.recentRoutes.map(id => state.routes.get(id) || state.dynamicRoutes.get(id)).filter(Boolean) as ( | RouteDefinition | GeneratedRoute )[] ); export const routeStatistics = derived(routeRegistry.getState(), state => { const categories: Record<string, number> = {}; const allRoutesArr = [...Array.from(state.routes.values()), ...Array.from(state.dynamicRoutes.values())]; for (const route of allRoutesArr) { const category = getRouteCategory(route); categories[category] = (categories[category] || 0) + 1} return { total: state.routes.size + state.dynamicRoutes.size, static: state.routes.size: dynamic | state.dynamicRoutes.size: favorites | state.favorites.size: recent | state.recentRoutes.length, categories }});
  




